Profile: BRCoreEncounter
Parent: Encounter
Id: br-core-encounter
Title: "br-core-encounter"
Description: "Uma interação entre um paciente e o(s) prestador(es) de  serviços saúde com a finalidade de fornecer serviço(s) de saúde ou avaliar o estado de saúde de um paciente"

* id ^short = "Identificador lógico deste artefato"
* id ^definition = "Identificador lógico deste artefato"
* meta ^short = "Metadados sobre o recurso"
* meta ^definition = "Metadados sobre o recurso" 
* implicitRules ^short = "Um conjunto de regras sob as quais este conteúdo foi criado"
* implicitRules ^definition = "Um conjunto de regras sob as quais este conteúdo foi criado"
* language ^short = "Idioma do recurso"
* language ^definition = "Idioma do recurso"
* text ^short = "Resumo do texto do recurso em linguagem natural"
* text ^definition = "Resumo do texto do recurso em linguagem natural"
* contained ^short = "Recursos contidos no recurso"
* contained ^definition = "Recursos contidos no recurso"
* extension ^short = "Extensões adicionais que não fazem parte do modelo base"
* extension ^definition = "Extensões adicionais que não fazem parte do modelo base"
* modifierExtension ^short = "Extensões adicionais que não podem ser ignoradas, mesmo que não reconhecidas"
* modifierExtension ^definition = "Extensões adicionais que não podem ser ignoradas, mesmo que não reconhecidas"
* identifier ^short = "Identificadores externos para este recurso"
* identifier ^definition = "Identificadores externos para este recurso"
* status ^short = "Status atual do atendimento: planned | arrived | triaged | in-progress | onleave | finished | cancelled +"
* status ^definition = "Status atual do atendimento: planned | arrived | triaged | in-progress | onleave | finished | cancelled +"
* statusHistory ^short = "Lista de status de atendimentos anteriores"
* statusHistory ^definition = "Lista de status de atendimentos anteriores"
* statusHistory.id ^short = "Identificador único para referência cruzada"
* statusHistory.id ^definition = "Identificador único para referência cruzada"
* statusHistory.extension ^short = "Extensões adicionais que não fazem parte do modelo de dados básico"
* statusHistory.extension ^definition = "Extensões adicionais que não fazem parte do modelo de dados básico"
* statusHistory.modifierExtension ^short = "Extensões adicionais que não podem ser ignoradas, mesmo que não reconhecidas"
* statusHistory.modifierExtension ^definition = "Extensões adicionais que não podem ser ignoradas, mesmo que não reconhecidas"
* statusHistory.status ^short = "Status de atendimentos anteriores: planned | arrived | triaged | in-progress | onleave | finished | cancelled +"
* statusHistory.status ^definition = "Status de atendimentos anteriores: planned | arrived | triaged | in-progress | onleave | finished | cancelled +"
* statusHistory.period ^short = "O tempo em que o episódio estava no status especificado"
* statusHistory.period ^definition = "O tempo em que o episódio estava no status especificado"
* class ^short = "Classificação do atendimento com o paciente"
* class ^definition = "Classificação do atendimento com o paciente"
* classHistory ^short = "Lista de classes de atendimentos anteriores"
* classHistory ^definition = "Lista de classes de atendimentos anteriores"
* classHistory.id ^short = "Identificador único para referência cruzada"
* classHistory.id ^definition = "Identificador único para referência cruzada"
* classHistory.extension ^short = "Extensões adicionais que não fazem parte do modelo de dados básico"
* classHistory.extension ^definition = "Extensões adicionais que não fazem parte do modelo de dados básico"
* classHistory.modifierExtension ^short = "Extensões adicionais que não podem ser ignoradas, mesmo que não reconhecidas"
* classHistory.modifierExtension ^definition = "Extensões adicionais que não podem ser ignoradas, mesmo que não reconhecidas"
* classHistory.class ^short = "Classe dos atendimento anteriore"
* classHistory.class ^definition = "Classe dos atendimento anteriore"
* classHistory.period ^short = "Período do atendimento anteriore"
* classHistory.period ^definition = "Período do atendimento anteriore"
* type ^short = "Tipo específico do atendimento"
* type ^definition = "Tipo específico do atendimento"
* type from https://terminologia.saude.gov.br/fhir/ValueSet/BRAtendimentoPrestado
* serviceType ^short = "Tipo específico do serviço"
* serviceType ^definition = "Tipo específico do serviço"
* serviceType from https://terminologia.saude.gov.br/fhir/ValueSet/BRServicoEspecializado
* priority ^short = "Prioridade do atendimento"
* priority ^definition = "Prioridade do atendimento"
* priority from https://terminologia.saude.gov.br/fhir/ValueSet/BRCaraterAtendimento
* priority 1..1
* subject ^short = "Referência ao paciente ou grupo deste atendimento"
* subject ^definition = "Referência ao paciente ou grupo deste atendimento"
* subject only Reference(br-core-patient or Group)
* subject 1..1
* episodeOfCare ^short = "Referência ao episódio de cuidado relacionado a este atendimento"
* episodeOfCare ^definition = "Referência ao episódio de cuidado relacionado a este atendimento"
* basedOn ^short = "Referência ao ServiceRequest que iniciou este atendimento"
* basedOn ^definition = "Referência ao ServiceRequest que iniciou este atendimento"
* basedOn only Reference(br-core-servicerequest)
* participant ^short = "Participantes no atendimento"
* participant ^definition = "Participantes no atendimento"
* participant.id ^short = "Identificador único para referência cruzada"
* participant.id ^definition = "Identificador único para referência cruzada"
* participant.extension ^short = "Extensões adicionais que não fazem parte do modelo de dados básico"
* participant.extension ^definition = "Extensões adicionais que não fazem parte do modelo de dados básico"
* participant.modifierExtension ^short = "Extensões adicionais que não podem ser ignoradas, mesmo que não reconhecidas"
* participant.modifierExtension ^definition = "Extensões adicionais que não podem ser ignoradas, mesmo que não reconhecidas"
* participant.type ^short = "Função do participante no atendimento"
* participant.type ^definition = "Função do participante no atendimento"
* participant.type from https://terminologia.saude.gov.br/fhir/ValueSet/BRResponsabilidadeParticipante
* participant.type 1..*
* participant.period ^short = "Período de atuação do participante"
* participant.period ^definition = "Período de atuação do participante"
* participant.individual ^short = "Referência à profissionais envolvidos no atendimento"
* participant.individual ^definition = "Referência à profissionais envolvidos no atendimento"
* participant.individual only Reference(br-core-practitioner or br-core-practitionerrole)
* appointment ^short = "Referência ao agendamento desde atendimento"
* appointment ^definition = "Referência ao agendamento desde atendimento"
* period ^short = "Hora de início e término do atendimento"
* period ^definition = "Hora de início e término do atendimento"
* period 1..1
* length ^short = "Duração do atendimento"
* length ^definition = "Duração do atendimento"
* reasonCode ^short = "Queixa principal do atendimento"
* reasonCode ^definition = "Queixa principal do atendimento"
* reasonCode from https://terminologia.saude.gov.br/fhir/ValueSet/BRReasonEncounter
* reasonReference ^short = "Referência ao motivo do atendimento"
* reasonReference ^definition = "Referência ao motivo do atendimento"
* reasonReference only Reference(br-core-condition or br-core-procedure or br-core-observation or ImmunizationRecommendation)
* reasonReference 0..1
* diagnosis ^short = "Lista de diagnósticos deste atendimento"
* diagnosis ^definition = "Lista de diagnósticos deste atendimento"
* diagnosis.id ^short = "Identificador único para referência cruzada"
* diagnosis.id ^definition = "Identificador único para referência cruzada"
* diagnosis.extension ^short = "Extensões adicionais que não fazem parte do modelo de dados básico"
* diagnosis.extension ^definition = "Extensões adicionais que não fazem parte do modelo de dados básico"
* diagnosis.modifierExtension ^short = "Extensões adicionais que não podem ser ignoradas, mesmo que não reconhecidas"
* diagnosis.modifierExtension ^definition = "Extensões adicionais que não podem ser ignoradas, mesmo que não reconhecidas"
* diagnosis.condition ^short = "O diagnóstico ou procedimento relevante para este atendimento"
* diagnosis.condition ^definition = "O diagnóstico ou procedimento relevante para este atendimento"
* diagnosis.condition only Reference(br-core-condition or br-core-procedure)
* diagnosis.use ^short = "Papel deste diagnóstico no atendimento (por exemplo, internação, faturamento, alta…)"
* diagnosis.use ^definition = "Papel deste diagnóstico no atendimento (por exemplo, internação, faturamento, alta…)"
* diagnosis.use 1..1
* diagnosis.use from http://hl7.org/fhir/ValueSet/diagnosis-role
* diagnosis.rank ^short = "Classificação do diagnóstico"
* diagnosis.rank ^definition = "Classificação do diagnóstico"
* account ^short = "Referências as contas desde atendimento"
* account ^definition = "Referências as contas desde atendimento"
* hospitalization ^short = "Detalhes sobre a internação em um serviço de saúde"
* hospitalization ^definition = "Detalhes sobre a internação em um serviço de saúde"
* hospitalization.id ^short = "Identificador único para referência cruzada"
* hospitalization.id ^definition = "Identificador único para referência cruzada"
* hospitalization.extension ^short = "Extensões adicionais que não fazem parte do modelo de dados básico"
* hospitalization.extension ^definition = "Extensões adicionais que não fazem parte do modelo de dados básico"
* hospitalization.modifierExtension ^short = "Extensões adicionais que não podem ser ignoradas, mesmo que não reconhecidas"
* hospitalization.modifierExtension ^definition = "Extensões adicionais que não podem ser ignoradas, mesmo que não reconhecidas"
* hospitalization.preAdmissionIdentifier ^short = "Identificador de pré-internação"
* hospitalization.preAdmissionIdentifier ^definition = "Identificador de pré-internação"
* hospitalization.origin ^short = "Referência ao local/organização de onde o paciente veio antes da internação"
* hospitalization.origin ^definition = "Referência ao local/organização de onde o paciente veio antes da internação"
* hospitalization.origin only Reference(br-core-location or br-core-organization)
* hospitalization.admitSource ^short = "De onde o paciente foi admitido (encaminhamento médico, transferência)"
* hospitalization.admitSource ^definition = "De onde o paciente foi admitido (encaminhamento médico, transferência)"
* hospitalization.admitSource 1..1
* hospitalization.admitSource from https://terminologia.saude.gov.br/fhir/ValueSet/BRProcedencia
* hospitalization.reAdmission ^short = "O tipo de readmissão hospitalar  (se houver). Se o valor estiver ausente, a internação não será dentificada como uma reinternação"
* hospitalization.reAdmission ^definition = "O tipo de readmissão hospitalar  (se houver). Se o valor estiver ausente, a internação não será dentificada como uma reinternação"
* hospitalization.dietPreference ^short = "Preferências alimentares do paciente"
* hospitalization.dietPreference ^definition = "Preferências alimentares do paciente"
* hospitalization.specialCourtesy ^short = "Cortesias especiais (VIP, membro do conselho)"
* hospitalization.specialCourtesy ^definition = "Cortesias especiais (VIP, membro do conselho)"
* hospitalization.specialArrangement ^short = "Necessidades especiais: cadeira de rodas, tradutor, maca, etc"
* hospitalization.specialArrangement ^definition = "Necessidades especiais: cadeira de rodas, tradutor, maca, etc"
* hospitalization.destination ^short = "Referência ao local/organização de encaminhamento pós-alta"
* hospitalization.destination ^definition = "Referência ao local/organização de encaminhamento pós-alta"
* hospitalization.destination only Reference(br-core-location or br-core-organization)
* hospitalization.dischargeDisposition ^short = "Categoria ou tipo de local após a alta"
* hospitalization.dischargeDisposition ^definition = "Categoria ou tipo de local após a alta"
* hospitalization.dischargeDisposition from https://terminologia.saude.gov.br/fhir/CodeSystem/BRMotivoDesfecho
* hospitalization.dischargeDisposition 1..1
* location ^short = "Lista de locais onde o paciente esteve"
* location ^definition = "Lista de locais onde o paciente esteve"
* location.id ^short = "Identificador único para referência cruzada"
* location.id ^definition = "Identificador único para referência cruzada"
* location.extension ^short = "Extensões adicionais que não fazem parte do modelo de dados básico"
* location.extension ^definition = "Extensões adicionais que não fazem parte do modelo de dados básico"
* location.modifierExtension ^short = "Extensões adicionais que não podem ser ignoradas, mesmo que não reconhecidas"
* location.modifierExtension ^definition = "Extensões adicionais que não podem ser ignoradas, mesmo que não reconhecidas"
* location.location ^short = "Local onde o atendimento acontece"
* location.location ^definition = "Local onde o atendimento acontece"
* location.location only Reference(br-core-location)
* location.status ^short = "O status do local: planned | active | reserved | completed"
* location.status ^definition = "O status do local: planned | active | reserved | completed"
* location.status from http://hl7.org/fhir/ValueSet/encounter-location-status
* location.physicalType ^short = "O tipo físico do local (geralmente o nível na hierarquia do local - quarto, enfermaria, etc.)"
* location.physicalType ^definition = "O tipo físico do local (geralmente o nível na hierarquia do local - quarto, enfermaria, etc.)"
* location.physicalType from http://hl7.org/fhir/ValueSet/location-physical-type
* location.period ^short = "Período de tempo durante o qual o paciente esteve presente no local"
* location.period ^definition = "Período de tempo durante o qual o paciente esteve presente no local"
* serviceProvider ^short = "A organização (instalação) responsável por este encontro"
* serviceProvider ^definition = "A organização (instalação) responsável por este encontro"
* serviceProvider only Reference(br-core-organization)
* serviceProvider 1..1
* partOf ^short = "Outro atendimento do qual este atendimento faz parte"
* partOf ^definition = "Outro atendimento do qual este atendimento faz parte"
* partOf only Reference(br-core-encounter)