Profile: BRCoreComposition
Parent: http://hl7.org/fhir/StructureDefinition/Composition
Id: br-core-composition
Title: "br-core-composition"
Description: "Um conjunto de informações relacionadas aos cuidados em sáude que são reunidas em um único bundle lógico que estabelece seu próprio contexto e atesta quem está fazendo a declaração. Uma Composição define a estrutura e o conteúdo narrativo necessários para um documento. No entanto, uma Composição sozinha não constitui um documento. Em vez disso, a Composição deve ser a primeira entrada em um Bundle onde Bundle.type=document, e quaisquer outros recursos referenciados da Composição devem ser incluídos como entradas subsequentes no Bundle (por exemplo, Patient, Practitioner, Encounter, etc.)."

* id ^short = "ID lógico deste artefato"
* id ^definition = "ID lógico deste artefato"
* meta ^short = "ID lógico deste artefato"
* meta ^definition = "ID lógico deste artefato"
* implicitRules ^short = "Conjunto de regras utilizadas para a elaboração deste conteúdo"
* implicitRules ^definition = "Conjunto de regras utilizadas para a elaboração deste conteúdo"
* language ^short = "Idioma do conteúdo do recurso"
* language ^definition = "Idioma do conteúdo do recurso"
* text ^short = "Resumo do recurso para interpretação humana"
* text ^definition = "Resumo do recurso para interpretação humana"
* contained ^short = "Recursos contidos"
* contained ^definition = "Recursos contidos neste artefato"
* modifierExtension ^short = "Extensões que não podem ser ignoradas"
* modifierExtension ^definition = "Extensões que não podem ser ignoradas"
* identifier ^short = "Identificador independente da versão da Composition"
* identifier ^definition = "Identificador independente da versão da Composition"
* status ^short = "Status/Situação da Composition"
* status ^definition = "Status/Situação da Composition: preliminar, definitivo, alterado, inserido com erro"
* status from http://hl7.org/fhir/ValueSet/composition-status (required)
* type ^short = "Tipo da Composition"
* type ^definition = "Tipo da Composition (fixo em 'Sumário Internacional do Paciente)"
* type from http://hl7.org/fhir/ValueSet/doc-typecodes (preferred)
* type.id ^short = "ID exclusivo para referência entre elementos"
* type.id ^definition = "ID exclusivo para referência entre elementos"
* type.extension ^short = "Conteúdo adicional definido por implementações"
* type.extension ^definition = "Conteúdo adicional definido por implementações"
* type.coding ^short = "Código definido por uma terminologia"
* type.coding ^definition = "Código definido por uma terminologia"
* type.coding.id ^short = "ID exclusivo para referência entre elementos"
* type.coding.id ^definition = "ID exclusivo para referência entre elementos"
* type.coding.extension ^short = "Conteúdo adicional definido por implementações"
* type.coding.extension ^definition = "Conteúdo adicional definido por implementações"
* type.coding.system ^short = "Identificador do sistema de terminologia"
* type.coding.system ^definition = "Identidficador do sistema de terminologia."
* type.coding.version ^short = "Versão da terminologia LOINC"
* type.coding.version ^definition = "Versão da terminologia LOINC - se relevante"
* type.coding.code ^short = "Código conforme terminologia"
* type.coding.code ^definition = "Código conforme terminologia."
* type.coding.display ^short = "Descrição conforme definição da terminologia LOINC"
* type.coding.display ^definition = "Descrição conforme definição da terminologia LOINC"
* type.coding.userSelected ^short = "Se esta codificação foi escolhida diretamente pelo usuário"
* type.coding.userSelected ^definition = "Se esta codificação foi escolhida diretamente pelo usuário"
* subject ^definition = "Sobre quem e/ou sobre o que é a composição"
* type.text ^short = "Representação em texto livre do conceito"
* type.text ^definition = "Representação em texto livre do conceito"
* category ^short = "Categorização da Composition"
* category ^definition = "Categorização da Composition"
* category from http://hl7.org/fhir/ValueSet/document-classcodes (example)
* subject ^short = "Sobre quem e/ou sobre o que é a Composition"
* subject ^definition = "Sobre quem e/ou sobre o que é a Composition"
* subject.id ^short = "ID exclusivo para referência entre elementos"
* subject.id ^definition = "ID exclusivo para referência entre elementos"
* subject.extension ^short = "Conteúdo adicional definido por implementações"
* subject.extension ^definition = "Conteúdo adicional definido por implementações"
* subject.reference ^short = "Referência literal, URL relativa, interna ou absoluta"
* subject.reference ^definition = "Referência literal, URL relativa, interna ou absoluta"
* subject.type ^short = "Tipo ao qual a referência se refere"
* subject.type ^definition = "Tipo ao qual a referência se refere (por exemplo,'Paciente')"
* subject.identifier ^short = "Referência lógica, quando a referência literal não é conhecida"
* subject.identifier ^definition = "Referência lógica, quando a referência literal não é conhecida"
* subject.display ^short = "Texto alternativo para o recurso"
* subject.display ^definition = "Texto alternativo para o recurso"
* subject only Reference(br-core-patient)
* encounter ^short = "Contato assistencial descrito nesta Composition"
* encounter ^definition = "Contato assistencial descrito nesta Composition"
* encounter only Reference(br-core-encounter)
* date ^short = "Data de edição da Composition"
* date ^definition = "Data de edição da Composition"
* author ^short = "Quem e/ou o que foi o autor desta Composition"
* author ^definition = "Quem e/ou o que foi o autor desta Compositon"
* author only Reference(br-core-practitioner or br-core-practitionerrole or Device or br-core-patient or br-core-relatedperson or br-core-organization)
* title ^short = "Sumário Internacional do Paciente"
* title ^definition = "Sumário Internacional do Paciente"
* confidentiality ^short = "Códigos que especificam o nível de confidencialidade da Composition"
* confidentiality ^definition = "Códigos que especificam o nível de confidencialidade da Composition"
* confidentiality from http://terminology.hl7.org/ValueSet/v3-ConfidentialityClassification (required)
* attester ^short = "Responsável por atestar a acurácia da Composition"
* attester ^definition = "Responsável por atestar a acurácia da Composition"
* attester.id ^short = "ID exclusivo para referência entre elementos"
* attester.id ^definition = "ID exclusivo para referência entre elementos"
* attester.extension ^short = "Conteúdo adicional definido por implementações"
* attester.extension ^definition = "Conteúdo adicional definido por implementações"
* attester.modifierExtension ^short = "Extensões que não podem ser ignoradas mesmo que não sejam reconhecidas"
* attester.modifierExtension ^definition = "Extensões que não podem ser ignoradas mesmo que não sejam reconhecidas"
* attester.mode ^short = "Métodolo utilizada para autenticar a Composition"
* attester.mode ^definition = "Métodolo utilizada para autenticar a Composition: pessoal, profissional, legal, oficial"
* attester.mode  from http://hl7.org/fhir/ValueSet/composition-attestation-mode (required)
* attester.time ^short = "Quando a Composition foi atestada"
* attester.time ^definition = "Quando a Composition foi atestada"
* attester.party ^short = "Quem atestou a Composition"
* attester.party ^definition = "Quem atestou a Composition"
* attester.party only Reference( br-core-patient or br-core-relatedperson or br-core-practitioner or br-core-practitionerrole or br-core-organization)
* custodian ^short = "Organização responsável pela custódia da Composition"
* custodian ^definition = "Identifica a organização ou grupo responsável pela composição."
* custodian only Reference(br-core-organization)
* relatesTo ^short = "Relacionamentos com outras Compositions/Documents"
* relatesTo ^definition = "Relações que esta composição tem com outras composições ou recursos."
* relatesTo.id ^short = "Relacionamentos com outras composições/Documents"
* relatesTo.id ^definition = "Relacionamentos com outras composições/Documents"
* relatesTo.extension ^short = "Conteúdo adicional definido por implementações"
* relatesTo.extension ^definition = "Conteúdo adicional definido por implementações"
* relatesTo.modifierExtension ^short = "Extensões que não podem ser ignoradas mesmo que não sejam reconhecidas"
* relatesTo.modifierExtension ^definition = "Extensões que não podem ser ignoradas mesmo que não sejam reconhecidas"
* relatesTo.code ^short = "Alvo do relacionamento da composição"
* relatesTo.code ^definition = "Alvo do relacionamento da composição"
* relatesTo.code from http://hl7.org/fhir/ValueSet/document-relationship-type (required)
* relatesTo.target[x] ^short = "Relacionamento alvo"
* relatesTo.target[x] ^definition = "Relacionamento alvo"
* relatesTo.targetReference ^short = "Referencia a composition alvo"
* relatesTo.targetReference ^definition = "Referencia a composition alvo"
* relatesTo.targetReference only Reference(br-core-composition)
* event ^short = "Serviços assistenciais documentados"
* event ^definition = "O serviço especializado  como uma colonoscopia ou uma apendicectomia, sendo documentado." 
* event.id ^short = "ID exclusivo para referência entre elementos"
* event.id ^definition = "Identificador  único para o elemento dentro de um recurso (para referências internas). Este pode ser qualquer valor de string que não contenha espaços."
* event.extension ^short = "Conteúdo adicional definido por implementações"
* event.extension ^definition = "Conteúdo adicional definido por implementações"
* event.modifierExtension ^short = "Extensões que não podem ser ignoradas mesmo que não sejam reconhecidas"
* event.modifierExtension ^definition = "Extensões que não podem ser ignoradas mesmo que não sejam reconhecidas"
* event.code ^short = "Código(s) aplicável(is) aos eventos documentados"
* event.code ^definition = "Esta lista de códigos representa os principais atos clínicos, como uma colonoscopia ou uma apendicectomia, sendo documentados. Em alguns casos, o evento é inerente ao typeCode, como um 'Histórico e Relatório Físico', no qual o procedimento documentado é necessariamente um ato de 'Histórico e Físico'."
* event.code from http://terminology.hl7.org/ValueSet/v3-ActCode (required)
* event.period ^short = "O período de tempo coberto pela composition."
* event.period ^definition = "O período de tempo coberto pela composition. Não há declaração de que a documentação seja uma representação completa para este período, apenas que documenta eventos durante esse tempo."
* event.detail ^short = "Referência aos eventos da Composition"
* event.detail ^definition = "Referência aos eventos da Composition"
* event.detail only Reference(Resource)
* section ^short = "A secção inicial da composition a partir da qual as demais seções são definidas"
* section ^definition = "A secção inicial da composition a partir da qual as demais seções são definidas"
* section.id ^short = "Identificador exclusivo para referência entre elemento"
* section.id ^definition = "Identificador exclusivo para referência entre elementos"
* section.extension ^short = "Conteúdo adicional definido por implementações"
* section.extension ^definition = "Conteúdo adicional definido por implementações"
* section.modifierExtension ^short = "Extensões que não podem ser ignoradas mesmo que não sejam reconhecidas"
* section.modifierExtension ^definition = "Extensões que não podem ser ignoradas mesmo que não sejam reconhecidas"
* section.title ^short = "Título da seção"
* section.title ^definition = "Título da seção do Sumário Internacional do Paciente"
* section.code ^short = "Um código que identifica o tipo de conteúdo contido dentro da seção."
* section.code ^definition = "Um código que identifica o tipo de conteúdo contido dentro da seção. Isso deve ser consistente com o título da seção."
* section.code from 	http://hl7.org/fhir/ValueSet/doc-section-codes (required)
* section.author ^short = "Quem e/ou o que foi o autor desta seção"
* section.author ^definition = " Identifica quem é responsável pelas informações nesta seção, não necessariamente quem a digitou."
* section.author only Reference(br-core-practitioner or br-core-practitionerrole or Device or br-core-patient or br-core-relatedperson or br-core-organization)
* section.focus ^short = "Quem/o que é a seção"
* section.focus ^definition = "Quem/o que é a seção"
* section.text ^short = "Resumo em texto livre da seção"
* section.text ^definition = "Resumo em texto livre da seção"
* section.mode ^short = "Método de processamento da seção"
* section.mode ^definition = "Método de processamento da seção"
* section.mode from http://hl7.org/fhir/ValueSet/list-mode (required)
* section.orderedBy ^short = "Especifica a ordem dos itens nas sections.entry"
* section.orderedBy ^definition = "Especifica a ordem dos itens nas sections.entry"
* section.orderedBy from http://hl7.org/fhir/ValueSet/list-order (preferred)
* section.entry ^short = "Uma referência ao recurso a partir  do qual narrativa da seção é derivada."
* section.entry ^definition = "Uma referência ao recurso a partir  do qual narrativa da seção é derivada."
* section.emptyReason ^short = "Explicação porquê a secção está vazia"
* section.emptyReason ^definition = "Explicação porquê a secção está vazia"
* section.orderedBy from http://hl7.org/fhir/ValueSet/list-empty-reason (preferred)
* section.section ^short = "Uma subseção aninhada dentro desta seção"
* section.section ^definition = "Uma subseção aninhada dentro desta seção"
