Profile: br-core-specimen
Parent: http://hl7.org/fhir/StructureDefinition/Specimen
Id: br-core-specimen
Description: "Este perfil representa uma amostra."

* id ^short = "ID lógico deste artefato"
* id ^definition = "ID lógico deste artefato"
* meta ^short = "Metadados sobre o recurso"
* meta ^definition = "Metadados sobre o recurso"
* implicitRules ^short = "Um conjunto de regras sob as quais este conteúdo foi criado"
* implicitRules ^definition = "Um conjunto de regras sob as quais este conteúdo foi criado"
* language ^short = "Idioma do conteúdo do recurso"
* language ^definition = "Idioma do conteúdo do recurso"
* text ^short = "Resumo do texto do recurso, para interpretação humana"
* text ^definition = "Resumo do texto do recurso, para interpretação humana"
* contained ^short = "Recursos contidos"
* contained ^definition = "Recursos contidos"
* extension ^short = "Conteúdo adicional definido por implementações"
* extension ^definition = "Conteúdo adicional definido por implementações"
* modifierExtension ^short = "Extensões que não podem ser ignoradas"
* modifierExtension ^definition = "Extensões que não podem ser ignoradas"
* identifier ^short = "Identificador Externo"
* identifier ^definition = "Identificador Externo"
* accessionIdentifier ^short = "Identificador atribuído pelo laboratório"
* accessionIdentifier ^definition = "Identificador atribuído pelo laboratório"
* status ^short = "disponível | indisponível | insatisfatório | inserido com erro: códigos que fornecem o status/disponibilidade de uma amostra."
* status ^definition = "disponível | indisponível | insatisfatório | inserido com erro: códigos que fornecem o status/disponibilidade de uma amostra"
* type ^short = "Tipo de material que compõem a amostra"
* type ^definition = "Tipo de material que compõem a amostra"
* type from https://terminologia.saude.gov.br/fhir/ValueSet/BRTipoAmostra
* subject ^short = "Referência de onde veio a amostra. Pode ser de paciente(s), de um local (por exemplo, a fonte de uma amostra ambiental) ou uma amostra de uma substância ou dispositivo"
* subject ^definition = "Referência de onde veio a amostra. Pode ser de paciente(s), de um local (por exemplo, a fonte de uma amostra ambiental) ou uma amostra de uma substância ou dispositivo"
* subject only Reference(br-core-patient or Group or Device or Substance or br-core-location)
* subject.id ^short = "ID exclusivo para referência entre elementos"
* subject.id ^definition = "ID exclusivo para referência entre elementos"
* subject.extension ^short = "Conteúdo adicional definido por implementações"
* subject.extension ^definition = "Conteúdo adicional definido por implementações"
* subject.reference ^short = "Referência literal, URL relativa, interna ou absoluta"
* subject.reference ^definition = "Referência literal, URL relativa, interna ou absoluta"
* subject.type ^short = "Tipo ao qual a referência se refere (por exemplo, Paciente)"
* subject.type ^definition = "Tipo ao qual a referência se refere (por exemplo, Paciente)"
* subject.identifier ^short = "Referência lógica, quando a referência literal não é conhecida"
* subject.identifier ^definition = "Referência lógica, quando a referência literal não é conhecida"
* subject.display ^short = "Texto alternativo para o recurso"
* subject.display ^definition = "Texto alternativo para o recurso"
* receivedTime ^short = "Data/hora em que a amostra foi recebida para processamento"
* receivedTime ^definition = "Data/hora em que a amostra foi recebida para processamento"
* parent ^short = "Origem da amostra"
* parent ^definition = "Origem da amostra"
* parent only Reference(br-core-specimen)
* request ^short = "Por que a amostra foi coletada"
* request ^definition = "Por que a amostra foi coletada"
* request only Reference(br-core-servicerequest)
* collection ^short = "Detalhes da coleta"
* collection ^definition = "Detalhes da coleta"
* collection.id ^short = "ID exclusivo para referência entre elementos"
* collection.id ^definition = "ID exclusivo para referência entre elementos"
* collection.extension ^short = "Conteúdo adicional definido por implementações"
* collection.extension ^definition = "Conteúdo adicional definido por implementações"
* collection.modifierExtension ^short = "Extensões que não podem ser ignoradas mesmo que não sejam reconhecidas"
* collection.modifierExtension ^definition = "Extensões que não podem ser ignoradas mesmo que não sejam reconhecidas"
* collection.collector ^short = "Profissional resopnsável pela coleta"
* collection.collector ^definition = "Profissional resopnsável pela coleta"
//* collection.collector only Reference(br-core-practitioner or br-core-practitionerrole)
* collection.collected[x] ^short = "Data/Hora-Período da coleta"
* collection.collected[x] ^definition = "Data/Hora-Período da coleta"
* collection.duration ^short = "Duração da coleta"
* collection.duration ^definition = "Duracao da coleta"
* collection.quantity ^short = "Quantidade de amostra coletada"
* collection.quantity ^definition = "Quantidade de amostra coletada"
* collection.method ^short = "Método de coleta da amostra"
* collection.method ^definition = "Método de coleta da amostra"
* collection.bodySite ^short = "Local anatômico de coleta da amostra"
* collection.bodySite ^definition = "Local anatômico de coleta da amostra"
* collection.fastingStatus[x] ^short = "Tempo de jejum do paciente, se for o caso"
* collection.fastingStatus[x] ^definition = "Tempo de jejum do paciente, se for o caso"
* processing ^short = "Detalhes da etapa de processamento da amostra e respectivos passos"
* processing ^definition = "Detalhes da etapa de processamento da amostra e respectivos passos"
* processing.id ^short = "ID exclusivo para referência entre elementos"
* processing.id ^definition = "ID exclusivo para referência entre elementos"
* processing.extension ^short = "Conteúdo adicional definido por implementações"
* processing.extension ^definition = "Conteúdo adicional definido por implementações"
* processing.modifierExtension ^short = "Extensões que não podem ser ignoradas mesmo que não sejam reconhecidas"
* processing.modifierExtension ^definition = "Extensões que não podem ser ignoradas mesmo que não sejam reconhecidas"
* processing.description ^short = "Texto que descreve o procedimento"
* processing.description ^definition = "Texto que descreve o procedimento"
* processing.procedure ^short = "Indica a etapa de tratamento aplicada a amostra"
* processing.procedure ^definition = "Indica a etapa de tratamento aplicada a amostra"
* processing.additive ^short = "Material utilizado na etapa de processamento da amostra"
* processing.additive ^definition = "Material utilizado na etapa de processamento da amostra"
* processing.additive only Reference(Substance)
* processing.time[x] ^short = "Data e hora do processamento da amostra"
* processing.time[x] ^definition = "Data e hora do processamento da amostra"
* container ^short = "Recipiente que contém a amostra (tubo/lâmina, etc.)"
* container ^definition = "Recipiente que contém a amostra (tubo/lâmina, etc.)"
* container.id ^short = "ID exclusivo para referência entre elementos"
* container.id ^definition = "ID exclusivo para referência entre elementos"
* container.extension ^short = "Conteúdo adicional definido por implementações"
* container.extension ^definition = "Conteúdo adicional definido por implementações"
* container.modifierExtension ^short = "Extensões que não podem ser ignoradas mesmo que não sejam reconhecidas"
* container.modifierExtension ^definition = "Extensões que não podem ser ignoradas mesmo que não sejam reconhecidas"
* container.identifier ^short = "Id do recipiente"
* container.identifier ^definition = "Id do recipiente que contém a amostra"
* container.description ^short = "Descrição do recipiente"
* container.description ^definition = "Descrição do recipiente que contém a amostra"
* container.type ^short = "Tipo de recipiente associado a amostra"
* container.type ^definition = "Tipo de recipiente associado a amostra"
* container.capacity ^short = "Volume ou tamanho do recipiente"
* container.capacity ^definition = "Volume ou tamanho do recipiente"
* container.specimenQuantity ^short = "Quantidade de amostra no recipiente"
* container.specimenQuantity ^definition = "Quantidade de amostra no recipiente"
* container.additive[x] ^short = "Aditivo associado ao recipiente"
* container.additive[x] ^definition = "Aditivo associado ao recipiente"
* condition ^short = "Estado da amostra"
* condition ^definition = "Estado da amostra"
* note ^short = "Comentários"
* note ^definition = "Comentários sobre a Amostra"