Profile: br-core-vitalsigns
Parent: http://hl7.org/fhir/StructureDefinition/vitalsigns
Id: br-core-vitalsigns
Description: "Este perfil representa uma sinal vital."

//* effective[x].id.extension only Reference(br-core-practitioner or br-core-practitionerrole or br-core-organization or br-core-patient or br-core-relatedperson or Device or CareTeam)
* id ^short = "Identificador lógico deste artefato"
* id ^definition = "Identificador lógico deste artefato"
* meta ^short = "Metadados sobre o recurso"
* meta ^definition = "Metadados sobre o recurso"
* implicitRules ^short = "URI(s) sob as quais este recurso é conhecido"
* implicitRules ^definition = "Um ou mais códigos que servem para identificar o tipo de recurso"
* language ^short = "Linguagem do recurso"
* language ^definition = "A linguagem humana natural do recurso"
* text ^short = "Texto narrativo, 72 caracteres para resumo"
* text ^definition = "Um texto narrativo resumindo as informações do recurso"
* contained ^short = "Recursos contidos"
* contained ^definition = "Recursos contidos no recurso"
* extension ^short = "Extensões adicionais"
* extension ^definition = "Extensões adicionais que não fazem parte do modelo base"
* modifierExtension ^short = "Extensões adicionais que não podem ser ignoradas"
* modifierExtension ^definition = "Extensões adicionais que não podem ser ignoradas, mesmo que não reconhecidas"
* identifier ^short = "Identificadores externos para este recurso"
* identifier ^definition = "Identificadores externos para este recurso"
* basedOn ^short = "Referência ao pedido ou ao plano de tratamento que gerou este recurso"
* basedOn ^definition = "Referência ao pedido ou ao plano de tratamento que gerou este recurso"
* basedOn only Reference(br-core-careplan or DeviceRequest or ImmunizationRecommendation or br-core-medicationrequest or NutritionOrder or br-core-servicerequest) 
* partOf ^short = "Referência ao evento do qual este recurso faz parte"
* partOf ^definition = "Referência ao evento do qual este recurso faz parte"
//* partOf only Reference(br-core-medicationadministration or br-core-medicationdispense or br-core-medicationstatement or br-core-procedure or br-core-immunization or ImagingStudy)
* status ^short = "Status atual da observação"
* status ^definition = "active | completed | entered-in-error | intended | stopped | on-hold | unknown | not-taken"
* category ^short = "Categoria de alto nível da observação"
* category ^definition = "Categoria de alto nível da observação"
* category[VSCat] ^short = "Classificação do tipo de observação"
* category[VSCat] ^definition = "Classificação do tipo de observação"
* category[VSCat].id ^short = "Identificador exclusivo para referência entre elementos"
* category[VSCat].id ^definition = "Identificador exclusivo para referência entre elementos"
* category[VSCat].extension ^short = "Conteúdo adicional definido por implementações"
* category[VSCat].extension ^definition = "Conteúdo adicional definido por implementações"
* category[VSCat].coding ^short = "Código definido por uma terminologia"
* category[VSCat].coding ^definition = "Código definido por uma terminologia"
* category[VSCat].coding.id ^short = "Identificador exclusivo para referência entre elementos"
* category[VSCat].coding.id ^definition = "Identificador exclusivo para referência entre elementos"
* category[VSCat].coding.extension ^short = "Conteúdo adicional definido por implementações"
* category[VSCat].coding.extension ^definition = "Conteúdo adicional definido por implementações"
* category[VSCat].coding.system ^short = "Identidade do sistema de terminologia"
* category[VSCat].coding.system ^definition = "Identidade do sistema de terminologia"
* category[VSCat].coding.version ^short = "Versão do sistema, se relevante"
* category[VSCat].coding.version ^definition = "Versão do sistema, se relevante"
* category[VSCat].coding.code ^short = "Símbolo na sintaxe definida pelo sistema"
* category[VSCat].coding.code ^definition = "Símbolo na sintaxe definida pelo sistema"
* category[VSCat].coding.display ^short = "Representação definida pelo sistema"
* category[VSCat].coding.display ^definition = "Representação definida pelo sistema"
* category[VSCat].coding.userSelected ^short = "Se a codificação foi escolhida diretamente pelo usuário"
* category[VSCat].coding.userSelected ^definition = "Se a codificação foi escolhida diretamente pelo usuário"
* category[VSCat].text ^short = "Representação em texto simples do conceito"
* category[VSCat].text ^definition = "Representação em texto simples do conceito"
* code ^short = "Códigos dos resultados de sinais vitais do C-CDA"
* code ^definition = "Códigos dos resultados de sinais vitais do C-CDA"
* subject ^short = "De quem ou do que trata a observação"
* subject ^definition = "De quem ou do que trata a observação"
* subject only Reference(br-core-patient)
* focus ^short = "Sobre o que é a observação, quando não é sobre o subject do registro"
* focus ^definition = "Sobre o que é a observação, quando não é sobre o subject do registro"
* focus only Reference(Resource)
* encounter ^short = "Atendimento no qual a observação foi feita"
* encounter ^definition = "Atendimento no qual a observação foi feita"
* encounter only Reference(br-core-encounter)
* effective[x] ^short = "Tempo ou período de tempo clinicamente relevante para os sinais vitais"
* effective[x] ^definition = "Tempo ou período de tempo clinicamente relevante para os sinais vitais"
* issued ^short = "Data ou hora em que esta versão da observação ficou disponível"
* issued ^definition = "Data ou hora em que esta versão da observação ficou disponível"
* issued 1..1
* performer ^short = "O responsável pela observação"
* performer ^definition = "O responsável pela observação"
//* performer only Reference(br-core-practitioner or br-core-practitionerrole or br-core-organization or CareTeam or br-core-patient or br-core-relatedperson)
* value[x] ^short = "O resultado do exame em si"
* value[x] ^definition = "O resultado do exame em si"
* value[x] 1..1
* dataAbsentReason ^short = "Por que o resultado não está disponível"
* dataAbsentReason ^definition = "Por que o resultado não está disponível"
* interpretation ^short = "Interpretação da observação"
* interpretation ^definition = "Interpretação da observação. Por exemplo: valor alto, baixo, normal"
* note ^short = "Comentários sobre a observação"
* note ^definition = "Comentários sobre a observação"
* bodySite ^short = "Parte do corpo examinada"
* bodySite ^definition = "Parte do corpo examinada"
* method ^short = "Método usado para examinar"
* method ^definition = "Método usado para examinar"
* specimen ^short = "Amostra examinada na observação"
* specimen ^definition = "Amostra examinada na observação"
//* specimen only Reference(SpecimenBRIPS)
* device ^short = "Dispositivo (de medida)"
* device ^definition = "Dispositivo (de medida)"
* device only Reference(Device or DeviceMetric)
* referenceRange ^short = "Fornece um guia para interpretação"
* referenceRange ^definition = "Fornece um guia para interpretação"
* referenceRange.id ^short = "Identificador único para referenciação cruzada"
* referenceRange.id ^definition = "Identificador único para referenciação cruzada"
* referenceRange.extension ^short = "Extensões adicionais que não fazem parte do modelo de dados básico"
* referenceRange.extension ^definition = "Extensões adicionais que não fazem parte do modelo de dados básico" 
* referenceRange.modifierExtension ^short = "Extensões adicionais que não podem ser ignoradas, mesmo que não reconhecidas"
* referenceRange.modifierExtension ^definition = "Extensões adicionais que não podem ser ignoradas, mesmo que não reconhecidas"
* referenceRange.low ^short = "Limite inferior do intervalo"
* referenceRange.low ^definition = "Limite inferior do intervalo de valores de referência"
* referenceRange.high ^short = "Limite superior do intervalo"
* referenceRange.high ^definition = "Limite superior do intervalo de valores de referência"
* referenceRange.type ^short = "Qualificador do valor de referência"
* referenceRange.type ^definition = "Qualificador do valor de referência"
* referenceRange.appliesTo ^short = "População do intervalo de referência"
* referenceRange.appliesTo ^definition = "População do intervalo de referência"
* referenceRange.age ^short = "Faixa etária aplicável"
* referenceRange.age ^definition = "Faixa etária aplicável, se relevante"
* referenceRange.text ^short = "Intervalo de referência em formato textual"
* referenceRange.text ^definition = "Intervalo de referência em formato textual"
* hasMember ^short = "Recurso relacionado que pertence ao grupo da Observação"
* hasMember ^definition = "Recurso relacionado que pertence ao grupo da Observação"
* hasMember only Reference(QuestionnaireResponse or MolecularSequence)
* derivedFrom ^short = "Medições relacionadas a partir das quais a observação é feita"
* derivedFrom ^definition = "Medições relacionadas a partir das quais a observação é feita"
//* derivedFrom only Reference(DocumentReference or br-core-imagingstudy or Media or QuestionnaireResponse or br-core-observation or MolecularSequence)
* component ^short = "Resultados do componente"
* component ^definition = "Resultados do componente"
* component.id ^short = "Identificador único para referenciação cruzada"
* component.id ^definition = "Identificador único para referenciação cruzada"
* component.extension ^short = "Extensões adicionais que não fazem parte do modelo de dados básico"
* component.extension ^definition = "Extensões adicionais que não fazem parte do modelo de dados básico" 
* component.modifierExtension ^short = "Extensões adicionais que não podem ser ignoradas, mesmo que não reconhecidas"
* component.modifierExtension ^definition = "Extensões adicionais que não podem ser ignoradas, mesmo que não reconhecidas"
* component.code ^short = "Tipo de observação de componente"
* component.code ^short = "Tipo de observação de componente"
* component.value[x] ^short = "O valor do resultado em si"
* component.dataAbsentReason ^short = "Por que o resultado do componente está faltando"
* component.dataAbsentReason ^definition = "Por que o resultado do componente está faltando"
* component.interpretation ^short = "Interpretação da observação"
* component.interpretation ^definition = "Interpretação da observação. Por exemplo: valor elevado"
* component.referenceRange ^short = "Valores de referência"
* component.referenceRange ^definition = "Valores de referência para auxiliar na interpretação do resultado"
//* display only Reference(br-core-encounter)