Profile: BRCoreLocation
Parent: http://hl7.org/fhir/StructureDefinition/Location
Id: br-core-location
Title: "br-core-location"
Description: "Este perfil restringe o recurso [Location](https://hl7.org/fhir/R4/location.html) que aborda detalhes e informações da posição de um local físico onde os serviços são fornecidos e os recursos e participantes podem ser armazenados, encontrados, contidos ou acomodados."

* identifier ^short = "Identificadores externos para este recurso"
* identifier ^definition = "Identificadores externos para este recurso"
* status ^short = "Indica se o local ainda está em uso."
* status ^definition = "active | suspended | inactive"
* status 1..1
* operationalStatus ^short = "O status operacional do local (normalmente apenas para uma cama/quarto)"
* operationalStatus ^definition = "O status operacional do local (normalmente apenas para uma cama/quarto)"
* name ^short = "Nome do local usado por humanos"
* name ^definition = "Nome do local usado por humanos"
* name 1..1
* alias ^short = "Uma lista de nomes alternativos pelos quais o local é conhecido, ou foi conhecido, no passado"
* alias ^definition = "Uma lista de nomes alternativos pelos quais o local é conhecido, ou foi conhecido, no passado"
* description ^short = "Detalhes adicionais sobre o local que podem ser exibidos como informações adicionais para identificar o local além do seu nome"
* description ^definition = "Detalhes adicionais sobre o local que podem ser exibidos como informações adicionais para identificar o local além do seu nome"
* mode ^short = "Indica se uma instância de recurso representa um local específico ou uma classe de locais."
* mode ^definition = "instance | kind"
* type ^short = "Tipo de função performada"
* type ^definition = "Tipo de função performada"
//* type from https://terminologia.saude.gov.br/fhir/ValueSet/BRServicosEspecializados
* telecom ^short = "Detalhes de contato do local"
* telecom ^definition = "Detalhes de contato do local"
* address ^short = "Endereço do local"
* address ^definition = "Endereço do local"
* physicalType ^short = "Forma física do local"
* physicalType ^definition = "Forma física do local"
//* physicalType from https://terminologia.saude.gov.br/fhir/ValueSet/BRInstalacoesFisicas
* position ^short = "A localização geográfica absoluta"
* position ^definition = "A localização geográfica absoluta"
* position.longitude ^short = "Longitude com referência WGS84"
* position.longitude ^definition = "Longitude com referência WGS84"
* position.latitude ^short = "Latitude com referência WGS84"
* position.latitude ^definition = "Latitude com referência WGS84"
* position.altitude ^short = "Altitude com referência WGS84"
* position.altitude ^definition = "Altitude com referência WGS84"
* managingOrganization ^short = "Organização responsável pelo provisionamento e manutenção"
* managingOrganization ^definition = "Organização responsável pelo provisionamento e manutenção"
* partOf ^short = "Outro local do qual este é fisicamente uma parte de"
* partOf ^short = "Outro local do qual este é fisicamente uma parte de"
* partOf only Reference(br-core-location)
* hoursOfOperation ^short = "Em que dias/horários da semana este local costuma ficar aberto?"
* hoursOfOperation ^definition = "Em que dias/horários da semana este local costuma ficar aberto?"
* hoursOfOperation.daysOfWeek ^short = "Dias da semana"
* hoursOfOperation.daysOfWeek ^definition = "mon | tue | wed | thu | fri | sat | sun"
* hoursOfOperation.allDay ^short = "Se o local está aberto o dia inteiro"
* hoursOfOperation.allDay ^definition = "Se o local está aberto o dia inteiro"
* hoursOfOperation.openingTime ^short = "Horário de abertura do local"
* hoursOfOperation.openingTime ^definition = "Horário de abertura do local"
* hoursOfOperation.closingTime ^short = "Horário de fechamento do local"
* hoursOfOperation.closingTime ^definition = "Horário de fechamento do local"
* availabilityExceptions ^short = "Descrição das exceções de disponibilidade"
* availabilityExceptions ^definition = "Descrição das exceções de disponibilidade"
* endpoint ^short = "Endpoints técnicos que fornecem acesso aos serviços operados para o local"
* endpoint ^definition = "Endpoints técnicos que fornecem acesso aos serviços operados para o local"