Profile: BRCoreCareTeam
Parent: http://hl7.org/fhir/StructureDefinition/CareTeam
Id: br-core-careteam
Title: "br-core-careteam"
Description: "Este perfil restringe o recurso [CareTeam](https://hl7.org/fhir/R4/careteam.html) que inclui todas as pessoas e organizações que planejam participar da coordenação e prestação de cuidados a um paciente"

* id ^short = "Identificador lógico deste artefato"
* id ^definition = "Identificador lógico deste artefato"
* meta ^short = "Metadados sobre o recurso"
* meta ^definition = "Metadados sobre o recurso" 
* implicitRules ^short = "Um conjunto de regras sob as quais este conteúdo foi criado"
* implicitRules ^definition = "Um conjunto de regras sob as quais este conteúdo foi criado"
* language ^short = "Idioma do recurso"
* language ^definition = "Idioma do recurso"
* text ^short = "Resumo do texto do recurso em linguagem natural"
* text ^definition = "Resumo do texto do recurso em linguagem natural"
* contained ^short = "Recursos contidos no recurso"
* contained ^definition = "Recursos contidos no recurso"
* extension ^short = "Extensões adicionais que não fazem parte do modelo base"
* extension ^definition = "Extensões adicionais que não fazem parte do modelo base"
* modifierExtension ^short = "Extensões adicionais que não podem ser ignoradas, mesmo que não reconhecidas"
* modifierExtension ^definition = "Extensões adicionais que não podem ser ignoradas, mesmo que não reconhecidas"
* identifier ^short = "Identificadores externos para este recurso"
* identifier ^definition = "Identificadores externos para este recurso"
* status ^short = "proposed | active | suspended | inactive | entered-in-error"
* status ^definition = "proposed | active | suspended | inactive | entered-in-error"
* category ^short = "Tipo da equipe assistêncial"
* category ^definition = "Tipo da equipe assistêncial"
* category from https://terminologia.saude.gov.br/fhir/ValueSet/BRModalidadeAssistencial
* name ^short = "Nome da equipe assistêncial"
* name ^definition = "Nome da equipe assistêncial"
* subject ^short = "Paciente referenciado pela equipe assistêncial"
* subject ^definition = "Paciente referenciado pela equipe assistêncial"
* subject only Reference(br-core-patient)
* encounter ^short = "Referência ao atendimento"
* encounter ^definition = "Referência ao atendimento"
* encounter only Reference(br-core-encounter)
* period ^short = "Período de atendimento pela a equipe assistêncial"
* period ^definition = "Período de atendimento pela a equipe assistêncial"
* participant ^short = "Lista de participantes envolvidos no atendimento"
* participant ^definition = "Lista de participantes envolvidos no atendimento"
* participant.id ^short = "Identificador único para referência cruzada"
* participant.id ^definition = "Identificador único para referência cruzada"
* participant.extension ^definition = "Extensões adicionais que não fazem parte do modelo de dados básico"
* participant.modifierExtension ^short = "Extensões adicionais que não podem ser ignoradas, mesmo que não reconhecidas"
* participant.modifierExtension ^definition = "Extensões adicionais que não podem ser ignoradas, mesmo que não reconhecidas"
* participant.role ^short = "Função do participante na equipe assistêncial"
* participant.role ^definition = "Função do participante na equipe assistêncial"
* participant.role from https://terminologia.saude.gov.br/fhir/ValueSet/BROcupacao (example)
* participant.member ^short = "Referência ao partipante"
* participant.member ^definition = "Referência ao partipante"
* participant.member only Reference(br-core-practitioner or br-core-practitionerrole or br-core-relatedperson or br-core-patient or br-core-organization or br-core-careteam)
* participant.onBehalfOf ^short = "Organização do participante"
* participant.onBehalfOf ^definition = "Organização do participante"
* participant.onBehalfOf only Reference(br-core-organization)
* participant.period ^short = "Período de tempo do participante atua no time assistêncial"
* participant.period ^definition = "Período de tempo do participante atua no time assistêncial"
* reasonCode ^short = "Motivo pelo qual a equipe assistência foi criada"
* reasonCode ^definition = "Motivo pelo qual a equipe assistência foi criada"
* reasonReference ^short = "Referência aos diagnóstico que esta equipe assistencial cobre"
* reasonReference ^definition = "Referência aos diagnóstico que esta equipe assistencial cobre"
* reasonReference only Reference(br-core-condition)
* managingOrganization ^short = "Organização da equipe assistêncial"
* managingOrganization ^definition = "Organização da equipe assistêncial"
* managingOrganization only Reference(br-core-organization)
* telecom ^short = "Contato da equipe assistencial"
* telecom ^definition = "Contato da equipe assistencial"
* note ^short = "Comentários adicionais sobre a equipe assistencial"
* note ^definition = "Comentários adicionais sobre a equipe assistencial"