Profile: BRCoreOrganization
Parent: http://hl7.org/fhir/StructureDefinition/Organization
Id: br-core-organization
Description: "Este perfil representa um agrupamento formal ou informal reconhecido de pessoas ou organizações com o propósito de alcançar alguma forma de ação coletiva. Inclui empresas, instituições, corporações, departamentos, grupos comunitários, grupos de práticas de saúde, planos de saúde, empresas fabricantes de produtos medicinais, entre outros"

* id ^short = "Identificador lógico deste artefato"
* id ^definition = "Identificador lógico deste artefato"
* meta ^short = "Metadados sobre o recurso"
* meta ^definition = "Metadados sobre o recurso" 
* implicitRules ^short = "Um conjunto de regras sob as quais este conteúdo foi criado"
* implicitRules ^definition = "Um conjunto de regras sob as quais este conteúdo foi criado"
* language ^short = "Idioma do recurso"
* language ^definition = "Idioma do recurso"
* text ^short = "Resumo do texto do recurso em linguagem natural"
* text ^definition = "Resumo do texto do recurso em linguagem natural"
* contained ^definition = "Recursos contidos no recurso"
* contained ^definition = "Recursos contidos no recurso"
* extension ^definition = "Extensões adicionais que não fazem parte do modelo base"
* extension ^definition = "Extensões adicionais que não fazem parte do modelo base"
* modifierExtension ^short = "Extensões adicionais que não podem ser ignoradas, mesmo que não reconhecidas"
* modifierExtension ^definition = "Extensões adicionais que não podem ser ignoradas, mesmo que não reconhecidas"
* identifier ^short = "Identificadores externos para este recurso"
* identifier ^definition = "Identificadores externos para este recurso"
* identifier ^slicing.discriminator.type = #value
* identifier ^slicing.discriminator.path = "system"
* identifier ^slicing.rules = #open
* identifier ^slicing.description = "Identificadores nacionais do estabelecimento"
* identifier 1..*
* identifier contains
    cnes 0..1 and
    cpf 0..1 and
    cnpj 0..1
* identifier[cnes] ^short = "Identificador do estabelecimento (CNES)"
* identifier[cnes] ^definition = "Identificador do estabelecimento"
* identifier[cnes].id ^short = "Id lógico do identificador do estabelecimento"
* identifier[cnes].id ^definition = "Id lógico do identificador do estabelecimento"
* identifier[cnes].extension ^short = "Extensões do identificador do estabelecimento"
* identifier[cnes].extension ^definition = "Extensões incluídas no identificador do estabelecimento"
* identifier[cnes].use ^short = "Uso do identificador do estabelecimento"
* identifier[cnes].use ^definition = "usual: identificador usual do estabelecimento. official: identificador oficial do estabelecimento. temp: identificador temporário do estabelecimento. secondary: identificador secundário do estabelecimento"
* identifier[cnes].use = http://hl7.org/fhir/identifier-use#official (exactly)
* identifier[cnes].type ^short = "Tipo do identificador do estabelecimento"
* identifier[cnes].type ^definition = "Código que representa o tipo do identificador do estabelecimento"
* identifier[cnes].type ^binding.description = "Tipo do identificador do estabelecimento"
* identifier[cnes].type ^binding.strength = #required
* identifier[cnes].type ^binding.valueSet = http://hl7.org/fhir/ValueSet/identifier-type
* identifier[cnes].type.id ^short = "Id lógico do tipo do identificador do estabelecimento"
* identifier[cnes].type.id ^definition = "Id lógico do tipo do identificador do estabelecimento"
* identifier[cnes].type.extension ^short = "Extensões do tipo do identificador do estabelecimento"
* identifier[cnes].type.extension ^definition = "Extensões incluídas no tipo do identificador do estabelecimento"
* identifier[cnes].type.coding 1..1
* identifier[cnes].type.coding ^short = "Codificação do tipo do identificador do estabelecimento"
* identifier[cnes].type.coding ^definition = "Codificação que representa o tipo do identificador do estabelecimento"
* identifier[cnes].type.coding.id ^short = "Id lógico da codificação do tipo do identificador do estabelecimento"
* identifier[cnes].type.coding.id ^definition = "Id lógico da codificação do tipo do identificador do estabelecimento"
* identifier[cnes].type.coding.extension ^short = "Extensões da codificação do tipo do identificador do estabelecimento"
* identifier[cnes].type.coding.extension ^definition = "Extensões incluídas na codificação do tipo do identificador do estabelecimento"
* identifier[cnes].type.coding.system 1..1
* identifier[cnes].type.coding.system = "http://terminology.hl7.org/CodeSystem/v2-0203" (exactly)
* identifier[cnes].type.coding.system ^short = "Sistema da codificação do tipo do identificador do estabelecimento"
* identifier[cnes].type.coding.system ^definition = "Sistema que identifica a codificação do tipo do identificador do estabelecimento"
* identifier[cnes].type.coding.version ^short = "Versão da codificação do tipo do identificador do estabelecimento"
* identifier[cnes].type.coding.version ^definition = "Versão da codificação do tipo do identificador do estabelecimento"
* identifier[cnes].type.coding.code 1..1
* identifier[cnes].type.coding.code = http://terminology.hl7.org/CodeSystem/v2-0203#PRN (exactly)
* identifier[cnes].type.coding.code ^short = "Código da codificação do tipo do identificador do estabelecimento"
* identifier[cnes].type.coding.code ^definition = "Código que representa a codificação do tipo do identificador do estabelecimento"
* identifier[cnes].type.coding.display ^short = "Texto da codificação do tipo do identificador do estabelecimento"
* identifier[cnes].type.coding.display ^definition = "Texto que representa a codificação do tipo do identificador do estabelecimento"
* identifier[cnes].type.coding.userSelected ^short = "Seleção do usuário da codificação do tipo do identificador do estabelecimento"
* identifier[cnes].type.coding.userSelected ^definition = "Indica se a codificação do tipo do identificador do estabelecimento foi selecionada pelo usuário"
* identifier[cnes].type.text ^short = "Texto do tipo do identificador do estabelecimento"
* identifier[cnes].type.text ^definition = "Texto que representa o tipo do identificador do estabelecimento"
* identifier[cnes].system 1..1
* identifier[cnes].system ^short = "Sistema do identificador do estabelecimento"
* identifier[cnes].system ^definition = "Sistema que identifica o tipo do identificador do estabelecimento"
* identifier[cnes].system = "https://saude.gov.br/fhir/sid/cnes" (exactly)
* identifier[cnes].value 1..1
* identifier[cnes].value ^short = "Valor do identificador do estabelecimento"
* identifier[cnes].value ^definition = "Valor do identificador do estabelecimento"
* identifier[cnes].period ^short = "Período de uso do identificador do estabelecimento"
* identifier[cnes].period ^definition = "Período de tempo durante o qual o identificador do estabelecimento foi utilizado"
* identifier[cnes].assigner ^short = "Referência à organização que atribuiu o identificador ao estabelecimento"
* identifier[cnes].assigner ^definition = "Referência à organização que atribuiu o identificador ao estabelecimento"
* identifier[cnes].assigner only Reference(br-core-organization)
* identifier[cnes].assigner.id ^short = "Identificador único para referência cruzada"
* identifier[cnes].assigner.id ^short = "Identificador único para referência cruzada"
* identifier[cnes].assigner.extension ^short = "Extensões adicionais definidas pela implementação"
* identifier[cnes].assigner.extension ^definition = "Extensões adicionais definidas pela implementação"
* identifier[cnes].assigner.reference ^short = "Referência literal, URL relativa, interna ou absoluta"
* identifier[cnes].assigner.reference ^definition = "Referência literal, URL relativa, interna ou absoluta"
* identifier[cnes].assigner.type ^short = "Tipo referenciado (p. ex. br-core-patient)"
* identifier[cnes].assigner.type ^definition = "Tipo referenciado (p. ex. br-core-patient)"
* identifier[cnes].assigner.identifier ^short = "Referência lógica, quando a referência literal não é conhecida"
* identifier[cnes].assigner.identifier ^definition = "Referência lógica, quando a referência literal não é conhecida"
* identifier[cnes].assigner.display ^short = "Nome da entidade que atribuiu o identificador da organização"
* identifier[cnes].assigner.display ^definition = "Nome da entidade que atribuiu o identificador da organização"
* identifier[cpf] ^short = "Identificador do estabelecimento (CPF)"
* identifier[cpf] ^definition = "Identificador do estabelecimento"
* identifier[cpf].id ^short = "Id lógico do identificador do estabelecimento"
* identifier[cpf].id ^definition = "Id lógico do identificador do estabelecimento"
* identifier[cpf].extension ^short = "Extensões do identificador do estabelecimento"
* identifier[cpf].extension ^definition = "Extensões incluídas no identificador do estabelecimento"
* identifier[cpf].use ^short = "Uso do identificador do estabelecimento"
* identifier[cpf].use ^definition = "usual: identificador usual do estabelecimento. official: identificador oficial do estabelecimento. temp: identificador temporário do estabelecimento. secondary: identificador secundário do estabelecimento"
* identifier[cpf].use = http://hl7.org/fhir/identifier-use#official (exactly)
* identifier[cpf].type ^short = "Tipo do identificador do estabelecimento"
* identifier[cpf].type ^definition = "Código que representa o tipo do identificador do estabelecimento"
* identifier[cpf].type ^binding.description = "Tipo do identificador do estabelecimento"
* identifier[cpf].type ^binding.strength = #required
* identifier[cpf].type ^binding.valueSet = http://hl7.org/fhir/ValueSet/identifier-type
* identifier[cpf].type.id ^short = "Id lógico do tipo do identificador do estabelecimento"
* identifier[cpf].type.id ^definition = "Id lógico do tipo do identificador do estabelecimento"
* identifier[cpf].type.extension ^short = "Extensões do tipo do identificador do estabelecimento"
* identifier[cpf].type.extension ^definition = "Extensões incluídas no tipo do identificador do estabelecimento"
* identifier[cpf].type.coding 1..1
* identifier[cpf].type.coding ^short = "Codificação do tipo do identificador do estabelecimento"
* identifier[cpf].type.coding ^definition = "Codificação que representa o tipo do identificador do estabelecimento"
* identifier[cpf].type.coding.id ^short = "Id lógico da codificação do tipo do identificador do estabelecimento"
* identifier[cpf].type.coding.id ^definition = "Id lógico da codificação do tipo do identificador do estabelecimento"
* identifier[cpf].type.coding.extension ^short = "Extensões da codificação do tipo do identificador do estabelecimento"
* identifier[cpf].type.coding.extension ^definition = "Extensões incluídas na codificação do tipo do identificador do estabelecimento"
* identifier[cpf].type.coding.system 1..1
* identifier[cpf].type.coding.system = "http://terminology.hl7.org/CodeSystem/v2-0203" (exactly)
* identifier[cpf].type.coding.system ^short = "Sistema da codificação do tipo do identificador do estabelecimento"
* identifier[cpf].type.coding.system ^definition = "Sistema que identifica a codificação do tipo do identificador do estabelecimento"
* identifier[cpf].type.coding.version ^short = "Versão da codificação do tipo do identificador do estabelecimento"
* identifier[cpf].type.coding.version ^definition = "Versão da codificação do tipo do identificador do estabelecimento"
* identifier[cpf].type.coding.code 1..1
* identifier[cpf].type.coding.code ^short = "Código da codificação do tipo do identificador do estabelecimento"
* identifier[cpf].type.coding.code ^definition = "Código que representa a codificação do tipo do identificador do estabelecimento"
* identifier[cpf].type.coding.display ^short = "Texto da codificação do tipo do identificador do estabelecimento"
* identifier[cpf].type.coding.display ^definition = "Texto que representa a codificação do tipo do identificador do estabelecimento"
* identifier[cpf].type.coding.userSelected ^short = "Seleção do usuário da codificação do tipo do identificador do estabelecimento"
* identifier[cpf].type.coding.userSelected ^definition = "Indica se a codificação do tipo do identificador do estabelecimento foi selecionada pelo usuário"
* identifier[cpf].type.text ^short = "Texto do tipo do identificador do estabelecimento"
* identifier[cpf].type.text ^definition = "Texto que representa o tipo do identificador do estabelecimento"
* identifier[cpf].system 1..1
* identifier[cpf].system ^short = "Sistema do identificador do estabelecimento"
* identifier[cpf].system ^definition = "Sistema que identifica o tipo do identificador do estabelecimento"
* identifier[cpf].system = "https://saude.gov.br/fhir/sid/cpf" (exactly)
* identifier[cpf].value 1..1
* identifier[cpf].value ^short = "Valor do identificador do estabelecimento"
* identifier[cpf].value ^definition = "Valor do identificador do estabelecimento"
* identifier[cpf].period ^short = "Período de uso do identificador do estabelecimento"
* identifier[cpf].period ^definition = "Período de tempo durante o qual o identificador do estabelecimento foi utilizado"
* identifier[cpf].assigner ^short = "Referência à organização que atribuiu o identificador ao estabelecimento"
* identifier[cpf].assigner ^definition = "Referência à organização que atribuiu o identificador ao estabelecimento"
* identifier[cpf].assigner only Reference(br-core-organization)
* identifier[cpf].assigner.id ^short = "Identificador único para referência cruzada"
* identifier[cpf].assigner.id ^short = "Identificador único para referência cruzada"
* identifier[cpf].assigner.extension ^short = "Extensões adicionais definidas pela implementação"
* identifier[cpf].assigner.extension ^definition = "Extensões adicionais definidas pela implementação"
* identifier[cpf].assigner.reference ^short = "Referência literal, URL relativa, interna ou absoluta"
* identifier[cpf].assigner.reference ^definition = "Referência literal, URL relativa, interna ou absoluta"
* identifier[cpf].assigner.type ^short = "Tipo referenciado (p. ex. br-core-patient)"
* identifier[cpf].assigner.type ^definition = "Tipo referenciado (p. ex. br-core-patient)"
* identifier[cpf].assigner.identifier ^short = "Referência lógica, quando a referência literal não é conhecida"
* identifier[cpf].assigner.identifier ^definition = "Referência lógica, quando a referência literal não é conhecida"
* identifier[cpf].assigner.display ^short = "Nome da entidade que atribuiu o identificador da organização"
* identifier[cpf].assigner.display ^definition = "Nome da entidade que atribuiu o identificador da organização"
* identifier[cnpj] ^short = "Identificador do estabelecimento (CNPJ)"
* identifier[cnpj] ^definition = "Identificador do estabelecimento"
* identifier[cnpj].id ^short = "Id lógico do identificador do estabelecimento"
* identifier[cnpj].id ^definition = "Id lógico do identificador do estabelecimento"
* identifier[cnpj].extension ^short = "Extensões do identificador do estabelecimento"
* identifier[cnpj].extension ^definition = "Extensões incluídas no identificador do estabelecimento"
* identifier[cnpj].use ^short = "Uso do identificador do estabelecimento"
* identifier[cnpj].use ^definition = "usual: identificador usual do estabelecimento. official: identificador oficial do estabelecimento. temp: identificador temporário do estabelecimento. secondary: identificador secundário do estabelecimento"
* identifier[cnpj].use = http://hl7.org/fhir/identifier-use#official (exactly)
* identifier[cnpj].type ^short = "Tipo do identificador do estabelecimento"
* identifier[cnpj].type ^definition = "Código que representa o tipo do identificador do estabelecimento"
* identifier[cnpj].type ^binding.description = "Tipo do identificador do estabelecimento"
* identifier[cnpj].type ^binding.strength = #required
* identifier[cnpj].type ^binding.valueSet = http://hl7.org/fhir/ValueSet/identifier-type
* identifier[cnpj].type.id ^short = "Id lógico do tipo do identificador do estabelecimento"
* identifier[cnpj].type.id ^definition = "Id lógico do tipo do identificador do estabelecimento"
* identifier[cnpj].type.extension ^short = "Extensões do tipo do identificador do estabelecimento"
* identifier[cnpj].type.extension ^definition = "Extensões incluídas no tipo do identificador do estabelecimento"
* identifier[cnpj].type.coding 1..1
* identifier[cnpj].type.coding ^short = "Codificação do tipo do identificador do estabelecimento"
* identifier[cnpj].type.coding ^definition = "Codificação que representa o tipo do identificador do estabelecimento"
* identifier[cnpj].type.coding.id ^short = "Id lógico da codificação do tipo do identificador do estabelecimento"
* identifier[cnpj].type.coding.id ^definition = "Id lógico da codificação do tipo do identificador do estabelecimento"
* identifier[cnpj].type.coding.extension ^short = "Extensões da codificação do tipo do identificador do estabelecimento"
* identifier[cnpj].type.coding.extension ^definition = "Extensões incluídas na codificação do tipo do identificador do estabelecimento"
* identifier[cnpj].type.coding.system 1..1
* identifier[cnpj].type.coding.system = "http://terminology.hl7.org/CodeSystem/v2-0203" (exactly)
* identifier[cnpj].type.coding.system ^short = "Sistema da codificação do tipo do identificador do estabelecimento"
* identifier[cnpj].type.coding.system ^definition = "Sistema que identifica a codificação do tipo do identificador do estabelecimento"
* identifier[cnpj].type.coding.version ^short = "Versão da codificação do tipo do identificador do estabelecimento"
* identifier[cnpj].type.coding.version ^definition = "Versão da codificação do tipo do identificador do estabelecimento"
* identifier[cnpj].type.coding.code 1..1
* identifier[cnpj].type.coding.code ^short = "Código da codificação do tipo do identificador do estabelecimento"
* identifier[cnpj].type.coding.code ^definition = "Código que representa a codificação do tipo do identificador do estabelecimento"
* identifier[cnpj].type.coding.display ^short = "Texto da codificação do tipo do identificador do estabelecimento"
* identifier[cnpj].type.coding.display ^definition = "Texto que representa a codificação do tipo do identificador do estabelecimento"
* identifier[cnpj].type.coding.userSelected ^short = "Seleção do usuário da codificação do tipo do identificador do estabelecimento"
* identifier[cnpj].type.coding.userSelected ^definition = "Indica se a codificação do tipo do identificador do estabelecimento foi selecionada pelo usuário"
* identifier[cnpj].type.text ^short = "Texto do tipo do identificador do estabelecimento"
* identifier[cnpj].type.text ^definition = "Texto que representa o tipo do identificador do estabelecimento"
* identifier[cnpj].system 1..1
* identifier[cnpj].system ^short = "Sistema do identificador do estabelecimento"
* identifier[cnpj].system ^definition = "Sistema que identifica o tipo do identificador do estabelecimento"
* identifier[cnpj].system = "https://saude.gov.br/fhir/sid/cnpj" (exactly)  
* identifier[cnpj].value 1..1
* identifier[cnpj].value ^short = "Valor do identificador do estabelecimento"
* identifier[cnpj].value ^definition = "Valor do identificador do estabelecimento"
* identifier[cnpj].period ^short = "Período de uso do identificador do estabelecimento"
* identifier[cnpj].period ^definition = "Período de tempo durante o qual o identificador do estabelecimento foi utilizado"
* identifier[cnpj].assigner ^short = "Referência à organização que atribuiu o identificador ao estabelecimento"
* identifier[cnpj].assigner ^definition = "Referência à organização que atribuiu o identificador ao estabelecimento"
* identifier[cnpj].assigner only Reference(br-core-organization)
* identifier[cnpj].assigner.id ^short = "Identificador único para referência cruzada"
* identifier[cnpj].assigner.id ^short = "Identificador único para referência cruzada"
* identifier[cnpj].assigner.extension ^short = "Extensões adicionais definidas pela implementação"
* identifier[cnpj].assigner.extension ^definition = "Extensões adicionais definidas pela implementação"
* identifier[cnpj].assigner.reference ^short = "Referência literal, URL relativa, interna ou absoluta"
* identifier[cnpj].assigner.reference ^definition = "Referência literal, URL relativa, interna ou absoluta"
* identifier[cnpj].assigner.type ^short = "Tipo referenciado (p. ex. br-core-patient)"
* identifier[cnpj].assigner.type ^definition = "Tipo referenciado (p. ex. br-core-patient)"
* identifier[cnpj].assigner.identifier ^short = "Referência lógica, quando a referência literal não é conhecida"
* identifier[cnpj].assigner.identifier ^definition = "Referência lógica, quando a referência literal não é conhecida"
* identifier[cnpj].assigner.display ^short = "Nome da entidade que atribuiu o identificador da organização"
* identifier[cnpj].assigner.display ^definition = "Nome da entidade que atribuiu o identificador da organização"
* active ^short = "Indica se a Organização está ativa" 
* active ^definition = "Indica se a Organização está ativa"
* type ^short = "Tipo da organização"
* type ^definition = "Tipo da organização"
* type from https://terminologia.saude.gov.br/fhir/ValueSet/BRTipoEstabelecimentoSaude (example)
* name 1..1
* name ^short = "Nome da organização"
* name ^definition = "Nome da organização"
* alias 1..1
* alias ^short = "Razão social da organização"
* alias ^definition = "Razão social da organização"
* telecom ^short = "Meio de contato" 
* telecom ^definition = "Meio de contato" 
* address 1..1
* address ^short = "Endereço"
* address ^definition = "Endereço"
* partOf ^short = "Referência à Organização associada (p.ex. Mantenedora)"
* partOf ^definition = "Referência à Organização associada (p.ex. Mantenedora)"
* partOf only Reference(br-core-organization)
* contact ^short = "Contato"
* contact ^definition = "Contato para a organização para uma determinada finalidade"
* contact.id ^short = "Identificação unívoca da pessoa de contato"
* contact.id ^definition = "Identificação unívoca da pessoa de contato"
* contact.extension ^short = "Extensões adicionais"
* contact.extension ^definition = "Extensões adicionais que não fazem parte do modelo base"
* contact.modifierExtension ^short = "Extensões adicionais"
* contact.modifierExtension ^definition = "Extensões adicionais que não fazem parte do modelo base"
* contact.purpose ^short = "Tipo de Contato"
* contact.purpose ^definition = "Tipo de Contato"
* contact.name ^short = "Nome associado ao contato"
* contact.name ^definition = "Nome associado ao contato"
* contact.telecom ^short = "Meio de Contato"
* contact.telecom ^definition = "Meio de Contato"
* contact.address ^short = "Endereço do contato"
* contact.address ^definition = "Endereço do contato"
* endpoint ^short = "Endpoints técnicos que fornecem acesso a serviços eletrônicos operados pela organização"
* endpoint ^definition = "Endpoints técnicos que fornecem acesso a serviços eletrônicos operados pela organização"
* endpoint only Reference(Endpoint)