Profile: BRCoreLocation
Parent: http://hl7.org/fhir/StructureDefinition/Location
Id: br-core-location
Title: "br-core-location"
Description: "Este perfil restringe o recurso [Location](https://hl7.org/fhir/R4/location.html) que aborda detalhes e informações da posição de um local físico onde os serviços são fornecidos e os recursos e participantes podem ser armazenados, encontrados, contidos ou acomodados"

* id ^short = "Identificador lógico deste artefato"
* id ^definition = "Identificador lógico deste artefato"
* meta ^short = "Metadados sobre o recurso"
* meta ^definition = "Metadados sobre o recurso" 
* implicitRules ^short = "Um conjunto de regras sob as quais este conteúdo foi criado"
* implicitRules ^definition = "Um conjunto de regras sob as quais este conteúdo foi criado"
* language ^short = "Idioma do recurso"
* language ^definition = "Idioma do recurso"
* text ^short = "Resumo do texto do recurso em linguagem natural"
* text ^definition = "Resumo do texto do recurso em linguagem natural"
* contained ^short = "Recursos contidos no recurso"
* contained ^definition = "Recursos contidos no recurso"
* extension ^short = "Extensões adicionais que não fazem parte do modelo base"
* extension ^definition = "Extensões adicionais que não fazem parte do modelo base"
* modifierExtension ^short = "Extensões adicionais que não podem ser ignoradas, mesmo que não reconhecidas"
* modifierExtension ^definition = "Extensões adicionais que não podem ser ignoradas, mesmo que não reconhecidas"
* identifier ^short = "Identificadores para este recurso"
* identifier ^definition = "Identificadores para este recurso"
* status ^short = "Indica se o local ainda está em uso: active | suspended | inactive"
* status ^definition = "Indica se o local ainda está em uso: active | suspended | inactive"
* status 1..1
* operationalStatus ^short = "O status operacional do local (normalmente apenas para uma cama/quarto)"
* operationalStatus ^definition = "O status operacional do local (normalmente apenas para uma cama/quarto)"
* name ^short = "Nome do local"
* name ^definition = "Nome do local"
* name 1..1
* alias ^short = "Uma lista de nomes alternativos pelos quais o local é conhecido, ou foi conhecido, no passado"
* alias ^definition = "Uma lista de nomes alternativos pelos quais o local é conhecido, ou foi conhecido, no passado"
* description ^short = "Detalhes adicionais sobre o local que podem ser exibidos como informações adicionais para identificar o local além do seu nome"
* description ^definition = "Detalhes adicionais sobre o local que podem ser exibidos como informações adicionais para identificar o local além do seu nome"
* mode ^short = "Indica se uma instância deste recurso representa um local específico ou uma classe de locais"
* mode ^definition = "Indica se uma instância deste recurso representa um local específico ou uma classe de locais"
* type ^short = "Tipo de serviço oferecido"
* type ^definition = "Tipo de serviço oferecido"
* type from https://terminologia.saude.gov.br/fhir/ValueSet/BRServicoEspecializado 
* telecom ^short = "Detalhes de contato do local"
* telecom ^definition = "Detalhes de contato do local"
* address ^short = "Endereço do local"
* address ^definition = "Endereço do local"
* physicalType ^short = "Estrutura física do local"
* physicalType ^definition = "Estrutura física do local"
* physicalType from https://terminologia.saude.gov.br/fhir/ValueSet/BRInstalacoesFisicas (preferred)
* position ^short = "A localização geográfica absoluta"
* position ^definition = "A localização geográfica absoluta"
* position.id ^short = "Identificador único para referência cruzada"
* position.id ^definition = "Identificador único para referência cruzada"
* position.extension ^short = "Extensões adicionais que não fazem parte do modelo de dados básico"
* position.extension ^definition = "Extensões adicionais que não fazem parte do modelo de dados básico"
* position.modifierExtension ^short = "Extensões adicionais que não podem ser ignoradas, mesmo que não reconhecidas"
* position.modifierExtension ^definition = "Extensões adicionais que não podem ser ignoradas, mesmo que não reconhecidas"
* position.longitude ^short = "Longitude com referência WGS84"
* position.longitude ^definition = "Longitude com referência WGS84"
* position.latitude ^short = "Latitude com referência WGS84"
* position.latitude ^definition = "Latitude com referência WGS84"
* position.altitude ^short = "Altitude com referência WGS84"
* position.altitude ^definition = "Altitude com referência WGS84"
* managingOrganization ^short = "Referência à organização responsável pelo provisionamento e manutenção"
* managingOrganization ^definition = "Referência à organização responsável pelo provisionamento e manutenção"
* partOf ^short = "Referência à outro local que esta localidade é parte"
* partOf ^definition = "Referência à outro local que esta localidade é parte"
* partOf only Reference(br-core-location)
* hoursOfOperation ^short = "Horário de funcionamento"
* hoursOfOperation ^definition = "Horário de funcionamento"
* hoursOfOperation.id ^short = "Identificador único para referência cruzada"
* hoursOfOperation.id ^definition = "Identificador único para referência cruzada"
* hoursOfOperation.extension ^short = "Extensões adicionais que não fazem parte do modelo de dados básico"
* hoursOfOperation.extension ^definition = "Extensões adicionais que não fazem parte do modelo de dados básico"
* hoursOfOperation.modifierExtension ^short = "Extensões adicionais que não podem ser ignoradas, mesmo que não reconhecidas"
* hoursOfOperation.modifierExtension ^definition = "Extensões adicionais que não podem ser ignoradas, mesmo que não reconhecidas"
* hoursOfOperation.daysOfWeek ^short = "Dias da semana"
* hoursOfOperation.daysOfWeek ^definition = "Dias da semana"
* hoursOfOperation.allDay ^short = "Se o local está aberto o dia inteiro"
* hoursOfOperation.allDay ^definition = "Se o local está aberto o dia inteiro"
* hoursOfOperation.openingTime ^short = "Horário de abertura do local"
* hoursOfOperation.openingTime ^definition = "Horário de abertura do local"
* hoursOfOperation.closingTime ^short = "Horário de fechamento do local"
* hoursOfOperation.closingTime ^definition = "Horário de fechamento do local"
* availabilityExceptions ^short = "Descrição das exceções de disponibilidade"
* availabilityExceptions ^definition = "Descrição das exceções de disponibilidade"
* endpoint ^short = "Endpoints técnicos que fornecem acesso aos serviços operados para o local"
* endpoint ^definition = "Endpoints técnicos que fornecem acesso aos serviços operados para o local"