Profile: BRMedicationStatement
Parent: http://hl7.org/fhir/StructureDefinition/MedicationStatement
Id: br-core-medicationstatement
Title: "br-core-medicationstatement"
Description: "Um registro de um medicamento que está sendo consumido por um paciente. Um recurso [br-core-medicationstatement](https://saude.gov.br/fhir/StructureDefiniton/medicationstatement.html) indica  que o paciente pode estar tomando o medicamento agora ou tomou o medicamento no passado ou tomará o medicamento no futuro. A fonte dessas informações pode ser o paciente, outra pessoa significativa (como um membro da família ou cônjuge) ou um clínico. Um cenário comum em que essas informações são capturadas é durante o processo de obtenção do histórico durante uma visita ou internação do paciente. As informações sobre medicamentos podem vir de fontes como a memória do paciente, de um frasco de prescrição ou de uma lista de medicamentos que o paciente, o clínico ou outra parte mantém.

A principal diferença entre um recurso [br-core-medicationstatement](https://saude.gov.br/fhir/StructureDefiniton/medicationstatement.html) e um [br-core-medicationadministration](https://saude.gov.br/fhir/StructureDefiniton/medicationadministration.html) é que o último  contém informações completas sobre a administração e é baseada em informações reais sobre a administração e da pessoa que administrou o medicamento.  Um [br-core-medicationstatement](https://saude.gov.br/fhir/StructureDefiniton/medicationstatement.html#MedicationStatement) é frequentemente, se não sempre, menos específico. Não há data/hora obrigatória em que o medicamento foi administrado; na verdade, sabe-se apenas que uma fonte relatou que o paciente está tomando esse medicamento, onde detalhes como hora, quantidade ou taxa ou mesmo o produto do medicamento podem estar incompletos, ausentes ou menos precisos. Conforme dito anteriormente, as informações do [br-core-medicationstatement](https://saude.gov.br/fhir/StructureDefiniton/medicationstatement.html#MedicationStatement) podem vir da memória do paciente, de um frasco de prescrição ou de uma lista de medicamentos que o paciente, o clínico ou outra parte mantém. A administração de medicamentos é mais formal e não deixa de ter informações detalhadas.
"

* id ^short = "Identificador lógico deste artefato"
* id ^definition = "Identificador lógico deste artefato"
* meta ^short = "Metadados sobre o recurso"
* meta ^definition = "Metadados sobre o recurso" 
* implicitRules ^short = "Um conjunto de regras sob as quais este conteúdo foi criado"
* implicitRules ^definition = "Um conjunto de regras sob as quais este conteúdo foi criado"
* language ^short = "Idioma do recurso"
* language ^definition = "Idioma do recurso"
* text ^short = "Resumo do texto do recurso em linguagem natural"
* text ^definition = "Resumo do texto do recurso em linguagem natural"
* contained ^short = "Recursos contidos no recurso"
* contained ^definition = "Recursos contidos no recurso"
* extension ^short = "Extensões adicionais que não fazem parte do modelo base"
* extension ^definition = "Extensões adicionais que não fazem parte do modelo base"
* modifierExtension ^short = "Extensões adicionais que não podem ser ignoradas, mesmo que não reconhecidas"
* modifierExtension ^definition = "Extensões adicionais que não podem ser ignoradas, mesmo que não reconhecidas"
* identifier ^short = "Identificadores externos para este recurso"
* identifier ^definition = "Identificadores externos para este recurso"
* basedOn ^short = "Referência ao pedido ou ao plano de tratamento que gerou este recurso"
* basedOn ^definition = "Referência ao pedido ou ao plano de tratamento que gerou este recurso"
* basedOn only Reference(br-core-medicationrequest or br-core-careplan or br-core-servicerequest)
* partOf ^short = "Referência ao evento do qual este recurso faz parte"
* partOf ^definition = "Referência ao evento do qual este recurso faz parte"
* partOf only Reference(br-core-medicationadministration or br-core-medicationdispense or br-core-medicationstatement or br-core-procedure or br-core-observation)
* status ^short = "Status atual do recurso: active | completed | entered-in-error | intended | stopped | on-hold | unknown | not-taken"
* status ^definition = "Status atual do recurso: active | completed | entered-in-error | intended | stopped | on-hold | unknown | not-taken"
* statusReason ^short = "Motivo do status atual"
* statusReason ^definition = "Motivo do status atual"
* category ^short = "Um conceito codificado identificando onde se espera que o medicamento incluído neste recurso seja administrado"
* category ^definition = "Um conceito codificado identificando onde se espera que o medicamento incluído neste recurso seja administrado"
* medication[x] ^short = "Qual medicamento foi tomado"
* medication[x] ^definition = "Qual medicamento foi tomado"
* medicationReference ^short = "Referência ao medicamento"
* medicationReference ^definition = "Referência ao medicamento"
* medicationReference only Reference(br-core-medication)
* subject ^short = "Referência que utiliza o medicamento"
* subject ^definition = "Referência que utiliza o medicamento"
* subject only Reference(br-core-patient)
* subject.id ^short = "Identificador único para referência cruzada"
* subject.id ^definition = "Identificador único para referência cruzada"
* subject.extension ^short = "Extensões adicionais que não fazem parte do modelo de dados básico"
* subject.extension ^definition = "Extensões adicionais que não fazem parte do modelo de dados básico"
* subject.reference ^short = "Referência literal. URL relativa, interna ou externa"
* subject.reference ^definition = "Referência literal. URL relativa, interna ou externa"
* subject.type ^short = "Tipo de recurso ao qual a referência é feita"
* subject.type ^definition = "Tipo de recurso ao qual a referência é feita"
* subject.identifier ^short = "Referência lógica, quando a referência literal não é conhecida"
* subject.identifier ^definition = "Referência lógica, quando a referência literal não é conhecida"
* subject.display ^short = "Texto alternativo para o recurso"
* subject.display ^definition = "Texto alternativo para o recurso"
* context ^short = "Referência ao atendimento ou ao cuidado de associado a este recurso"
* context ^definition = "Referência ao atendimento ou ao cuidado de associado a este recurso"
* context only Reference(br-core-encounter or EpisodeOfCare)
* effective[x] only dateTime or Period
* effective[x] ^short = "Data ou intervalo de tempo na qual o medicamento foi ou será administrado"
* effective[x] ^definition = "Data ou intervalo de tempo na qual o medicamento foi ou será administrado"
* effectiveDateTime ^short = "Data na qual o medicamento foi ou será administrado"
* effectiveDateTime ^definition = "Data na qual o medicamento foi ou será administrado"
* effectivePeriod ^short = "Intervalo de tempo no qual o medicamento foi ou será administrado"
* effectivePeriod ^definition = "Intervalo de tempo no qual o medicamento foi ou será administrado"
* dateAsserted ^short = "Data de registro deste recurso" 
* dateAsserted ^definition = "Data de registro deste recurso" 
* informationSource ^short = "Referência à pessoa ou organização que forneceu as informações sobre este recurso"
* informationSource ^definition = "Referência à pessoa ou organização que forneceu as informações sobre este recurso"
* informationSource only Reference(br-core-patient or br-core-practitioner or br-core-practitionerrole or br-core-relatedperson or br-core-organization)
* derivedFrom ^short = "Referência à um recurso com informações adicionais"
* derivedFrom ^definition = "Referência à um recurso com informações adicionais"
* derivedFrom only Reference(Resource)
* reasonCode ^short = "Motivo pelo qual o medicamento foi ou será administrado"
* reasonCode ^definition = "Motivo pelo qual o medicamento foi ou será administrado"
* reasonReference ^short = "Referência à condição ou observação associado a este recurso"
* reasonReference ^definition = "Referência à condição ou observação associado a este recurso"
* reasonReference only Reference(br-core-condition or br-core-observation or br-core-diagnosticreport)
* note ^short = "Informações adicionais sobre essa declaração"
* note ^definition = "Informações adicionais sobre essa declaração"
* dosage ^short = "Dosagem dos medicamentos"
* dosage ^definition = "Dosagem dos medicamentos"
* dosage.id ^short = "Identificador único para referência cruzada"
* dosage.id ^definition = "Identificador único para referência cruzada"
* dosage.extension ^short = "Extensões adicionais que não fazem parte do modelo de dados básico"
* dosage.extension ^definition = "Extensões adicionais que não fazem parte do modelo de dados básico" 
* dosage.modifierExtension ^short = "Extensões adicionais que não podem ser ignoradas, mesmo que não reconhecidas"
* dosage.modifierExtension ^definition = "Extensões adicionais que não podem ser ignoradas, mesmo que não reconhecidas"
* dosage.sequence ^short = "A ordem das instruções de dosagem"
* dosage.sequence ^definition = "A ordem das instruções de dosagem"
* dosage.text ^short = "Instruções de dosagem em texto livre"
* dosage.text ^definition = "Instruções de dosagem em texto livre"
* dosage.additionalInstruction ^short = "Informações auxiliares ou advertências ao paciente"
* dosage.additionalInstruction ^definition = "Informações auxiliares ou advertências ao paciente"
* dosage.patientInstruction ^short = "Instruções orientadas ao paciente ou consumidor"
* dosage.patientInstruction ^definition = "Instruções orientadas ao paciente ou consumidor"
* dosage.timing ^short = "Quando o medicamento deve ser administrado"
* dosage.timing ^definition = "Quando o medicamento deve ser administrado"
* dosage.asNeeded[x] ^short = "Tomar \"conforme necessário\" (para x)" 
* dosage.asNeeded[x] ^definition = "Tomar \"conforme necessário\" (para x)" 
* dosage.site ^short = "Local no corpo onde deve ser administrado o medicamento"
* dosage.site ^definition = "Local no corpo onde deve ser administrado o medicamento"
* dosage.site from http://hl7.org/fhir/ValueSet/body-site (example)
* dosage.route ^short = "Via de administração"
* dosage.route ^definition = "Via de administração"
* dosage.route from http://hl7.org/fhir/uv/ips/ValueSet/medicine-route-of-administration (example)
* dosage.method ^short = "Método de administração"
* dosage.method ^definition = "Método de administração"
* dosage.doseAndRate ^short = "Quantidade de medicamento administrado"
* dosage.doseAndRate ^definition = "Quantidade de medicamento administrado"
* dosage.doseAndRate.id ^short = "Identificador único para referência cruzada"
* dosage.doseAndRate.id ^definition = "Identificador único para referência cruzada"
* dosage.doseAndRate.extension ^short = "Extensões adicionais que não fazem parte do modelo de dados básico"
* dosage.doseAndRate.extension ^definition = "Extensões adicionais que não fazem parte do modelo de dados básico" 
* dosage.doseAndRate.type ^short = "O tipo de dose especificado"
* dosage.doseAndRate.type ^definition = "O tipo de dose especificado"
* dosage.doseAndRate.dose[x] ^short = "Quantidade de medicamento por dose"
* dosage.doseAndRate.dose[x] ^definition = "Quantidade de medicamento por dose"
* dosage.doseAndRate.rate[x] ^short = "Quantidade de medicamento por unidade de tempo"
* dosage.doseAndRate.rate[x] ^definition = "Quantidade de medicamento por unidade de tempo"
* dosage.maxDosePerPeriod ^short = "Limite máximo de medicamento por unidade de tempo"
* dosage.maxDosePerPeriod ^definition = "Limite máximo de medicamento por unidade de tempo"
* dosage.maxDosePerAdministration ^short = "Limite máximo de medicamento por administração"
* dosage.maxDosePerAdministration ^definition = "Limite máximo de medicamento por administração"
* dosage.maxDosePerLifetime ^short = "Limite máximo de medicamento por tempo de vida do paciente"
* dosage.maxDosePerLifetime ^definition = "Limite máximo de medicamento por tempo de vida do paciente"