Profile: BRCoreHealthcareService
Parent: http://hl7.org/fhir/StructureDefinition/HealthcareService
Id: br-core-healthcareservice
Title: "br-core-healthcareservice"
Description: "Este perfil restringe o recurso [HealthcareService](https://hl7.org/fhir/R4/healthcareservice.html) que representa os detalhes de um serviço de saúde disponível em um local."

* identifier ^short = "Identificadores externos para este recurso"
* identifier ^definition = "Identificadores externos para este recurso"
* active ^short = "Se este registro HealthcareService está em uso ativo"
* active ^definition = "Se este registro HealthcareService está em uso ativo"
* providedBy ^short = "Organização que fornece este serviço"
* providedBy ^definition = "Organização que fornece este serviço"
* category ^short = "Ampla categoria de serviço sendo executado ou entregue"
* category ^definition = "Ampla categoria de serviço sendo executado ou entregue"
* category from https://terminologia.saude.gov.br/fhir/CodeSystem/BRTipoEstabelecimentoSaude	(preferred)  
* type ^short = "Tipo de serviço que pode ser entregue ou executado"
* type ^definition = "Tipo de serviço que pode ser entregue ou executado"
* type from https://terminologia.saude.gov.br/fhir/CodeSystem/BRServicoEspecializado (preferred)
* specialty ^short = "Especialidades atendidas pelo HealthcareService"
* specialty ^definition = "Especialidades atendidas pelo HealthcareService"
* location ^short = "Local(ais) onde o serviço pode ser prestado"
* location ^definition = "Local(ais) onde o serviço pode ser prestado"
* name ^short = "Descrição do serviço conforme apresentado ao consumidor durante a pesquisa"
* name ^definition = "Descrição do serviço conforme apresentado ao consumidor durante a pesquisa"
* comment ^short = "Descrição adicional e/ou quaisquer questões específicas não abordadas em outro lugar"
* comment ^definition = "Descrição adicional e/ou quaisquer questões específicas não abordadas em outro lugar"
* extraDetails ^short = "Detalhes extras sobre o serviço que não podem ser colocados nos outros campos"
* extraDetails ^definition = "Detalhes extras sobre o serviço que não podem ser colocados nos outros campos"
* photo ^short = "Facilita a rápida identificação do serviço"
* photo ^definition = "Facilita a rápida identificação do serviço"
* telecom ^short = "Contatos relacionados ao serviço de saúde"
* telecom ^definition = "Contatos relacionados ao serviço de saúde"
* coverageArea ^short = "O serviço de localização(ões) é destinado/disponível para"
* coverageArea ^definition = "O serviço de localização(ões) é destinado/disponível para"
* serviceProvisionCode  ^short = "Condições sob as quais o serviço está disponível/oferecido"
* serviceProvisionCode  ^definition = "Condições sob as quais o serviço está disponível/oferecido"
* serviceProvisionCode from https://terminologia.saude.gov.br/fhir/ValueSet/TipoConvenio (preferred)
* eligibility ^short = "Requisitos de elegibilidade específicos necessários para usar o serviço"
* eligibility ^definition = "Requisitos de elegibilidade específicos necessários para usar o serviço"
* eligibility.code ^short = "Valor codificado para a elegibilidade"
* eligibility.code ^definition = "Valor codificado para a elegibilidade"
* eligibility.comment ^short = "Descreve as condições de elegibilidade para o serviço"
* eligibility.comment ^definition = "Descreve as condições de elegibilidade para o serviço"
* program ^short = "Programas aos quais este serviço é aplicável"
* program ^definition = "Programas aos quais este serviço é aplicável"
//* program from https://terminologia.saude.gov.br/fhir/ValueSet/BRProgramaNacionalSaude (preferred)
* characteristic ^short = "Coleção de características (atributos)"
* characteristic ^definition = "Coleção de características (atributos)"
* communication ^short = "O idioma em que este serviço é oferecido"
* communication ^definition = "O idioma em que este serviço é oferecido"
* referralMethod ^short = "Formas pelas quais o serviço aceita referências"
* referralMethod ^definition = "Formas pelas quais o serviço aceita referências"
* appointmentRequired ^short = "Se for necessário agendamento para acesso a este serviço"
* appointmentRequired ^definition = "Se for necessário agendamento para acesso a este serviço"
* availableTime ^short = "Horários em que o Site de Serviço está disponível"
* availableTime ^definition = "Horários em que o Site de Serviço está disponível"
* availableTime.daysOfWeek ^short = "Os dias da semana."
* availableTime.daysOfWeek ^definition = "mon | tue | wed | thu | fri | sat | sun"
* availableTime.allDay ^short = "Sempre disponível? por exemplo, serviço 24 horas"
* availableTime.allDay ^definition = "Sempre disponível? por exemplo, serviço 24 horas"
* availableTime.availableStartTime ^short = "Horário de abertura do dia (ignorado se allDay = true)"
* availableTime.availableStartTime ^definition = "Horário de abertura do dia (ignorado se allDay = true)"
* availableTime.availableEndTime ^short = "Hora de fechamento do dia (ignorado se allDay = true)"
* availableTime.availableEndTime ^definition = "Hora de fechamento do dia (ignorado se allDay = true)"
* notAvailable ^short = "Não disponível durante este período devido ao motivo fornecido"
* notAvailable ^definition = "Não disponível durante este período devido ao motivo fornecido"
* notAvailable.description ^short = "Motivo apresentado ao usuário explicando por que o tempo não está disponível"
* notAvailable.description ^definition = "Motivo apresentado ao usuário explicando por que o tempo não está disponível"
* notAvailable.during ^short = "Serviço não disponível a partir desta data"
* notAvailable.during ^definition = "Serviço não disponível a partir desta data"
* availabilityExceptions ^short = "Descrição das exceções de disponibilidade"
* availabilityExceptions ^definition = "Descrição das exceções de disponibilidade"
* endpoint ^short = "Endpoints técnicos que fornecem acesso a serviços eletrônicos operados para o serviço de saúde"
* endpoint ^definition = "Endpoints técnicos que fornecem acesso a serviços eletrônicos operados para o serviço de saúde"