Profile: BRCoreMedication
Parent: http://hl7.org/fhir/StructureDefinition/Medication
Id: br-core-medication
Title: "br-core-medication"
Description: "Este recurso é uma especialização do recurso FHIR R4 [Medication](https://hl7.org/fhir/R4/medication.html) usado principalmente para a identificação e definição de um medicamento para fins de prescrição, dispensação e administração de um medicamento, bem como para fazer declarações sobre medicamentos no Brasil"

* id ^short = "Identificador lógico deste artefato"
* id ^definition = "Identificador lógico deste artefato"
* meta ^short = "Metadados sobre o recurso"
* meta ^definition = "Metadados sobre o recurso" 
* implicitRules ^short = "Um conjunto de regras sob as quais este conteúdo foi criado"
* implicitRules ^definition = "Um conjunto de regras sob as quais este conteúdo foi criado"
* language ^short = "Idioma do recurso"
* language ^definition = "Idioma do recurso"
* text ^short = "Resumo do texto do recurso em linguagem natural"
* text ^definition = "Resumo do texto do recurso em linguagem natural"
* contained ^short = "Recursos contidos no recurso"
* contained ^definition = "Recursos contidos no recurso"
* extension ^short = "Extensões adicionais que não fazem parte do modelo base"
* extension ^definition = "Extensões adicionais que não fazem parte do modelo base"
* modifierExtension ^short = "Extensões adicionais que não podem ser ignoradas, mesmo que não reconhecidas"
* modifierExtension ^definition = "Extensões adicionais que não podem ser ignoradas, mesmo que não reconhecidas"
* identifier ^short = "Identificadores para este recurso"
* identifier ^definition = "Identificadores para este recurso"
* code ^short = "Código do medicamento"
* code ^definition = "Código do medicamento"
* status ^short = "Status do medicamento ativo| inativo| entrado com erro"
* status ^definition = "Status do medicamento ativo| inativo| entrado com erro"
* manufacturer ^short = "Referência ao fabricante do medicamento"
* manufacturer ^definition = "Referência ao fabricante do medicamento"
* manufacturer only Reference(br-core-organization)
* form ^short = "Forma famacêutica do medicamento"
* form ^definition = "Forma famacêutica do medicamento"
* form from http://hl7.org/fhir/uv/ips/ValueSet/medicine-doseform
* amount ^short = "Quantidade de medicamento na embalagem"
* amount ^definition = "Quantidade de medicamento na embalagem"
* ingredient ^short = "Ingredientes do medicamento"
* ingredient ^definition = "Ingredientes do medicamento"
* ingredient.id ^short = "ID exclusivo para referência entre elementos"
* ingredient.id ^definition = "ID exclusivo para referência entre elementos"
* ingredient.extension ^short = "Conteúdo adicional definido por implementações"
* ingredient.extension ^definition = "Conteúdo adicional definido por implementações"
* ingredient.modifierExtension ^short = "Extensões que não podem ser ignoradas"
* ingredient.modifierExtension ^definition = "Extensões que não podem ser ignoradas"
* ingredient.item[x] ^short = "Ingrediente"
* ingredient.item[x] ^definition = "O ingrediente ou conteúdo real Vinculante: Substâncias ativas de medicamentos - IPS (preferencial): Substâncias medicamentosas SNOMED CT"
* ingredient.itemReference ^short = "Referência à Substance ou br-core-medication"
* ingredient.itemReference ^definition = "Referência à Substance ou br-core-medication"
* ingredient.itemReference only Reference(Substance or br-core-medication)
* ingredient.isActive ^short = "Indica se este é o ingrediente ativo"
* ingredient.isActive ^definition = "Indica se este é o ingrediente ativo"
* ingredient.strength ^short = "Quantidade do ingrediente presente"
* ingredient.strength ^definition = "Quantidade do ingrediente presente"
* batch ^short = "Detalhes sobre medicamento na forma tack"
* batch ^definition = "Detalhes sobre medicamento na forma tack"
* batch.id ^short = "Identificador único para referência cruzada"
* batch.id ^definition = "Identificador único para referência cruzada"
* batch.extension ^short = "Extensões adicionais que não fazem parte do modelo de dados básico"
* batch.extension ^definition = "Extensões adicionais que não fazem parte do modelo de dados básico"
* batch.modifierExtension ^short = "Extensões adicionais que não podem ser ignoradas, mesmo que não reconhecidas"
* batch.modifierExtension ^definition = "Extensões adicionais que não podem ser ignoradas, mesmo que não reconhecidas"
* batch.lotNumber ^short = "Número do lote do pack de medicamento"
* batch.lotNumber ^definition = "Número do lote do pack de medicamento"
* batch.expirationDate ^short = "Data de validade do pack do medicamento"
* batch.expirationDate ^definition = "Data de validade do pack do medicamento"