Profile: br-core-observationresults
Parent: http://hl7.org/fhir/StructureDefinition/Observation
Id: br-core-observationresults
Description: "Este perfil representa "

* id ^short = "Identificador lógico deste artefato"
* id ^definition = "Identificador lógico deste artefato"
* meta ^short = "Metadados sobre o recurso"
* meta ^definition = "Metadados sobre o recurso"
* implicitRules ^short = "URI(s) sob as quais este recurso é conhecido"
* implicitRules ^definition = "Um ou mais códigos que servem para identificar o tipo de recurso"
* language ^short = "Idioma do recurso"
* language ^definition = "Idioma do recurso"
* text ^short = "Texto com o resumo do recurso"
* text ^definition = "Texto resumindo as informações do recurso"
* contained ^short = "Recursos contidos"
* contained ^definition = "Recursos contidos no recurso"
* extension ^short = "Extensões adicionais"
* extension ^definition = "Extensões adicionais que não fazem parte do modelo base"
* modifierExtension ^short = "Extensões adicionais que não podem ser ignoradas"
* modifierExtension ^definition = "Extensões adicionais que não podem ser ignoradas, mesmo que não reconhecidas"
* identifier ^short = "Identificadores externos para este recurso"
* identifier ^definition = "Identificadores externos para este recurso"
* basedOn ^short = "Referência ao pedido ou ao plano de tratamento que gerou este recurso"
* basedOn ^definition = "Referência ao pedido ou ao plano de tratamento que gerou este recurso"
* basedOn only Reference(CarePlan or ServiceRequest or DeviceRequest or ImmunizationRecommendation or br-core-medicationrequest or NutritionOrder)
* partOf ^short = "Referência ao evento do qual este recurso faz parte"
* partOf ^definition = "Referência ao evento do qual este recurso faz parte"
//* partOf only Reference(br-core-medicationadministration or br-core-medicationdispense or br-core-medicationstatement or br-core-procedure or br-core-immunization or ImagingStudy)
* status ^short = "Status atual da observação"
* status ^definition = "active | completed | entered-in-error | intended | stopped | on-hold | unknown | not-taken"
* category ^short = "Categoria de alto nível da observação"
* category ^definition = "Categoria de alto nível da observação"
* code ^short = "Código da observação"
* code ^definition = "Código da observação"
* subject ^short = "De quem ou do que trata a observação"
* subject ^definition = "De quem ou do que trata a observação"
* subject.id ^short = "Identificador único para referenciação cruzada"
* subject.id ^definition = "Identificador único para referenciação cruzada"
* subject.extension ^short = "Extensões adicionais que não fazem parte do modelo de dados básico"
* subject.extension ^definition = "Extensões adicionais que não fazem parte do modelo de dados básico"
* subject.reference ^short = "Referência literal. URL relativa, interna ou externa"
* subject.reference ^definition = "Referência literal. URL relativa, interna ou externa"
* subject.type ^short = "Tipo de recurso ao qual a referência é feita"
* subject.type ^definition = "Tipo de recurso ao qual a referência é feita"
* subject.identifier ^short = "Referência lógica, quando a referência literal não é conhecida"
* subject.identifier ^definition = "Referência lógica, quando a referência literal não é conhecida"
* subject.display ^short = "Texto alternativo para o recurso"
* subject.display ^definition = "Texto alternativo para o recurso"
* subject only Reference(br-core-patient or Group or Device or br-core-location)
* focus ^short = "Sobre o que é a observação, quando não é sobre o subject do registro"
* focus ^definition = "Sobre o que é a observação, quando não é sobre o subject do registro"
* focus only Reference(Resource)
* encounter ^short = "Atendimento no qual a observação foi feita"
* encounter ^definition = "Atendimento no qual a observação foi feita"
* encounter only Reference(br-core-encounter)
* effective[x] ^short = "Tempo ou período de tempo clinicamente relevante para a observação"
* effective[x] ^definition = "Tempo ou período de tempo clinicamente relevante para a observação"
* effective[x].id ^short = "Identificador único para referenciação cruzada"
* effective[x].id ^definition = "Identificador único para referenciação cruzada"
* effective[x].extension ^short = "Extensões adicionais que não fazem parte do modelo de dados básico"
* effective[x].extension ^definition = "Extensões adicionais que não fazem parte do modelo de dados básico"
//* effective[x].extension[data-absent-reason] ^short = "Por que o valor esperado não está presente"
//* effective[x].extension[data-absent-reason] ^definition = "Utilizado para especificar o porquê do valor esperado não estar presente"
* issued ^short = "Data ou hora em que esta versão da observação ficou disponível"
* issued ^definition = "Data ou hora em que esta versão da observação ficou disponível"
* performer ^short = "O responsável pela observação"
* performer ^definition = "O responsável pela observação"
//* performer only Reference(br-core-practitioner or br-core-practitionerrole or br-core-organization or CareTeam or br-core-patient or br-core-relatedperson)
* value[x] ^short = "O resultado da observação"
* value[x] ^definition = "O resultado da observação"
* dataAbsentReason ^short = "Por quê o resultado não está disponível"
* dataAbsentReason ^definition = "Utilizado para especificar o porquê do valor esperado não estar presente"
* interpretation ^short = "Interpretação da observação"
* interpretation ^definition = "Interpretação da observação. Por exemplo: valor alto, baixo, normal"
* note ^short = "Comentários sobre a observação"
* note ^definition = "Comentários sobre a observação"
* bodySite ^short = "Parte anatômica alvo da observação"
* bodySite ^definition = "Parte anatômica alvo da observação"
* method ^short = "Método de medição"
* method ^definition = "Método de medição da observação"
* specimen ^short = "Amostra utilizada para esta observação"
* specimen ^definition = "Amostra utilizada para esta observação"
* specimen only Reference(br-core-specimen)
* device ^short = "Dispositivo de medida da observação"
* device ^definition = "Dispositivo de medida da observação"
* device only Reference(Device or DeviceMetric)
* referenceRange ^short = "Fornece um guia para interpretação"
* referenceRange ^definition = "Fornece um guia para interpretação"
* referenceRange.id ^short = "Identificador único para referenciação cruzada"
* referenceRange.id ^definition = "Identificador único para referenciação cruzada"
* referenceRange.extension ^short = "Extensões adicionais que não fazem parte do modelo de dados básico"
* referenceRange.extension ^definition = "Extensões adicionais que não fazem parte do modelo de dados básico" 
* referenceRange.modifierExtension ^short = "Extensões adicionais que não podem ser ignoradas, mesmo que não reconhecidas"
* referenceRange.modifierExtension ^definition = "Extensões adicionais que não podem ser ignoradas, mesmo que não reconhecidas"
* referenceRange.low ^short = "Limite inferior do intervalo"
* referenceRange.low ^definition = "Limite inferior do intervalo de valores de referência"
* referenceRange.high ^short = "Limite superior do intervalo"
* referenceRange.high ^definition = "Limite superior do intervalo de valores de referência"
* referenceRange.type ^short = "Qualificador do valor de referência"
* referenceRange.type ^definition = "Qualificador do valor de referência"
* referenceRange.appliesTo ^short = "População do intervalo de referência"
* referenceRange.appliesTo ^definition = "População do intervalo de referência"
* referenceRange.age ^short = "Faixa etária aplicável"
* referenceRange.age ^definition = "Faixa etária aplicável, se relevante"
* referenceRange.text ^short = "Intervalo de referência em formato textual"
* referenceRange.text ^definition = "Intervalo de referência em formato textual"
* hasMember ^short = "Recurso relacionado que pertence ao grupo da Observação"
* hasMember ^definition = "Recurso relacionado que pertence ao grupo da Observação"
* hasMember only Reference(br-core-observationresults or QuestionnaireResponse or MolecularSequence)
* derivedFrom ^short = "Medições relacionadas a partir das quais a observação é feita"
* derivedFrom ^definition = "Medições relacionadas a partir das quais a observação é feita"
* derivedFrom only Reference(DocumentReference or ImagingStudy or Media or QuestionnaireResponse or br-core-observationresults or MolecularSequence)
* component ^short = "Resultados do componente"
* component ^definition = "Resultados do componente"
* component.id ^short = "Identificador único para referenciação cruzada"
* component.id ^definition = "Identificador único para referenciação cruzada"
* component.extension ^short = "Extensões adicionais que não fazem parte do modelo de dados básico"
* component.extension ^definition = "Extensões adicionais que não fazem parte do modelo de dados básico" 
* component.modifierExtension ^short = "Extensões adicionais que não podem ser ignoradas, mesmo que não reconhecidas"
* component.modifierExtension ^definition = "Extensões adicionais que não podem ser ignoradas, mesmo que não reconhecidas"
* component.code ^short = "Tipo de observação de componente"
* component.code ^short = "Tipo de observação de componente"
* component.value[x] ^short = "O valor do resultado do componente"
* component.value[x] ^definition = "O valor do resultado do componente"
* component.dataAbsentReason ^short = "Por que o resultado do componente está faltando"
* component.dataAbsentReason ^definition = "Por que o resultado do componente está faltando"
* component.interpretation ^short = "Interpretação da observação"
* component.interpretation ^definition = "Interpretação da observação. Por exemplo: valor elevado"
* component.referenceRange ^short = "Valores de referência"
* component.referenceRange ^definition = "Valores de referência para auxiliar na interpretação do resultado"