Profile: BRCoreAllergyIntolerance
Parent: http://hl7.org/fhir/StructureDefinition/AllergyIntolerance
Id: br-core-allergyintolerance
Title: "br-core-allergyintolerance"
Description: "Este perfil define as características mínimas para o recurso [br-core-allergyintolerance](StructureDefinition-br-core-allergyintolerance.html) registrar, pesquisar e buscar alergias/reações adversas associadas a um paciente. O perfil especifica quais elementos principais, extensões, vocabulários e conjuntos de valores **DEVEM** estar presentes e restringe como os elementos são usados. Além disso, fornece a base para o desenvolvimento de padrões para casos de uso específicos promove a interoperabilidade e a adoção. "

* id ^short = "Identificador lógico deste artefato"
* id ^definition = "Identificador lógico deste artefato"
* meta ^short = "Metadados sobre o recurso"
* meta ^definition = "Metadados sobre o recurso" 
* implicitRules ^short = "Um conjunto de regras sob as quais este conteúdo foi criado"
* implicitRules ^definition = "Um conjunto de regras sob as quais este conteúdo foi criado"
* language ^short = "Idioma do recurso"
* language ^definition = "Idioma do recurso"
* text ^short = "Resumo do texto do recurso em linguagem natural"
* text ^definition = "Resumo do texto do recurso em linguagem natural"
* contained ^short = "Recursos contidos no recurso"
* contained ^definition = "Recursos contidos no recurso"
* extension ^short = "Extensões adicionais que não fazem parte do modelo base"
* extension ^definition = "Extensões adicionais que não fazem parte do modelo base"
* modifierExtension ^short = "Extensões adicionais que não podem ser ignoradas, mesmo que não reconhecidas"
* modifierExtension ^definition = "Extensões adicionais que não podem ser ignoradas, mesmo que não reconhecidas"
* identifier ^short = "Identificadores externos para este recurso"
* identifier ^definition = "Identificadores externos para este recurso"
* clinicalStatus ^short = "O estado clínico da alergia ou intolerância"
* clinicalStatus ^definition = "O estado clínico da alergia ou intolerância"
* verificationStatus ^short = "Declaração sobre a certeza associada a uma propensão, ou risco potencial, de uma reação à substância identificada"
* verificationStatus ^definition = "Declaração sobre a certeza associada a uma propensão, ou risco potencial, de uma reação à substância identificada"
* type ^short = "Identificação do mecanismo fisiológico subjacente a um Risco de Reação"
* type ^definition = "Identificação do mecanismo fisiológico subjacente a um Risco de Reação"
* category ^short = "Categoria de uma substância identificada associada a alergias ou intolerâncias: comida | medicamento | ambiente | biológico"
* category ^definition = "Categoria de uma substância identificada associada a alergias ou intolerâncias: comida | medicamento | ambiente | biológico"
* criticality ^short = "Criticalidade da reação: baixo | alto | incapaz de avaliar"
* criticality ^definition  = "Criticalidade da reação: baixo | alto | incapaz de avaliar"
* code ^short = "Tipo de substância/produto, condição de alergia ou intolerância ou ou código para alergia ausente/desconhecida"
* code ^definition = "Tipo de substância/produto, condição de alergia ou intolerância ou ou código para alergia ausente/desconhecida"
* code from https://terminologia.saude.gov.br/fhir/ValueSet/BRAlergenos (required)
* patient ^short = "Referência do paciente"
* patient ^definition = "Referência do paciente"
* patient only Reference(br-core-patient)
* patient.id ^short = "Identificador exclusivo para referência entre elementos"
* patient.id ^definition = "Identificador exclusivo para referência entre elementos"
* patient.extension ^short = "Conteúdo adicional definido por implementações"
* patient.extension ^definition = "Conteúdo adicional definido por implementações"
* patient.reference ^short = "Referência literal, URL relativa, interna ou absoluta"
* patient.reference ^definition = "Referência literal, URL relativa, interna ou absoluta"
* patient.type ^short = "Tipo ao qual a referência se refere (por exemplo: Paciente)"
* patient.type ^definition = "Tipo ao qual a referência se refere (por exemplo: Paciente)"
* patient.identifier ^short = "Referência lógica, quando a referência literal não é conhecida"
* patient.identifier ^definition = "Referência lógica, quando a referência literal não é conhecida"
* patient.display ^short = "Texto alternativo para o recurso"
* patient.display ^definition = "Texto alternativo para o recurso"
* encounter ^short = "Quando a alergia ou intolerância foi afirmada"
* encounter ^definition = "Quando a alergia ou intolerância foi afirmada"
* encounter only Reference(br-core-encounter)
* onset[x] ^short = "Quando a alergia ou a intolerância foi identificada"
* onset[x] ^definition = "Quando a alergia ou a intolerância foi identificada"
* recordedDate ^short = "Data em que a primeira versão da instância do recurso foi registrada"
* recordedDate ^definition = "Data em que a primeira versão da instância do recurso foi registrada"
* recorder ^short = "Quem registrou a alergia/reação adversa"
* recorder ^definition = "Quem registrou a alergia/reação adversa"
* recorder only Reference(br-core-patient or br-core-practitioner or br-core-practitionerrole or br-core-relatedperson)
* asserter ^short = "Fonte da informação sobre a alergia/reação adversa"
* asserter ^definition = "Fonte da informação sobre a alergia/reação adversa"
* asserter only Reference(br-core-patient or br-core-practitioner or br-core-practitionerrole or br-core-relatedperson)
* lastOccurrence ^short = "Data (/hora) da última ocorrência conhecida de uma reação"
* lastOccurrence ^definition = "Data (/hora) da última ocorrência conhecida de uma reação"
* note ^short = "Texto adicional não capturado em outros campos"
* note ^definition = "Texto adicional não capturado em outros campos."
* reaction ^short = "Eventos de reação adversa relacionados à exposição da substância"
* reaction ^definition = "Eventos de reação adversa relacionados à exposição da substância"
* reaction.id ^short = "ID exclusivo para referência entre elementos"
* reaction.id ^definition = "ID exclusivo para referência entre elementos"
* reaction.modifierExtension ^short = "Conteúdo adicional definido por implementações"
* reaction.modifierExtension ^definition = "Conteúdo adicional definido por implementações"
* reaction.extension ^short = "Extensões que não podem ser ignoradas mesmo que não sejam reconhecidas"
* reaction.extension ^definition = "Extensões que não podem ser ignoradas mesmo que não sejam reconhecidas"
* reaction.substance ^short = "Substância específica ou produto farmacêutico considerado responsável pelo evento"
* reaction.substance ^definition = "Substância específica ou produto farmacêutico considerado responsável pelo evento"
* reaction.substance from https://terminologia.saude.gov.br/fhir/ValueSet/BRAlergenos
* reaction.manifestation ^short = "Código para a manifestação de reação de alergia ou intolerância do subconjunto SNOMED International Patient Set (IPS) do SNOMED CT (IPS Free Set)"
* reaction.manifestation ^definition = "Código para a manifestação de reação de alergia ou intolerância do subconjunto SNOMED IPS do SNOMED CT (IPS Free Set)"
* reaction.manifestation from https://terminologia.saude.gov.br/fhir/ValueSet/BRReacoesAdversasMedDRA (required)
* reaction.description ^short = "Descrição do evento como um todo"
* reaction.description ^definition = "Descrição do evento como um todo"
* reaction.onset ^short = "Data (/hora) em que as manifestações apareceram"
* reaction.onset ^definition = "Data (/hora) em que as manifestações apareceram"
* reaction.severity ^short = "Avaliação clínica da gravidade de um evento de reação: leve | moderado | grave (do evento como um todo)"
* reaction.severity ^definition = "Avaliação clínica da gravidade de um evento de reação: leve | moderado | grave (do evento como um todo)"
* reaction.exposureRoute ^short = "Como o sujeito foi exposto à substância"
* reaction.exposureRoute ^definition = "Como o sujeito foi exposto à substância"
* reaction.exposureRoute from http://hl7.org/fhir/uv/ips/ValueSet/medicine-route-of-administration
* reaction.note ^short = "Texto sobre evento não capturado em outros campos"
* reaction.note ^definition = "Texto sobre evento não capturado em outros campos"