Profile: br-core-medicationstatement
Parent: http://hl7.org/fhir/StructureDefinition/MedicationStatement
Id: br-core-medicationstatement
Title: "br-core-medicationstatement"
Description: "Contém os dados relacionados à medicação tomada por um paciente"


* id ^short = "Identificador lógico deste artefato"
* id ^definition = "Identificador lógico deste artefato"
* meta ^short = "Metadados sobre o recurso"
* meta ^definition = "Metadados sobre o recurso"
* implicitRules ^short = "URI(s) sob as quais este recurso é conhecido"
* implicitRules ^definition = "Um ou mais códigos que servem para identificar o tipo de recurso"
* language ^short = "Linguagem do recurso"
* language ^definition = "A linguagem humana natural do recurso"
* text ^short = "Texto narrativo, 72 caracteres para resumo"
* text ^definition = "Um texto narrativo resumindo as informações do recurso"
* contained ^short = "Recursos contidos"
* contained ^definition = "Recursos contidos no recurso"
* extension ^short = "Extensões adicionais"
* extension ^definition = "Extensões adicionais que não fazem parte do modelo base"
* modifierExtension ^short = "Extensões adicionais que não podem ser ignoradas"
* modifierExtension ^definition = "Extensões adicionais que não podem ser ignoradas, mesmo que não reconhecidas"
* identifier ^short = "Identificadores externos para este recurso"
* identifier ^definition = "Identificadores externos para este recurso"
* basedOn ^short = "Referência ao pedido ou ao plano de tratamento que gerou este recurso"
* basedOn ^definition = "Referência ao pedido ou ao plano de tratamento que gerou este recurso"
* basedOn only Reference(br-core-medicationrequest or br-core-careplan or br-core-servicerequest)
* partOf ^short = "Referência ao evento do qual este recurso faz parte"
* partOf ^definition = "Referência ao evento do qual este recurso faz parte"
//* partOf only Reference(br-core-medicationadministration or br-core-medicationdispense or br-core-medicationstatement or br-core-procedure or br-core-observationresults)
* status ^short = "Status atual do recurso"
* status ^definition = "active | completed | entered-in-error | intended | stopped | on-hold | unknown | not-taken"
* statusReason ^short = "Motivo do status atual"
* statusReason ^definition = "Motivo do status atual"
* category ^short = "Tipo de uso de medicamento"
* category ^definition = "Um conceito codificado identificando onde se espera que o medicamento incluído neste recurso seja administrado"
* medication[x] ^short = "Qual medicamento foi tomado"
* medication[x] ^definition = "Qual medicamento foi tomado"
//* medicationReference only Reference(MedicationBRIPS)
* subject ^short = "Quem toma ou tomou o medicamento"
* subject ^definition = "Quem toma ou tomou o medicamento"
* subject only Reference(br-core-patient)
* subject.id ^short = "Identificador único para referenciação cruzada"
* subject.id ^definition = "Identificador único para referenciação cruzada"
* subject.extension ^short = "Extensões adicionais que não fazem parte do modelo de dados básico"
* subject.extension ^definition = "Extensões adicionais que não fazem parte do modelo de dados básico"
* subject.reference ^short = "Referência literal. URL relativa, interna ou externa"
* subject.reference ^definition = "Referência literal. URL relativa, interna ou externa"
* subject.type ^short = "Tipo de recurso ao qual a referência é feita"
* subject.type ^definition = "Tipo de recurso ao qual a referência é feita"
* subject.identifier ^short = "Referência lógica, quando a referência literal não é conhecida"
* subject.identifier ^definition = "Referência lógica, quando a referência literal não é conhecida"
* subject.display ^short = "Texto alternativo para o recurso"
* subject.display ^definition = "Texto alternativo para o recurso"
* context ^short = "Recurso Encounter ou Episode associado a este recurso"
* context only Reference(br-core-encounter or EpisodeOfCare)
* context ^definition = "Recurso Encounter ou Episode associado a este recurso"
* effective[x] ^short = "Data ou intervalo na qual o medicamento foi ou será tomado"
* effective[x] ^definition = "Data ou intervalo na qual o medicamento foi ou será tomado"
* effective[x].id ^short = "Identificador único para referenciação cruzada"
* effective[x].id ^definition = "Identificador único para referenciação cruzada"
//* effective[x].extension[data-absent-reason] ^short = "Se não há data, por que não há data?"
//* effective[x].extension[data-absent-reason] ^definition = "Se não há data, por que não há data?"
//* effective[x].extension[data-absent-reason] ^binding.description = "Usado para especificar porque o conteúdo da data não foi informado"
//* effective[x].extension[data-absent-reason] ^binding.strength = #required
//* effective[x].extension[data-absent-reason] ^binding.valueSet = http://hl7.org/fhir/ValueSet/data-absent-reason
* effectiveDateTime ^short = "Data ou intervalo na qual o medicamento foi ou será tomado"
* effectiveDateTime ^definition = "Data ou intervalo na qual o medicamento foi ou será tomado"
* effectivePeriod ^short = "Data ou intervalo na qual o medicamento foi ou será tomado"
* effectivePeriod ^definition = "Data ou intervalo na qual o medicamento foi ou será tomado"
* dateAsserted ^short = "Quando a declaração de medicação foi estabelecida" 
* dateAsserted ^definition = "Quando a declaração de medicação foi estabelecida"
* informationSource ^short = "Referência à pessoa ou organização que forneceu as informações sobre esta administração de medicamento"
* informationSource ^definition = "Referência à pessoa ou organização que forneceu as informações sobre esta administração de medicamento"
//* informationSource only Reference(br-core-patient or br-core-practitioner or br-core-practitionerrole or br-core-relatedperson or br-core-organization)
* derivedFrom ^short = "Referência a um recurso com informações de suporte adicionais"
* derivedFrom ^definition = "Referência a um recurso com informações de suporte adicionais"
* derivedFrom only Reference(Resource)
* reasonCode ^short = "Razão pela qual o medicamento está sendo ou foi tomado"
* reasonCode ^definition = "Razão pela qual o medicamento está sendo ou foi tomado"
* reasonReference ^short = "Condição ou observação que apoia a tomada deste medicamento"
* reasonReference ^definition = "Condição ou observação que apoia a tomada deste medicamento"
* reasonReference only Reference(br-core-condition or br-core-observationresults or br-core-diagnosticreport)
* note ^short = "Informações adicionais sobre essa declaração"
* note ^definition = "Informações adicionais sobre essa declaração"
* dosage ^short = "Detalhes sobre a administração do medicamento"
* dosage ^definition = "Detalhes sobre a administração do medicamento"
* dosage.id ^short = "Identificador único para referenciação cruzada"
* dosage.id ^definition = "Identificador único para referenciação cruzada"
* dosage.extension ^short = "Extensões adicionais que não fazem parte do modelo de dados básico"
* dosage.extension ^definition = "Extensões adicionais que não fazem parte do modelo de dados básico" 
* dosage.modifierExtension ^short = "Extensões adicionais que não podem ser ignoradas, mesmo que não reconhecidas"
* dosage.modifierExtension ^definition = "Extensões adicionais que não podem ser ignoradas, mesmo que não reconhecidas"
* dosage.sequence ^short = "A ordem das instruções de dosagem"
* dosage.sequence ^definition = "A ordem das instruções de dosagem"
* dosage.text ^short = "Instruções de dosagem em texto livre"
* dosage.text ^definition = "Instruções de dosagem em texto livre"
* dosage.additionalInstruction ^short = "Informações auxiliares ou advertências ao paciente"
* dosage.additionalInstruction ^definition = "Informações auxiliares ou advertências ao paciente"
* dosage.patientInstruction ^short = "Instruções orientadas ao paciente ou consumidor"
* dosage.patientInstruction ^definition = "Instruções orientadas ao paciente ou consumidor"
* dosage.timing ^short = "Quando o medicamento deve ser administrado"
* dosage.timing ^definition = "Quando o medicamento deve ser administrado"
* dosage.asNeeded[x] ^short = "Tomar \"conforme necessário\" (para x)" 
* dosage.asNeeded[x] ^definition = "Tomar \"conforme necessário\" (para x)" 
* dosage.site ^short = "Local no corpo onde deve ser administrado o medicamento"
* dosage.site ^definition = "Local no corpo onde deve ser administrado o medicamento"
* dosage.route ^short = "Rota de administração"
* dosage.route ^definition = "Rota de administração"
* dosage.method ^short = "Método de administração"
* dosage.method ^definition = "Método de administração"
* dosage.doseAndRate ^short = "Quantidade de medicamento administrado"
* dosage.doseAndRate ^definition = "Quantidade de medicamento administrado"
* dosage.doseAndRate.id ^short = "Identificador único para referenciação cruzada"
* dosage.doseAndRate.id ^definition = "Identificador único para referenciação cruzada"
* dosage.doseAndRate.extension ^short = "Extensões adicionais que não fazem parte do modelo de dados básico"
* dosage.doseAndRate.extension ^definition = "Extensões adicionais que não fazem parte do modelo de dados básico" 
* dosage.doseAndRate.type ^short = "O tipo de dose especificado"
* dosage.doseAndRate.type ^definition = "O tipo de dose especificado"
* dosage.doseAndRate.dose[x] ^short = "Quantidade de medicamento por dose"
* dosage.doseAndRate.dose[x] ^definition = "Quantidade de medicamento por dose"
* dosage.doseAndRate.rate[x] ^short = "Quantidade de medicamento por unidade de tempo"
* dosage.doseAndRate.rate[x] ^definition = "Quantidade de medicamento por unidade de tempo"
* dosage.maxDosePerPeriod ^short = "Limite máximo de medicamento por unidade de tempo"
* dosage.maxDosePerPeriod ^definition = "Limite máximo de medicamento por unidade de tempo"
* dosage.maxDosePerAdministration ^short = "Limite máximo de medicamento por administração"
* dosage.maxDosePerAdministration ^definition = "Limite máximo de medicamento por administração"
* dosage.maxDosePerLifetime ^short = "Limite máximo de medicamento por tempo de vida do paciente"
* dosage.maxDosePerLifetime ^definition = "Limite máximo de medicamento por tempo de vida do paciente"