Profile: BRCoreRegistroAtendimentoClinico
Parent: br-core-composition
Id: br-core-registroatendimentoclinico
Title: "br-core-registroatendimentoclinico"
Description: "Esse perfil restringe o perfil [br-core-composition](https://br-core/saude.gov.br/fhir/StructureDefinition/br-core-composition.html) para especificar um documento clínico, o registro de atendimento clínico, definido pela [PORTARIA Nº 234, DE 18 DE JULHO DE 2022](https://www.cosemssp.org.br/wp-content/uploads/2022/07/PORTARIA-No-234-DE-18-DE-JULHO-DE-2022-PORTARIA-No-234-DE-18-DE-JULHO-DE-2022-DOU-Imprensa-Nacional.pdf), que institui o Modelo de Informação (MI) Registro de Atendimento Clínico (RAC). Este modelo compreende um conjunto essencial de elementos e dados administrativos e clínicos que fornecem um instantâneo (snapshot) das informações de uma consulta realizada a um indivíduo no âmbito da atenção básica, especializada ou domiciliar (atendimento diário). Apresenta informações relacionadas ao acompanhamento do indivíduo como medições, observações, diagnósticos e/ou problemas, exames, procedimentos, pequenas cirurgias e desfecho."

//Slicing
* section ^slicing.discriminator.type = #profile
* section ^slicing.discriminator.path = "code"
* section ^slicing.rules = #open
* section ^short = "Seções do sumário de alta"
* section ^definition = "Seções do sumário de alta"
* section contains
    diagnosticosAvaliados 1..* and
    procedimentosRealizados 0..1 and
    sinaisVitais 0..1 and
    historiaObstetrica 0..1 and
    aleitamentoMaterno 0..1 and 
    historiaSocial 0..1 and
    alergiasIntolerancias 0..1 and
    medicamentos 0..1 and
    planoCuidados 0..1 and
    capacidadeFuncional 0..1

// Section dignosticosAvaliados
* section[diagnosticosAvaliados] ^short = "Seção de Resumo de Diagnósticos Avaliados"
* section[diagnosticosAvaliados] ^definition = "Seção de Resumo de Diagnósticos Admissão"
* section[diagnosticosAvaliados].id ^short = "Identificador exclusivo para referência entre elementos"
* section[diagnosticosAvaliados].id ^definition = "Identificador exclusivo para referência entre elementos"
* section[diagnosticosAvaliados].extension ^short = "Conteúdo adicional definido por implementações"
* section[diagnosticosAvaliados].extension ^definition = "Conteúdo adicional definido por implementações" 
* section[diagnosticosAvaliados].modifierExtension ^short = "Extensões que não podem ser ignoradas mesmo que não sejam reconhecidas"
* section[diagnosticosAvaliados].modifierExtension ^definition = "Extensões que não podem ser ignoradas mesmo que não sejam reconhecidas"
* section[diagnosticosAvaliados].title ^short = "Título da seção - Fixo em 'Diagnósticos Avaliados'"
* section[diagnosticosAvaliados].title ^definition = "Título da seção - Fixo em 'Diagnósticos Avaliados'"
* section[diagnosticosAvaliados].code ^short = "Classificação da seção da Composition/Document"
* section[diagnosticosAvaliados].code ^definition = "Classificação da seção da Composition/Document"
* section[diagnosticosAvaliados].code.id ^short = "Identificador exclusivo para referência entre elementos"
* section[diagnosticosAvaliados].code.id ^definition = "Identificador exclusivo para referência entre elementos"
* section[diagnosticosAvaliados].code.extension ^short = "Conteúdo adicional definido por implementações"
* section[diagnosticosAvaliados].code.extension ^definition = "Conteúdo adicional definido por implementações"
* section[diagnosticosAvaliados].code.coding ^short = "Código definido por uma terminologia"
* section[diagnosticosAvaliados].code.coding ^definition = "Código definido por uma terminologia"
* section[diagnosticosAvaliados].code.coding.id ^short = "Identificador exclusivo para referência entre elementos"
* section[diagnosticosAvaliados].code.coding.id ^definition = "Identificador exclusivo para referência entre elementos"
* section[diagnosticosAvaliados].code.coding.extension ^short = "Conteúdo adicional definido por implementações"
* section[diagnosticosAvaliados].code.coding.extension ^definition = "Conteúdo adicional definido por implementações"
* section[diagnosticosAvaliados].code.coding.system ^short = "Identificador da terminologia"
* section[diagnosticosAvaliados].code.coding.system ^definition = "Identidade da terminologia"
* section[diagnosticosAvaliados].code.coding.system = $loinc
* section[diagnosticosAvaliados].code.coding.version ^short = "Versão da terminologia - se relevante"
* section[diagnosticosAvaliados].code.coding.version ^definition = "Versão da terminologia  - se relevante"
* section[diagnosticosAvaliados].code.coding.code ^short = "Código do conceito na sintaxe definida pela terminologia"
* section[diagnosticosAvaliados].code.coding.code ^definition = "Código do conceito na sintaxe definida pela terminologia - fixo em loinc#42347-5 'Admission Diagnosis'"
* section[diagnosticosAvaliados].code.coding.code = #57852-6 
* section[diagnosticosAvaliados].code.coding.display ^short = "Descrição conforme definido pela terminologia"
* section[diagnosticosAvaliados].code.coding.display ^definition = "Representação definida pela terminologia"
* section[diagnosticosAvaliados].code.coding.display = "Problem List"
* section[diagnosticosAvaliados].code.coding.userSelected ^short = "Se esta codificação foi escolhida diretamente pelo usuário"
* section[diagnosticosAvaliados].code.coding.userSelected ^definition = "Se esta codificação foi escolhida diretamente pelo usuário"
* section[diagnosticosAvaliados].code.text ^short = "Representação em texto do conceito"
* section[diagnosticosAvaliados].code.text ^definition = "Representação em texto do conceito"
* section[diagnosticosAvaliados].author ^short = "Quem/o quê foi o autor desta seção"
* section[diagnosticosAvaliados].author ^definition = "Quem/o quê foi o autor desta seção"
* section[diagnosticosAvaliados].author only Reference(br-core-practitioner or br-core-practitionerrole or Device or br-core-patient or br-core-relatedperson or br-core-organization)
* section[diagnosticosAvaliados].focus ^short = "Ordem dos itens nas section.entry"
* section[diagnosticosAvaliados].focus ^definition = "Ordem dos itens nas section.entry"
* section[diagnosticosAvaliados].text ^short = "Resumo de texto da seção"
* section[diagnosticosAvaliados].text ^definition = "Resumo de texto da seção"
* section[diagnosticosAvaliados].mode ^short = "Método de processamento da seção"
* section[diagnosticosAvaliados].mode ^definition = "Método de processamento da seção"
* section[diagnosticosAvaliados].orderedBy ^short = "Ordem dos elementos na seção 'entry'"
* section[diagnosticosAvaliados].orderedBy ^definition = "Ordem dos elementos na seção 'entry'"
* section[diagnosticosAvaliados].entry ^short = "Diagnósticos avaliados relevantes para o sumário internacional do paciente"
* section[diagnosticosAvaliados].entry ^definition = "Diagnósticos avaliados relevantes para o sumário internacional do paciente"
* section[diagnosticosAvaliados].entry only Reference(br-core-condition)

//Section procedimentosRealizados
* section[procedimentosRealizados] ^short = "Seção de Resumo de Procedimentos Realizados"
* section[procedimentosRealizados] ^definition = "Seção de Resumo de Procedimentos Realizados"
* section[procedimentosRealizados].id ^short = "Identificador exclusivo para referência entre elementos"
* section[procedimentosRealizados].id ^definition = "Identificador exclusivo para referência entre elementos"
* section[procedimentosRealizados].extension ^short = "Conteúdo adicional definido por implementações"
* section[procedimentosRealizados].extension ^definition = "Conteúdo adicional definido por implementações" 
* section[procedimentosRealizados].modifierExtension ^short = "Extensões que não podem ser ignoradas mesmo que não sejam reconhecidas"
* section[procedimentosRealizados].modifierExtension ^definition = "Extensões que não podem ser ignoradas mesmo que não sejam reconhecidas"
* section[procedimentosRealizados].title ^short = "Título da seção - Fixo em 'Procedimentos Realizados'"
* section[procedimentosRealizados].title ^definition = "Título da seção - Fixo em 'Procedimentos Realizados'"
* section[procedimentosRealizados].code ^short = "Classificação da seção da Composition/Document"
* section[procedimentosRealizados].code ^definition = "Classificação da seção da Composition/Document"
* section[procedimentosRealizados].code.id ^short = "Identificador exclusivo para referência entre elementos"
* section[procedimentosRealizados].code.id ^definition = "Identificador exclusivo para referência entre elementos"
* section[procedimentosRealizados].code.extension ^short = "Conteúdo adicional definido por implementações"
* section[procedimentosRealizados].code.extension ^definition = "Conteúdo adicional definido por implementações"
* section[procedimentosRealizados].code.coding ^short = "Código definido por uma terminologia"
* section[procedimentosRealizados].code.coding ^definition = "Código definido por uma terminologia"
* section[procedimentosRealizados].code.coding.id ^short = "Identificador exclusivo para referência entre elementos"
* section[procedimentosRealizados].code.coding.id ^definition = "Identificador exclusivo para referência entre elementos"
* section[procedimentosRealizados].code.coding.extension ^short = "Conteúdo adicional definido por implementações"
* section[procedimentosRealizados].code.coding.extension ^definition = "Conteúdo adicional definido por implementações"
* section[procedimentosRealizados].code.coding.system ^short = "Identificador da terminologia"
* section[procedimentosRealizados].code.coding.system ^definition = "Identidade da terminologia"
* section[procedimentosRealizados].code.coding.system = $loinc
* section[procedimentosRealizados].code.coding.version ^short = "Versão da terminologia - se relevante"
* section[procedimentosRealizados].code.coding.version ^definition = "Versão da terminologia  - se relevante"
* section[procedimentosRealizados].code.coding.code ^short = "Código do conceito na sintaxe definida pela terminologia"
* section[procedimentosRealizados].code.coding.code ^definition = "Código do conceito na sintaxe definida pela terminologia - fixo em loinc#42347-5 'Admission Diagnosis'"
* section[procedimentosRealizados].code.coding.code = #47519-4
* section[procedimentosRealizados].code.coding.display ^short = "Descrição conforme definido pela terminologia"
* section[procedimentosRealizados].code.coding.display ^definition = "Representação definida pela terminologia"
* section[procedimentosRealizados].code.coding.display = "History of Procedures Document"
* section[procedimentosRealizados].code.coding.userSelected ^short = "Se esta codificação foi escolhida diretamente pelo usuário"
* section[procedimentosRealizados].code.coding.userSelected ^definition = "Se esta codificação foi escolhida diretamente pelo usuário"
* section[procedimentosRealizados].code.text ^short = "Representação em texto do conceito"
* section[procedimentosRealizados].code.text ^definition = "Representação em texto do conceito"
* section[procedimentosRealizados].author ^short = "Quem/o quê foi o autor desta seção"
* section[procedimentosRealizados].author ^definition = "Quem/o quê foi o autor desta seção"
* section[procedimentosRealizados].focus ^short = "Ordem dos itens nas section.entry"
* section[procedimentosRealizados].focus ^definition = "Ordem dos itens nas section.entry"
* section[procedimentosRealizados].text ^short = "Resumo de texto da seção"
* section[procedimentosRealizados].text ^definition = "Resumo de texto da seção"
* section[procedimentosRealizados].mode ^short = "Método de processamento da seção"
* section[procedimentosRealizados].mode ^definition = "Método de processamento da seção"
* section[procedimentosRealizados].orderedBy ^short = "Ordem dos elementos na seção 'entry'"
* section[procedimentosRealizados].orderedBy ^definition = "Ordem dos elementos na seção 'entry'"
* section[procedimentosRealizados].entry ^short = "Procedimentos realizados relevantes para o sumário internacional do paciente"
* section[procedimentosRealizados].entry ^definition = "Procedimentos realizados relevantes para o sumário internacional do paciente"
* section[procedimentosRealizados].entry only Reference(br-core-procedure)

//Section sinaisVitais
* section[sinaisVitais] ^short = "Seção de Resumo de Sinais Vitais"
* section[sinaisVitais] ^definition = "Seção de Resumo de Sinais Vitais"
* section[sinaisVitais].id ^short = "Identificador exclusivo para referência entre elementos"
* section[sinaisVitais].id ^definition = "Identificador exclusivo para referência entre elementos"
* section[sinaisVitais].extension ^short = "Conteúdo adicional definido por implementações"
* section[sinaisVitais].extension ^definition = "Conteúdo adicional definido por implementações" 
* section[sinaisVitais].modifierExtension ^short = "Extensões que não podem ser ignoradas mesmo que não sejam reconhecidas"
* section[sinaisVitais].modifierExtension ^definition = "Extensões que não podem ser ignoradas mesmo que não sejam reconhecidas"
* section[sinaisVitais].title ^short = "Título da seção - Fixo em 'Sinais Vitais'"
* section[sinaisVitais].title ^definition = "Título da seção - Fixo em 'Sinais Vitais'"
* section[sinaisVitais].code ^short = "Classificação da seção da Composition/Document"
* section[sinaisVitais].code ^definition = "Classificação da seção da Composition/Document"
* section[sinaisVitais].code.id ^short = "Identificador exclusivo para referência entre elementos"
* section[sinaisVitais].code.id ^definition = "Identificador exclusivo para referência entre elementos"
* section[sinaisVitais].code.extension ^short = "Conteúdo adicional definido por implementações"
* section[sinaisVitais].code.extension ^definition = "Conteúdo adicional definido por implementações"
* section[sinaisVitais].code.coding ^short = "Código definido por uma terminologia"
* section[sinaisVitais].code.coding ^definition = "Código definido por uma terminologia"
* section[sinaisVitais].code.coding.id ^short = "Identificador exclusivo para referência entre elementos"
* section[sinaisVitais].code.coding.id ^definition = "Identificador exclusivo para referência entre elementos"
* section[sinaisVitais].code.coding.extension ^short = "Conteúdo adicional definido por implementações"
* section[sinaisVitais].code.coding.extension ^definition = "Conteúdo adicional definido por implementações"
* section[sinaisVitais].code.coding.system ^short = "Identificador da terminologia"
* section[sinaisVitais].code.coding.system ^definition = "Identidade da terminologia"
* section[sinaisVitais].code.coding.system = $loinc
* section[sinaisVitais].code.coding.version ^short = "Versão da terminologia - se relevante"
* section[sinaisVitais].code.coding.version ^definition = "Versão da terminologia  - se relevante"
* section[sinaisVitais].code.coding.code ^short = "Código do conceito na sintaxe definida pela terminologia"
* section[sinaisVitais].code.coding.code ^definition = "Código do conceito na sintaxe definida pela terminologia - fixo em loinc#42347-5 'Admission Diagnosis'"
* section[sinaisVitais].code.coding.code = #8716-3
* section[sinaisVitais].code.coding.display ^short = "Descrição conforme definido pela terminologia"
* section[sinaisVitais].code.coding.display ^definition = "Representação definida pela terminologia"
* section[sinaisVitais].code.coding.display = "Vital Signs Document"
* section[sinaisVitais].code.coding.userSelected ^short = "Se esta codificação foi escolhida diretamente pelo usuário"
* section[sinaisVitais].code.coding.userSelected ^definition = "Se esta codificação foi escolhida diretamente pelo usuário"
* section[sinaisVitais].code.text ^short = "Representação em texto do conceito"
* section[sinaisVitais].code.text ^definition = "Representação em texto do conceito"
* section[sinaisVitais].author ^short = "Quem/o quê foi o autor desta seção"
* section[sinaisVitais].author ^definition = "Quem/o quê foi o autor desta seção"
* section[sinaisVitais].author only Reference(br-core-practitioner or br-core-practitionerrole or Device or br-core-patient or br-core-relatedperson or br-core-organization)
* section[sinaisVitais].focus ^short = "Ordem dos itens nas section.entry"
* section[sinaisVitais].focus ^definition = "Ordem dos itens nas section.entry"
* section[sinaisVitais].text ^short = "Resumo de texto da seção"
* section[sinaisVitais].text ^definition = "Resumo de texto da seção"
* section[sinaisVitais].mode ^short = "Método de processamento da seção"
* section[sinaisVitais].mode ^definition = "Método de processamento da seção"
* section[sinaisVitais].orderedBy ^short = "Ordem dos elementos na seção 'entry'"
* section[sinaisVitais].orderedBy ^definition = "Ordem dos elementos na seção 'entry'"
* section[sinaisVitais].entry ^short = "Sinais vitais relevantes para o sumário internacional do paciente"
* section[sinaisVitais].entry ^definition = "Sinais vitais relevantes para o sumário internacional do paciente"
* section[sinaisVitais].entry only Reference(br-core-vitalsigns)

//Section historiaObstetrica
* section[historiaObstetrica] ^short = "Seção de Resumo de História obstétrica"
* section[historiaObstetrica] ^definition = "Seção de Resumo de História obstétrica"
* section[historiaObstetrica].id ^short = "Identificador exclusivo para referência entre elementos"
* section[historiaObstetrica].id ^definition = "Identificador exclusivo para referência entre elementos"
* section[historiaObstetrica].extension ^short = "Conteúdo adicional definido por implementações"
* section[historiaObstetrica].extension ^definition = "Conteúdo adicional definido por implementações" 
* section[historiaObstetrica].modifierExtension ^short = "Extensões que não podem ser ignoradas mesmo que não sejam reconhecidas"
* section[historiaObstetrica].modifierExtension ^definition = "Extensões que não podem ser ignoradas mesmo que não sejam reconhecidas"
* section[historiaObstetrica].title ^short = "Título da seção - Fixo em 'História obstétrica'"
* section[historiaObstetrica].title ^definition = "Título da seção - Fixo em 'História obstétrica'"
* section[historiaObstetrica].code ^short = "Classificação da seção da Composition/Document"
* section[historiaObstetrica].code ^definition = "Classificação da seção da Composition/Document"
* section[historiaObstetrica].code.id ^short = "Identificador exclusivo para referência entre elementos"
* section[historiaObstetrica].code.id ^definition = "Identificador exclusivo para referência entre elementos"
* section[historiaObstetrica].code.extension ^short = "Conteúdo adicional definido por implementações"
* section[historiaObstetrica].code.extension ^definition = "Conteúdo adicional definido por implementações"
* section[historiaObstetrica].code.coding ^short = "Código definido por uma terminologia"
* section[historiaObstetrica].code.coding ^definition = "Código definido por uma terminologia"
* section[historiaObstetrica].code.coding.id ^short = "Identificador exclusivo para referência entre elementos"
* section[historiaObstetrica].code.coding.id ^definition = "Identificador exclusivo para referência entre elementos"
* section[historiaObstetrica].code.coding.extension ^short = "Conteúdo adicional definido por implementações"
* section[historiaObstetrica].code.coding.extension ^definition = "Conteúdo adicional definido por implementações"
* section[historiaObstetrica].code.coding.system ^short = "Identificador da terminologia"
* section[historiaObstetrica].code.coding.system ^definition = "Identidade da terminologia"
* section[historiaObstetrica].code.coding.system = $loinc
* section[historiaObstetrica].code.coding.version ^short = "Versão da terminologia - se relevante"
* section[historiaObstetrica].code.coding.version ^definition = "Versão da terminologia  - se relevante"
* section[historiaObstetrica].code.coding.code ^short = "Código do conceito na sintaxe definida pela terminologia"
* section[historiaObstetrica].code.coding.code ^definition = "Código do conceito na sintaxe definida pela terminologia - fixo em loinc#42347-5 'Admission Diagnosis'"
* section[historiaObstetrica].code.coding.code = #89213-3
* section[historiaObstetrica].code.coding.display ^short = "Descrição conforme definido pela terminologia"
* section[historiaObstetrica].code.coding.display ^definition = "Representação definida pela terminologia"
* section[historiaObstetrica].code.coding.display = "Obstetrics History and physical note Document"
* section[historiaObstetrica].code.coding.userSelected ^short = "Se esta codificação foi escolhida diretamente pelo usuário"
* section[historiaObstetrica].code.coding.userSelected ^definition = "Se esta codificação foi escolhida diretamente pelo usuário"
* section[historiaObstetrica].code.text ^short = "Representação em texto do conceito"
* section[historiaObstetrica].code.text ^definition = "Representação em texto do conceito"
* section[historiaObstetrica].author ^short = "Quem/o quê foi o autor desta seção"
* section[historiaObstetrica].author ^definition = "Quem/o quê foi o autor desta seção"
* section[historiaObstetrica].author only Reference(br-core-practitioner or br-core-practitionerrole or Device or br-core-patient or br-core-relatedperson or br-core-organization)
* section[historiaObstetrica].focus ^short = "Ordem dos itens nas section.entry"
* section[historiaObstetrica].focus ^definition = "Ordem dos itens nas section.entry"
* section[historiaObstetrica].text ^short = "Resumo de texto da seção"
* section[historiaObstetrica].text ^definition = "Resumo de texto da seção"
* section[historiaObstetrica].mode ^short = "Método de processamento da seção"
* section[historiaObstetrica].mode ^definition = "Método de processamento da seção"
* section[historiaObstetrica].orderedBy ^short = "Ordem dos elementos na seção 'entry'"
* section[historiaObstetrica].orderedBy ^definition = "Ordem dos elementos na seção 'entry'"
* section[historiaObstetrica].entry ^short = "História obstétrica relevantes para o sumário internacional do paciente"
* section[historiaObstetrica].entry ^definition = "História obstétrica relevantes para o sumário internacional do paciente"
* section[historiaObstetrica].entry only Reference(br-core-observationpregnancystatus or br-core-observationpregnancyoutcome)

//Section aleitamentoMaterno
* section[aleitamentoMaterno] ^short = "Seção de Resumo de Aleitamento Materno"
* section[aleitamentoMaterno] ^definition = "Seção de Resumo de Aleitamento Materno"
* section[aleitamentoMaterno].id ^short = "Identificador exclusivo para referência entre elementos"
* section[aleitamentoMaterno].id ^definition = "Identificador exclusivo para referência entre elementos"
* section[aleitamentoMaterno].extension ^short = "Conteúdo adicional definido por implementações"
* section[aleitamentoMaterno].extension ^definition = "Conteúdo adicional definido por implementações" 
* section[aleitamentoMaterno].modifierExtension ^short = "Extensões que não podem ser ignoradas mesmo que não sejam reconhecidas"
* section[aleitamentoMaterno].modifierExtension ^definition = "Extensões que não podem ser ignoradas mesmo que não sejam reconhecidas"
* section[aleitamentoMaterno].title ^short = "Título da seção - Fixo em 'Aleitamento Materno'"
* section[aleitamentoMaterno].title ^definition = "Título da seção - Fixo em 'Aleitamento Materno'"
* section[aleitamentoMaterno].code ^short = "Classificação da seção da Composition/Document"
* section[aleitamentoMaterno].code ^definition = "Classificação da seção da Composition/Document"
* section[aleitamentoMaterno].code.id ^short = "Identificador exclusivo para referência entre elementos"
* section[aleitamentoMaterno].code.id ^definition = "Identificador exclusivo para referência entre elementos"
* section[aleitamentoMaterno].code.extension ^short = "Conteúdo adicional definido por implementações"
* section[aleitamentoMaterno].code.extension ^definition = "Conteúdo adicional definido por implementações"
* section[aleitamentoMaterno].code.coding ^short = "Código definido por uma terminologia"
* section[aleitamentoMaterno].code.coding ^definition = "Código definido por uma terminologia"
* section[aleitamentoMaterno].code.coding.id ^short = "Identificador exclusivo para referência entre elementos"
* section[aleitamentoMaterno].code.coding.id ^definition = "Identificador exclusivo para referência entre elementos"
* section[aleitamentoMaterno].code.coding.extension ^short = "Conteúdo adicional definido por implementações"
* section[aleitamentoMaterno].code.coding.extension ^definition = "Conteúdo adicional definido por implementações"
* section[aleitamentoMaterno].code.coding.system ^short = "Identificador da terminologia"
* section[aleitamentoMaterno].code.coding.system ^definition = "Identidade da terminologia"
* section[aleitamentoMaterno].code.coding.system = $loinc
* section[aleitamentoMaterno].code.coding.version ^short = "Versão da terminologia - se relevante"
* section[aleitamentoMaterno].code.coding.version ^definition = "Versão da terminologia  - se relevante"
* section[aleitamentoMaterno].code.coding.code ^short = "Código do conceito na sintaxe definida pela terminologia"
* section[aleitamentoMaterno].code.coding.code ^definition = "Código do conceito na sintaxe definida pela terminologia - fixo em loinc#42347-5 'Admission Diagnosis'"
* section[aleitamentoMaterno].code.coding.code = #63895-7
* section[aleitamentoMaterno].code.coding.display ^short = "Descrição conforme definido pela terminologia"
* section[aleitamentoMaterno].code.coding.display ^definition = "Representação definida pela terminologia"
* section[aleitamentoMaterno].code.coding.display = "Breastfeeding status Document"
* section[aleitamentoMaterno].code.coding.userSelected ^short = "Se esta codificação foi escolhida diretamente pelo usuário"
* section[aleitamentoMaterno].code.coding.userSelected ^definition = "Se esta codificação foi escolhida diretamente pelo usuário"
* section[aleitamentoMaterno].code.text ^short = "Representação em texto do conceito"
* section[aleitamentoMaterno].code.text ^definition = "Representação em texto do conceito"
* section[aleitamentoMaterno].author ^short = "Quem/o quê foi o autor desta seção"
* section[aleitamentoMaterno].author ^definition = "Quem/o quê foi o autor desta seção"
* section[aleitamentoMaterno].author only Reference(br-core-practitioner or br-core-practitionerrole or Device or br-core-patient or br-core-relatedperson or br-core-organization)
* section[aleitamentoMaterno].focus ^short = "Ordem dos itens nas section.entry"
* section[aleitamentoMaterno].focus ^definition = "Ordem dos itens nas section.entry"
* section[aleitamentoMaterno].text ^short = "Resumo de texto da seção"
* section[aleitamentoMaterno].text ^definition = "Resumo de texto da seção"
* section[aleitamentoMaterno].mode ^short = "Método de processamento da seção"
* section[aleitamentoMaterno].mode ^definition = "Método de processamento da seção"
* section[aleitamentoMaterno].orderedBy ^short = "Ordem dos elementos na seção 'entry'"
* section[aleitamentoMaterno].orderedBy ^definition = "Ordem dos elementos na seção 'entry'"
* section[aleitamentoMaterno].entry ^short = "Aleitamento materno para o sumário internacional do paciente"
* section[aleitamentoMaterno].entry ^definition = "Aleitamento materno relevantes para o sumário internacional do paciente"
* section[aleitamentoMaterno].entry only Reference(br-core-observationbreastfeedingstatus)

//Section historiaSocial
* section[historiaSocial] ^short = "Seção de Resumo de História Social"
* section[historiaSocial] ^definition = "Seção de Resumo de História Social"
* section[historiaSocial].id ^short = "Identificador exclusivo para referência entre elementos"
* section[historiaSocial].id ^definition = "Identificador exclusivo para referência entre elementos"
* section[historiaSocial].extension ^short = "Conteúdo adicional definido por implementações"
* section[historiaSocial].extension ^definition = "Conteúdo adicional definido por implementações" 
* section[historiaSocial].modifierExtension ^short = "Extensões que não podem ser ignoradas mesmo que não sejam reconhecidas"
* section[historiaSocial].modifierExtension ^definition = "Extensões que não podem ser ignoradas mesmo que não sejam reconhecidas"
* section[historiaSocial].title ^short = "Título da seção - Fixo em 'História Social'"
* section[historiaSocial].title ^definition = "Título da seção - Fixo em 'História Social'"
* section[historiaSocial].code ^short = "Classificação da seção da Composition/Document"
* section[historiaSocial].code ^definition = "Classificação da seção da Composition/Document"
* section[historiaSocial].code.id ^short = "Identificador exclusivo para referência entre elementos"
* section[historiaSocial].code.id ^definition = "Identificador exclusivo para referência entre elementos"
* section[historiaSocial].code.extension ^short = "Conteúdo adicional definido por implementações"
* section[historiaSocial].code.extension ^definition = "Conteúdo adicional definido por implementações"
* section[historiaSocial].code.coding ^short = "Código definido por uma terminologia"
* section[historiaSocial].code.coding ^definition = "Código definido por uma terminologia"
* section[historiaSocial].code.coding.id ^short = "Identificador exclusivo para referência entre elementos"
* section[historiaSocial].code.coding.id ^definition = "Identificador exclusivo para referência entre elementos"
* section[historiaSocial].code.coding.extension ^short = "Conteúdo adicional definido por implementações"
* section[historiaSocial].code.coding.extension ^definition = "Conteúdo adicional definido por implementações"
* section[historiaSocial].code.coding.system ^short = "Identificador da terminologia"
* section[historiaSocial].code.coding.system ^definition = "Identidade da terminologia"
* section[historiaSocial].code.coding.system = $loinc
* section[historiaSocial].code.coding.version ^short = "Versão da terminologia - se relevante"
* section[historiaSocial].code.coding.version ^definition = "Versão da terminologia  - se relevante"
* section[historiaSocial].code.coding.code ^short = "Código do conceito na sintaxe definida pela terminologia"
* section[historiaSocial].code.coding.code ^definition = "Código do conceito na sintaxe definida pela terminologia - fixo em loinc#42347-5 'Admission Diagnosis'"
* section[historiaSocial].code.coding.code = #29762-2
* section[historiaSocial].code.coding.display ^short = "Descrição conforme definido pela terminologia"
* section[historiaSocial].code.coding.display ^definition = "Representação definida pela terminologia"
* section[historiaSocial].code.coding.display = "Social history Narrative Document"
* section[historiaSocial].code.coding.userSelected ^short = "Se esta codificação foi escolhida diretamente pelo usuário"
* section[historiaSocial].code.coding.userSelected ^definition = "Se esta codificação foi escolhida diretamente pelo usuário"
* section[historiaSocial].code.text ^short = "Representação em texto do conceito"
* section[historiaSocial].code.text ^definition = "Representação em texto do conceito"
* section[historiaSocial].author ^short = "Quem/o quê foi o autor desta seção"
* section[historiaSocial].author ^definition = "Quem/o quê foi o autor desta seção"
* section[historiaSocial].author only Reference(br-core-practitioner or br-core-practitionerrole or Device or br-core-patient or br-core-relatedperson or br-core-organization)
* section[historiaSocial].focus ^short = "Ordem dos itens nas section.entry"
* section[historiaSocial].focus ^definition = "Ordem dos itens nas section.entry"
* section[historiaSocial].text ^short = "Resumo de texto da seção"
* section[historiaSocial].text ^definition = "Resumo de texto da seção"
* section[historiaSocial].mode ^short = "Método de processamento da seção"
* section[historiaSocial].mode ^definition = "Método de processamento da seção"
* section[historiaSocial].orderedBy ^short = "Ordem dos elementos na seção 'entry'"
* section[historiaSocial].orderedBy ^definition = "Ordem dos elementos na seção 'entry'"
* section[historiaSocial].entry ^short = "História social relevantes para o sumário internacional do paciente"
* section[historiaSocial].entry ^definition = "História social relevantes para o sumário internacional do paciente"
* section[historiaSocial].entry only Reference(br-core-observationalcoholuse or br-core-observationtobaccouse) 

//Section alergiasIntolerancias
* section[alergiasIntolerancias] ^short = "Seção de Resumo de Alergias e Intolerâncias"
* section[alergiasIntolerancias] ^definition = "Seção de Resumo de Alergias e Intolerâncias"
* section[alergiasIntolerancias].id ^short = "Identificador exclusivo para referência entre elementos"
* section[alergiasIntolerancias].id ^definition = "Identificador exclusivo para referência entre elementos"
* section[alergiasIntolerancias].extension ^short = "Conteúdo adicional definido por implementações"
* section[alergiasIntolerancias].extension ^definition = "Conteúdo adicional definido por implementações" 
* section[alergiasIntolerancias].modifierExtension ^short = "Extensões que não podem ser ignoradas mesmo que não sejam reconhecidas"
* section[alergiasIntolerancias].modifierExtension ^definition = "Extensões que não podem ser ignoradas mesmo que não sejam reconhecidas"
* section[alergiasIntolerancias].title ^short = "Título da seção - Fixo em 'Alergias e Intolerâncias'"
* section[alergiasIntolerancias].title ^definition = "Título da seção - Fixo em 'Alergias e Intolerâncias'"
* section[alergiasIntolerancias].code ^short = "Classificação da seção da Composition/Document"
* section[alergiasIntolerancias].code ^definition = "Classificação da seção da Composition/Document"
* section[alergiasIntolerancias].code.id ^short = "Identificador exclusivo para referência entre elementos"
* section[alergiasIntolerancias].code.id ^definition = "Identificador exclusivo para referência entre elementos"
* section[alergiasIntolerancias].code.extension ^short = "Conteúdo adicional definido por implementações"
* section[alergiasIntolerancias].code.extension ^definition = "Conteúdo adicional definido por implementações"
* section[alergiasIntolerancias].code.coding ^short = "Código definido por uma terminologia"
* section[alergiasIntolerancias].code.coding ^definition = "Código definido por uma terminologia"
* section[alergiasIntolerancias].code.coding.id ^short = "Identificador exclusivo para referência entre elementos"
* section[alergiasIntolerancias].code.coding.id ^definition = "Identificador exclusivo para referência entre elementos"
* section[alergiasIntolerancias].code.coding.extension ^short = "Conteúdo adicional definido por implementações"
* section[alergiasIntolerancias].code.coding.extension ^definition = "Conteúdo adicional definido por implementações"
* section[alergiasIntolerancias].code.coding.system ^short = "Identificador da terminologia"
* section[alergiasIntolerancias].code.coding.system ^definition = "Identidade da terminologia"
* section[alergiasIntolerancias].code.coding.system = $loinc
* section[alergiasIntolerancias].code.coding.version ^short = "Versão da terminologia - se relevante"
* section[alergiasIntolerancias].code.coding.version ^definition = "Versão da terminologia  - se relevante"
* section[alergiasIntolerancias].code.coding.code ^short = "Código do conceito na sintaxe definida pela terminologia"
* section[alergiasIntolerancias].code.coding.code ^definition = "Código do conceito na sintaxe definida pela terminologia - fixo em loinc#42347-5 'Admission Diagnosis'"
* section[alergiasIntolerancias].code.coding.code = #48765-2
* section[alergiasIntolerancias].code.coding.display ^short = "Descrição conforme definido pela terminologia"
* section[alergiasIntolerancias].code.coding.display ^definition = "Representação definida pela terminologia"
* section[alergiasIntolerancias].code.coding.display = "Allergies and adverse reactions Document"
* section[alergiasIntolerancias].code.coding.userSelected ^short = "Se esta codificação foi escolhida diretamente pelo usuário"
* section[alergiasIntolerancias].code.coding.userSelected ^definition = "Se esta codificação foi escolhida diretamente pelo usuário"
* section[alergiasIntolerancias].code.text ^short = "Representação em texto do conceito"
* section[alergiasIntolerancias].code.text ^definition = "Representação em texto do conceito"
* section[alergiasIntolerancias].author ^short = "Quem/o quê foi o autor desta seção"
* section[alergiasIntolerancias].author ^definition = "Quem/o quê foi o autor desta seção"
* section[alergiasIntolerancias].author only Reference(br-core-practitioner or br-core-practitionerrole or Device or br-core-patient or br-core-relatedperson or br-core-organization)
* section[alergiasIntolerancias].focus ^short = "Ordem dos itens nas section.entry"
* section[alergiasIntolerancias].focus ^definition = "Ordem dos itens nas section.entry"
* section[alergiasIntolerancias].text ^short = "Resumo de texto da seção"
* section[alergiasIntolerancias].text ^definition = "Resumo de texto da seção"
* section[alergiasIntolerancias].mode ^short = "Método de processamento da seção"
* section[alergiasIntolerancias].mode ^definition = "Método de processamento da seção"
* section[alergiasIntolerancias].orderedBy ^short = "Ordem dos elementos na seção 'entry'"
* section[alergiasIntolerancias].orderedBy ^definition = "Ordem dos elementos na seção 'entry'"
* section[alergiasIntolerancias].entry ^short = "Alergias e intolerâncias relevantes para o sumário internacional do paciente"
* section[alergiasIntolerancias].entry ^definition = "Alergias e intolerâncias relevantes para o sumário internacional do paciente"
* section[alergiasIntolerancias].entry only Reference(br-core-allergyintolerance)

//Section medicamentos
* section[medicamentos] ^short = "Seção de Resumo de Medicamentos"
* section[medicamentos] ^definition = "Seção de Resumo de Medicamentos"
* section[medicamentos].id ^short = "Identificador exclusivo para referência entre elementos"
* section[medicamentos].id ^definition = "Identificador exclusivo para referência entre elementos"
* section[medicamentos].extension ^short = "Conteúdo adicional definido por implementações"
* section[medicamentos].extension ^definition = "Conteúdo adicional definido por implementações" 
* section[medicamentos].modifierExtension ^short = "Extensões que não podem ser ignoradas mesmo que não sejam reconhecidas"
* section[medicamentos].modifierExtension ^definition = "Extensões que não podem ser ignoradas mesmo que não sejam reconhecidas"
* section[medicamentos].title ^short = "Título da seção - Fixo em 'Medicamentos'"
* section[medicamentos].title ^definition = "Título da seção - Fixo em 'Medicamentos'"
* section[medicamentos].code ^short = "Classificação da seção da Composition/Document"
* section[medicamentos].code ^definition = "Classificação da seção da Composition/Document"
* section[medicamentos].code.id ^short = "Identificador exclusivo para referência entre elementos"
* section[medicamentos].code.id ^definition = "Identificador exclusivo para referência entre elementos"
* section[medicamentos].code.extension ^short = "Conteúdo adicional definido por implementações"
* section[medicamentos].code.extension ^definition = "Conteúdo adicional definido por implementações"
* section[medicamentos].code.coding ^short = "Código definido por uma terminologia"
* section[medicamentos].code.coding ^definition = "Código definido por uma terminologia"
* section[medicamentos].code.coding.id ^short = "Identificador exclusivo para referência entre elementos"
* section[medicamentos].code.coding.id ^definition = "Identificador exclusivo para referência entre elementos"
* section[medicamentos].code.coding.extension ^short = "Conteúdo adicional definido por implementações"
* section[medicamentos].code.coding.extension ^definition = "Conteúdo adicional definido por implementações"
* section[medicamentos].code.coding.system ^short = "Identificador da terminologia"
* section[medicamentos].code.coding.system ^definition = "Identidade da terminologia"
* section[medicamentos].code.coding.system = $loinc
* section[medicamentos].code.coding.version ^short = "Versão da terminologia - se relevante"
* section[medicamentos].code.coding.version ^definition = "Versão da terminologia  - se relevante"
* section[medicamentos].code.coding.code ^short = "Código do conceito na sintaxe definida pela terminologia"
* section[medicamentos].code.coding.code ^definition = "Código do conceito na sintaxe definida pela terminologia - fixo em loinc#42347-5 'Admission Diagnosis'"
* section[medicamentos].code.coding.code = #52471-0
* section[medicamentos].code.coding.display ^short = "Descrição conforme definido pela terminologia"
* section[medicamentos].code.coding.display ^definition = "Representação definida pela terminologia"
* section[medicamentos].code.coding.display = "Medications Document"
* section[medicamentos].code.coding.userSelected ^short = "Se esta codificação foi escolhida diretamente pelo usuário"
* section[medicamentos].code.coding.userSelected ^definition = "Se esta codificação foi escolhida diretamente pelo usuário"
* section[medicamentos].code.text ^short = "Representação em texto do conceito"
* section[medicamentos].code.text ^definition = "Representação em texto do conceito"
* section[medicamentos].author ^short = "Quem/o quê foi o autor desta seção"
* section[medicamentos].author ^definition = "Quem/o quê foi o autor desta seção"
* section[medicamentos].author only Reference(br-core-practitioner or br-core-practitionerrole or Device or br-core-patient or br-core-relatedperson or br-core-organization)
* section[medicamentos].focus ^short = "Ordem dos itens nas section.entry"
* section[medicamentos].focus ^definition = "Ordem dos itens nas section.entry"
* section[medicamentos].text ^short = "Resumo de texto da seção"
* section[medicamentos].text ^definition = "Resumo de texto da seção"
* section[medicamentos].mode ^short = "Método de processamento da seção"
* section[medicamentos].mode ^definition = "Método de processamento da seção"
* section[medicamentos].orderedBy ^short = "Ordem dos elementos na seção 'entry'"
* section[medicamentos].orderedBy ^definition = "Ordem dos elementos na seção 'entry'"
* section[medicamentos].entry ^short = "Medicamentos relevantes para o sumário internacional do paciente"
* section[medicamentos].entry ^definition = "Medicamentos relevantes para o sumário internacional do paciente"
* section[medicamentos].entry only Reference(br-core-medicationstatement or br-core-medicationrequest or br-core-medicationadministration or br-core-medicationdispense or DocumentReference)

//Section planoCuidados
* section[planoCuidados] ^short = "Seção de Resumo de Planos de Cuidado"
* section[planoCuidados] ^definition = "Seção de Resumo de Planos de Cuidado"
* section[planoCuidados].id ^short = "Identificador exclusivo para referência entre elementos"
* section[planoCuidados].id ^definition = "Identificador exclusivo para referência entre elementos"
* section[planoCuidados].extension ^short = "Conteúdo adicional definido por implementações"
* section[planoCuidados].extension ^definition = "Conteúdo adicional definido por implementações" 
* section[planoCuidados].modifierExtension ^short = "Extensões que não podem ser ignoradas mesmo que não sejam reconhecidas"
* section[planoCuidados].modifierExtension ^definition = "Extensões que não podem ser ignoradas mesmo que não sejam reconhecidas"
* section[planoCuidados].title ^short = "Título da seção - Fixo em 'Planos de Cuidado'"
* section[planoCuidados].title ^definition = "Título da seção - Fixo em 'Planos de Cuidado'"
* section[planoCuidados].code ^short = "Classificação da seção da Composition/Document"
* section[planoCuidados].code ^definition = "Classificação da seção da Composition/Document"
* section[planoCuidados].code.id ^short = "Identificador exclusivo para referência entre elementos"
* section[planoCuidados].code.id ^definition = "Identificador exclusivo para referência entre elementos"
* section[planoCuidados].code.extension ^short = "Conteúdo adicional definido por implementações"
* section[planoCuidados].code.extension ^definition = "Conteúdo adicional definido por implementações"
* section[planoCuidados].code.coding ^short = "Código definido por uma terminologia"
* section[planoCuidados].code.coding ^definition = "Código definido por uma terminologia"
* section[planoCuidados].code.coding.id ^short = "Identificador exclusivo para referência entre elementos"
* section[planoCuidados].code.coding.id ^definition = "Identificador exclusivo para referência entre elementos"
* section[planoCuidados].code.coding.extension ^short = "Conteúdo adicional definido por implementações"
* section[planoCuidados].code.coding.extension ^definition = "Conteúdo adicional definido por implementações"
* section[planoCuidados].code.coding.system ^short = "Identificador da terminologia"
* section[planoCuidados].code.coding.system ^definition = "Identidade da terminologia"
* section[planoCuidados].code.coding.system = $loinc
* section[planoCuidados].code.coding.version ^short = "Versão da terminologia - se relevante"
* section[planoCuidados].code.coding.version ^definition = "Versão da terminologia  - se relevante"
* section[planoCuidados].code.coding.code ^short = "Código do conceito na sintaxe definida pela terminologia"
* section[planoCuidados].code.coding.code ^definition = "Código do conceito na sintaxe definida pela terminologia - fixo em loinc#42347-5 'Admission Diagnosis'"
* section[planoCuidados].code.coding.code = #18776-5
* section[planoCuidados].code.coding.display ^short = "Descrição conforme definido pela terminologia"
* section[planoCuidados].code.coding.display ^definition = "Representação definida pela terminologia"
* section[planoCuidados].code.coding.display = "Plan of care note"
* section[planoCuidados].code.coding.userSelected ^short = "Se esta codificação foi escolhida diretamente pelo usuário"
* section[planoCuidados].code.coding.userSelected ^definition = "Se esta codificação foi escolhida diretamente pelo usuário"
* section[planoCuidados].code.text ^short = "Representação em texto do conceito"
* section[planoCuidados].code.text ^definition = "Representação em texto do conceito"
* section[planoCuidados].author ^short = "Quem/o quê foi o autor desta seção"
* section[planoCuidados].author ^definition = "Quem/o quê foi o autor desta seção"
* section[planoCuidados].focus ^short = "Ordem dos itens nas section.entry"
* section[planoCuidados].focus ^definition = "Ordem dos itens nas section.entry"
* section[planoCuidados].text ^short = "Resumo de texto da seção"
* section[planoCuidados].text ^definition = "Resumo de texto da seção"
* section[planoCuidados].mode ^short = "Método de processamento da seção"
* section[planoCuidados].mode ^definition = "Método de processamento da seção"
* section[planoCuidados].orderedBy ^short = "Ordem dos elementos na seção 'entry'"
* section[planoCuidados].orderedBy ^definition = "Ordem dos elementos na seção 'entry'"
* section[planoCuidados].entry ^short = "Planos de cuidado relevantes para o sumário internacional do paciente"
* section[planoCuidados].entry ^definition = "Planos de cuidado relevantes para o sumário internacional do paciente"
* section[planoCuidados].entry only Reference(br-core-careplan)

//Section capacidadeFuncional
* section[capacidadeFuncional] ^short = "Seção de Resumo de Capacidade Funcional"
* section[capacidadeFuncional] ^definition = "Seção de Resumo de Capacidade Funcional"
* section[capacidadeFuncional].id ^short = "Identificador exclusivo para referência entre elementos"
* section[capacidadeFuncional].id ^definition = "Identificador exclusivo para referência entre elementos"
* section[capacidadeFuncional].extension ^short = "Conteúdo adicional definido por implementações"
* section[capacidadeFuncional].extension ^definition = "Conteúdo adicional definido por implementações" 
* section[capacidadeFuncional].modifierExtension ^short = "Extensões que não podem ser ignoradas mesmo que não sejam reconhecidas"
* section[capacidadeFuncional].modifierExtension ^definition = "Extensões que não podem ser ignoradas mesmo que não sejam reconhecidas"
* section[capacidadeFuncional].title ^short = "Título da seção - Fixo em 'Capacidade Funcional'"
* section[capacidadeFuncional].title ^definition = "Título da seção - Fixo em 'Capacidade Funcional'"
* section[capacidadeFuncional].code ^short = "Classificação da seção da Composition/Document"
* section[capacidadeFuncional].code ^definition = "Classificação da seção da Composition/Document"
* section[capacidadeFuncional].code.id ^short = "Identificador exclusivo para referência entre elementos"
* section[capacidadeFuncional].code.id ^definition = "Identificador exclusivo para referência entre elementos"
* section[capacidadeFuncional].code.extension ^short = "Conteúdo adicional definido por implementações"
* section[capacidadeFuncional].code.extension ^definition = "Conteúdo adicional definido por implementações"
* section[capacidadeFuncional].code.coding ^short = "Código definido por uma terminologia"
* section[capacidadeFuncional].code.coding ^definition = "Código definido por uma terminologia"
* section[capacidadeFuncional].code.coding.id ^short = "Identificador exclusivo para referência entre elementos"
* section[capacidadeFuncional].code.coding.id ^definition = "Identificador exclusivo para referência entre elementos"
* section[capacidadeFuncional].code.coding.extension ^short = "Conteúdo adicional definido por implementações"
* section[capacidadeFuncional].code.coding.extension ^definition = "Conteúdo adicional definido por implementações"
* section[capacidadeFuncional].code.coding.system ^short = "Identificador da terminologia"
* section[capacidadeFuncional].code.coding.system ^definition = "Identidade da terminologia"
* section[capacidadeFuncional].code.coding.system = $loinc
* section[capacidadeFuncional].code.coding.version ^short = "Versão da terminologia - se relevante"
* section[capacidadeFuncional].code.coding.version ^definition = "Versão da terminologia  - se relevante"
* section[capacidadeFuncional].code.coding.code ^short = "Código do conceito na sintaxe definida pela terminologia"
* section[capacidadeFuncional].code.coding.code ^definition = "Código do conceito na sintaxe definida pela terminologia - fixo em loinc#42347-5 'Admission Diagnosis'"
* section[capacidadeFuncional].code.coding.code = #54522-8
* section[capacidadeFuncional].code.coding.display ^short = "Descrição conforme definido pela terminologia"
* section[capacidadeFuncional].code.coding.display ^definition = "Representação definida pela terminologia"
* section[capacidadeFuncional].code.coding.display = "Functional status"
* section[capacidadeFuncional].code.coding.userSelected ^short = "Se esta codificação foi escolhida diretamente pelo usuário"
* section[capacidadeFuncional].code.coding.userSelected ^definition = "Se esta codificação foi escolhida diretamente pelo usuário"
* section[capacidadeFuncional].code.text ^short = "Representação em texto do conceito"
* section[capacidadeFuncional].code.text ^definition = "Representação em texto do conceito"
* section[capacidadeFuncional].author ^short = "Quem/o quê foi o autor desta seção"
* section[capacidadeFuncional].author ^definition = "Quem/o quê foi o autor desta seção"
* section[capacidadeFuncional].focus ^short = "Ordem dos itens nas section.entry"
* section[capacidadeFuncional].focus ^definition = "Ordem dos itens nas section.entry"
* section[capacidadeFuncional].text ^short = "Resumo de texto da seção"
* section[capacidadeFuncional].text ^definition = "Resumo de texto da seção"
* section[capacidadeFuncional].mode ^short = "Método de processamento da seção"
* section[capacidadeFuncional].mode ^definition = "Método de processamento da seção"
* section[capacidadeFuncional].orderedBy ^short = "Ordem dos elementos na seção 'entry'"
* section[capacidadeFuncional].orderedBy ^definition = "Ordem dos elementos na seção 'entry'"
* section[capacidadeFuncional].entry ^short = "Capacidade funcional para o sumário internacional do paciente"
* section[capacidadeFuncional].entry ^definition = "Capacidade funcional relevantes para o sumário internacional do paciente"
* section[capacidadeFuncional].entry only Reference(br-core-capacidadefuncional)