Profile: br-core-relatedperson
Parent: RelatedPerson
Id: br-core-relatedperson
Description: "Este perfil"

* id ^short = "ID lógico deste artefato"
* id ^definition = "ID lógico deste artefato"
* meta ^short = "Metadados sobre o recurso"
* meta ^definition = "Metadados sobre o recurso"
* implicitRules ^short = "Um conjunto de regras sob as quais este conteúdo foi criado"
* implicitRules ^definition = "Um conjunto de regras sob as quais este conteúdo foi criado"
* language ^short = "Idioma do conteúdo do recurso"
* language ^definition = "Idioma do conteúdo do recurso"
* text ^short = "Resumo do texto do recurso, para interpretação humana"
* text ^definition = "Resumo do texto do recurso, para interpretação humana"
* contained ^short = "Recursos contidos"
* contained ^definition = "Recursos contidos"
* extension ^short = "Conteúdo adicional definido por implementações"
* extension ^definition = "Conteúdo adicional definido por implementações"
* modifierExtension ^short = "Extensões que não podem ser ignoradas"
* modifierExtension ^definition = "Extensões que não podem ser ignoradas"
* identifier ^short = "Identificador Externo"
* identifier ^definition = "Identificador Externo"
* active ^short = "Se o registro desta pessoa relacionada está em uso ativo"
* active ^definition = "Se o registro desta pessoa relacionada está em uso ativo"
* patient ^short = "O paciente com quem essa pessoa está relacionada"
* patient ^definition = "O paciente com quem essa pessoa está relacionada"
* patient only Reference(br-core-patient)
* relationship ^short = "A natureza do relacionamento"
* relationship ^definition = "A natureza do relacionamento"
* name ^short = "Um nome associado à pessoa"
* name ^definition = "Um nome associado à pessoa"
* telecom ^short = "Um detalhe de contato da pessoa"
* telecom ^definition = "Um detalhe de contato da pessoa"
* gender ^short = "masculino | feminino | outro | desconhecido"
* gender ^definition = "masculino | feminino | outro | desconhecido"
* birthDate ^short = "A data em que a pessoa relacionada nasceu"
* birthDate ^definition = "A data em que a pessoa relacionada nasceu"
* address ^short = "Endereço onde a pessoa relacionada pode ser contatada ou visitada"
* address ^definition = "Endereço onde a pessoa relacionada pode ser contatada ou visitada"
* photo ^short = "Imagem da pessoa"
* photo ^definition = "Imagem da pessoa"
* period ^short = "Período de tempo em que esta relação é considerada válida"
* period ^definition = "Período de tempo em que esta relação é considerada válida"
* communication ^short = "Uma linguagem que pode ser usada para se comunicar sobre a saúde do paciente"
* communication ^definition = "Uma linguagem que pode ser usada para se comunicar sobre a saúde do paciente"
* communication.language ^short = "A linguagem que pode ser usada para se comunicar com o paciente sobre sua saúde"
* communication.language ^definition = "A linguagem que pode ser usada para se comunicar com o paciente sobre sua saúde"
* communication.preferred ^short = "Language preference indicator"
* communication.preferred ^definition = "Language preference indicator"