Profile: BRCoreVitalSigns
Parent: http://hl7.org/fhir/StructureDefinition/vitalsigns
Id: br-core-vitalsigns
Description: "Este perfil é baseado no perfil [VitalSigns](http://hl7.org/fhir/R4/observation-vitalsigns.html) e define restrições adicionais no recurso Observation para representar Observation de sinais vitais. Ele especifica quais elementos principais, extensões, vocabulários e conjuntos de valores **DEVEM** estar presentes no recurso e restringe como os elementos são usados. "

* id ^short = "Identificador lógico deste artefato"
* id ^definition = "Identificador lógico deste artefato"
* meta ^short = "Metadados sobre o recurso"
* meta ^definition = "Metadados sobre o recurso" 
* implicitRules ^short = "Um conjunto de regras sob as quais este conteúdo foi criado"
* implicitRules ^definition = "Um conjunto de regras sob as quais este conteúdo foi criado"
* language ^short = "Idioma do recurso"
* language ^definition = "Idioma do recurso"
* text ^short = "Resumo do texto do recurso em linguagem natural"
* text ^definition = "Resumo do texto do recurso em linguagem natural"
* contained ^definition = "Recursos contidos no recurso"
* contained ^definition = "Recursos contidos no recurso"
* extension ^definition = "Extensões adicionais que não fazem parte do modelo base"
* extension ^definition = "Extensões adicionais que não fazem parte do modelo base"
* modifierExtension ^short = "Extensões adicionais que não podem ser ignoradas, mesmo que não reconhecidas"
* modifierExtension ^definition = "Extensões adicionais que não podem ser ignoradas, mesmo que não reconhecidas"
* identifier ^short = "Identificadores externos para este recurso"
* identifier ^definition = "Identificadores externos para este recurso"
* basedOn ^short = "Referência ao pedido ou ao plano de tratamento que gerou este recurso"
* basedOn ^definition = "Referência ao pedido ou ao plano de tratamento que gerou este recurso"
* basedOn only Reference(br-core-careplan or DeviceRequest or ImmunizationRecommendation or br-core-medicationrequest or NutritionOrder or br-core-servicerequest) 
* partOf ^short = "Referência ao evento do qual este recurso faz parte"
* partOf ^definition = "Referência ao evento do qual este recurso faz parte"
* partOf only Reference(br-core-medicationadministration or br-core-medicationdispense or br-core-medicationstatement or br-core-procedure or br-core-immunization or ImagingStudy)
* status ^short = "Status atual da observação"
* status ^definition = "active | completed | entered-in-error | intended | stopped | on-hold | unknown | not-taken"
* category ^short = "Categoria de alto nível da observação"
* category ^definition = "Categoria de alto nível da observação"
* category[VSCat] ^short = "Classificação do tipo de observação"
* category[VSCat] ^definition = "Classificação do tipo de observação"
* category[VSCat].id ^short = "Identificador exclusivo para referência entre elementos"
* category[VSCat].id ^definition = "Identificador exclusivo para referência entre elementos"
* category[VSCat].extension ^short = "Conteúdo adicional definido por implementações"
* category[VSCat].extension ^definition = "Conteúdo adicional definido por implementações"
* category[VSCat].coding ^short = "Código definido por uma terminologia"
* category[VSCat].coding ^definition = "Código definido por uma terminologia"
* category[VSCat].coding.id ^short = "Identificador exclusivo para referência entre elementos"
* category[VSCat].coding.id ^definition = "Identificador exclusivo para referência entre elementos"
* category[VSCat].coding.extension ^short = "Conteúdo adicional definido por implementações"
* category[VSCat].coding.extension ^definition = "Conteúdo adicional definido por implementações"
* category[VSCat].coding.system ^short = "Identidade do sistema de terminologia"
* category[VSCat].coding.system ^definition = "Identidade do sistema de terminologia"
* category[VSCat].coding.version ^short = "Versão do sistema, se relevante"
* category[VSCat].coding.version ^definition = "Versão do sistema, se relevante"
* category[VSCat].coding.code ^short = "Símbolo na sintaxe definida pelo sistema"
* category[VSCat].coding.code ^definition = "Símbolo na sintaxe definida pelo sistema"
* category[VSCat].coding.display ^short = "Representação definida pelo sistema"
* category[VSCat].coding.display ^definition = "Representação definida pelo sistema"
* category[VSCat].coding.userSelected ^short = "Se a codificação foi escolhida diretamente pelo usuário"
* category[VSCat].coding.userSelected ^definition = "Se a codificação foi escolhida diretamente pelo usuário"
* category[VSCat].text ^short = "Representação em texto simples do conceito"
* category[VSCat].text ^definition = "Representação em texto simples do conceito"
* code ^short = "Código definido pela sintaxe do sistema de terminologia"
* code ^definition = "Código definido pela sintaxe do sistema de terminologia"
* code from https://terminologia.saude.gov.br/fhir/ValueSet/BRSinaisVitais
* subject ^short = "Referência ao paciente desta observação"
* subject ^definition = "Referência ao paciente desta observação"
* subject only Reference(br-core-patient)
* focus ^short = "Referência à recursos associados"
* focus ^definition = "Referência à recursos associados"
* focus only Reference(Resource)
* encounter ^short = "Referência ao atendimento desta observação"
* encounter ^definition = "Referência ao atendimento desta observação"
* encounter only Reference(br-core-encounter)
* effective[x] ^short = "Tempo ou período de tempo clinicamente relevante para os sinais vitais"
* effective[x] ^definition = "Tempo ou período de tempo clinicamente relevante para os sinais vitais"
* issued ^short = "Data ou hora em que esta versão da observação ficou disponível"
* issued ^definition = "Data ou hora em que esta versão da observação ficou disponível"
* issued 1..1
* performer ^short = "O responsável pela captura da observação"
* performer ^definition = "O responsável pela captura da observação"
* performer only Reference(br-core-practitioner or br-core-practitionerrole or br-core-organization or CareTeam or br-core-patient or br-core-relatedperson)
* value[x] ^short = "Valor dos sinais vitais"
* value[x] ^definition = "Valor dos sinais vitais"
* value[x] 1..1
* dataAbsentReason ^short = "Por que o resultado não está disponível"
* dataAbsentReason ^definition = "Por que o resultado não está disponível"
* interpretation ^short = "Interpretação da observação"
* interpretation ^definition = "Interpretação da observação. Por exemplo: valor alto, baixo, normal"
* note ^short = "Comentários sobre a observação"
* note ^definition = "Comentários sobre a observação"
* bodySite ^short = "Local anatômico associado ao procedimento"
* bodySite ^definition = "Local anatômico associado ao procedimento"
* bodySite from http://hl7.org/fhir/ValueSet/body-site (preferred)
* method ^short = "Método utilizado para capturar o sinal vital"
* method ^definition = "Método utilizado para capturar o sinal vital"
* specimen ^short = "Referência à amostra associada nesta observação"
* specimen ^definition = "Referência à amostra associada nesta observação"
* specimen only Reference(br-core-specimen)
* device ^short = "Referência ao dispositivo (de medida) associado nesta observação"
* device ^definition = "Referência ao dispositivo (de medida) associado nesta observação"
* device only Reference(Device or DeviceMetric)
* referenceRange ^short = "Limites de referência"
* referenceRange ^definition = "Limites de referência"
* referenceRange.id ^short = "Identificador único para referência cruzada"
* referenceRange.id ^definition = "Identificador único para referência cruzada"
* referenceRange.extension ^short = "Extensões adicionais que não fazem parte do modelo de dados básico"
* referenceRange.extension ^definition = "Extensões adicionais que não fazem parte do modelo de dados básico" 
* referenceRange.modifierExtension ^short = "Extensões adicionais que não podem ser ignoradas, mesmo que não reconhecidas"
* referenceRange.modifierExtension ^definition = "Extensões adicionais que não podem ser ignoradas, mesmo que não reconhecidas"
* referenceRange.low ^short = "Limite inferior do intervalo de valores de referência"
* referenceRange.low ^definition = "Limite inferior do intervalo de valores de referência"
* referenceRange.high ^short = "Limite superior do intervalo de referência"
* referenceRange.high ^definition = "Limite superior do intervalo de referência"
* referenceRange.type ^short = "Qualificador do valor de referência"
* referenceRange.type ^definition = "Qualificador do valor de referência"
* referenceRange.appliesTo ^short = "População alvo do intervalo de referência"
* referenceRange.appliesTo ^definition = "População alvo do intervalo de referência"
* referenceRange.age ^short = "Faixa etária aplicável ao intervalo de referência"
* referenceRange.age ^definition = "Faixa etária aplicável ao intervalo de referência"
* referenceRange.text ^short = "Intervalo de referência em linguagen natural"
* referenceRange.text ^definition = "Intervalo de referência em linguagen natural"
* hasMember ^short = "Referências utilizadas para relatar componentes do painel de sinais vitais"
* hasMember ^definition = "Referências utilizadas para relatar componentes do painel de sinais vitais"
* hasMember only Reference(QuestionnaireResponse or MolecularSequence)
* derivedFrom ^short = "Referência à medições relacionadas a partir das quais esta observação foi realizada"
* derivedFrom ^definition = "Referência à medições relacionadas a partir das quais esta observação foi realizada"
* derivedFrom only Reference(DocumentReference or ImagingStudy or Media or QuestionnaireResponse or br-core-vitalsigns or MolecularSequence)
* component ^short = "Utilizado para relatar pressão sistólica e diastólica"
* component ^definition = "Utilizado para relatar pressão sistólica e diastólica"
* component.id ^short = "Identificador único para referência cruzada"
* component.id ^definition = "Identificador único para referência cruzada"
* component.extension ^short = "Extensões adicionais que não fazem parte do modelo de dados básico"
* component.extension ^definition = "Extensões adicionais que não fazem parte do modelo de dados básico" 
* component.modifierExtension ^short = "Extensões adicionais que não podem ser ignoradas, mesmo que não reconhecidas"
* component.modifierExtension ^definition = "Extensões adicionais que não podem ser ignoradas, mesmo que não reconhecidas"
* component.code ^short = "Tipo de observação de componente"
* component.code ^short = "Tipo de observação de componente"
* component.value[x] ^short = "O valor do sinal vital"
* component.value[x] ^definition = "O valor do sinal vital"
* component.dataAbsentReason ^short = "Por que o resultado do componente está faltando"
* component.dataAbsentReason ^definition = "Por que o resultado do componente está faltando"
* component.interpretation ^short = "Interpretação da observação"
* component.interpretation ^definition = "Interpretação da observação. Por exemplo: valor elevado"
* component.referenceRange ^short = "Valores de referência"
* component.referenceRange ^definition = "VValores de referência"