Profile: BRCoreHealthcareService
Parent: http://hl7.org/fhir/StructureDefinition/HealthcareService
Id: br-core-healthcareservice
Title: "br-core-healthcareservice"
Description: "Este perfil restringe o recurso [HealthcareService](https://hl7.org/fhir/R4/healthcareservice.html) que representa os detalhes de um serviço de saúde disponível em um local"

* id ^short = "Identificador lógico deste artefato"
* id ^definition = "Identificador lógico deste artefato"
* meta ^short = "Metadados sobre o recurso"
* meta ^definition = "Metadados sobre o recurso" 
* implicitRules ^short = "Um conjunto de regras sob as quais este conteúdo foi criado"
* implicitRules ^definition = "Um conjunto de regras sob as quais este conteúdo foi criado"
* language ^short = "Idioma do recurso"
* language ^definition = "Idioma do recurso"
* text ^short = "Resumo do texto do recurso em linguagem natural"
* text ^definition = "Resumo do texto do recurso em linguagem natural"
* contained ^short = "Recursos contidos no recurso"
* contained ^definition = "Recursos contidos no recurso"
* extension ^short = "Extensões adicionais que não fazem parte do modelo base"
* extension ^definition = "Extensões adicionais que não fazem parte do modelo base"
* modifierExtension ^short = "Extensões adicionais que não podem ser ignoradas, mesmo que não reconhecidas"
* modifierExtension ^definition = "Extensões adicionais que não podem ser ignoradas, mesmo que não reconhecidas"
* identifier ^short = "Identificadores deste recurso"
* identifier ^definition = "Identificadores deste recurso"
* active ^short = "Se este registro está em uso ativo"
* active ^definition = "Se este registro está em uso ativo"
* providedBy ^short = "Referência à organização que fornece este serviço"
* providedBy ^definition = "Referência à organização que fornece este serviço"
* category ^short = "Categoria de serviço"
* category ^definition = "Categoria de serviço"
* category from https://terminologia.saude.gov.br/fhir/ValueSet/BRTipoEstabelecimentoSaude	(preferred)  
* type ^short = "Tipo de serviço"
* type ^definition = "Tipo de serviço"
* type from https://terminologia.saude.gov.br/fhir/ValueSet/BRServicoEspecializado (preferred)
* specialty ^short = "Especialidades atendidas"
* specialty ^definition = "Especialidades atendidas"
* specialty from https://terminologia.saude.gov.br/fhir/ValueSet/BROcupacao (required)
* location ^short = "Referência aos locais onde o serviço pode ser prestado"
* location ^definition = "Referência aos locais onde o serviço pode ser prestado"
* name ^short = "Nome do serviço"
* name ^definition = "Nome do serviço"
* comment ^short = "Comentários sobre o serviço"
* comment ^definition = "Comentários sobre o serviço"
* extraDetails ^short = "Detalhes extras sobre o serviço"
* extraDetails ^definition = "Detalhes extras sobre o serviço"
* photo ^short = "Anexos para facilitar a identificação do serviço"
* photo ^definition = "Anexos para facilitar a identificação do serviço"
* telecom ^short = "Contatos relacionados ao serviço de saúde"
* telecom ^definition = "Contatos relacionados ao serviço de saúde"
* coverageArea ^short = "Área de abrangência do serviço"
* coverageArea ^definition = "Área de abrangência do serviço"
* serviceProvisionCode  ^short = "Condições sob as quais o serviço está disponível/oferecido"
* serviceProvisionCode  ^definition = "Condições sob as quais o serviço está disponível/oferecido"
* serviceProvisionCode from https://terminologia.saude.gov.br/fhir/ValueSet/TipoConvenio (preferred)
* eligibility ^short = "Elegibilidade"
* eligibility ^definition = "Elegibilidade"
* eligibility.id ^short = "Identificador único para referência cruzada"
* eligibility.id ^definition = "Identificador único para referência cruzada"
* eligibility.extension ^short = "Extensões adicionais que não fazem parte do modelo de dados básico"
* eligibility.extension ^definition = "Extensões adicionais que não fazem parte do modelo de dados básico"
* eligibility.modifierExtension ^short = "Extensões adicionais que não podem ser ignoradas, mesmo que não reconhecidas"
* eligibility.modifierExtension ^definition = "Extensões adicionais que não podem ser ignoradas, mesmo que não reconhecidas"
* eligibility.code ^short = "Valor codificado para a elegibilidade"
* eligibility.code ^definition = "Valor codificado para a elegibilidade"
* eligibility.comment ^short = "Descreve as condições de elegibilidade do serviço"
* eligibility.comment ^definition = "Descreve as condições de elegibilidade do serviço"
* program ^short = "Programas que este serviço atende"
* program ^definition = "Programas que este serviço atende"
* program from https://terminologia.saude.gov.br/fhir/ValueSet/BRProgramaSaude (preferred)
* characteristic ^short = "Características do serviço"
* characteristic ^definition = "Características do serviço"
* communication ^short = "Idiomas oferecido por este serviço"
* communication ^definition = "Idiomas oferecido por este serviço"
* referralMethod ^short = "Formas pelas quais o serviço aceita referências"
* referralMethod ^definition = "Formas pelas quais o serviço aceita referências"
* appointmentRequired ^short = "Se for necessário agendamento para acesso a este serviço"
* appointmentRequired ^definition = "Se for necessário agendamento para acesso a este serviço"
* availableTime ^short = "Horários de funcionamento do serviço"
* availableTime ^definition = "Horários de funcionamento do serviço"
* availableTime.id ^short = "Identificador único para referência cruzada"
* availableTime.id ^definition = "Identificador único para referência cruzada"
* availableTime.extension ^short = "Extensões adicionais que não fazem parte do modelo de dados básico"
* availableTime.extension ^definition = "Extensões adicionais que não fazem parte do modelo de dados básico"
* availableTime.modifierExtension ^short = "Extensões adicionais que não podem ser ignoradas, mesmo que não reconhecidas"
* availableTime.modifierExtension ^definition = "Extensões adicionais que não podem ser ignoradas, mesmo que não reconhecidas"
* availableTime.daysOfWeek ^short = "Dias da semana: seg, ter, qua,qui, sex, sab,dom"
* availableTime.daysOfWeek ^definition = "Dias da semana: seg, ter, qua,qui, sex, sab,dom"
* availableTime.allDay ^short = "Se disponível 24 horas"
* availableTime.allDay ^definition = "Se disponível 24 horas"
* availableTime.availableStartTime ^short = "Horário de abertura"
* availableTime.availableStartTime ^definition = "Horário de abertura"
* availableTime.availableEndTime ^short = "Hora de fechamento"
* availableTime.availableEndTime ^definition = "Hora de fechamento"
* notAvailable ^short = "Não disponível"
* notAvailable ^definition = "Não disponível"
* notAvailable.id ^short = "Identificador único para referência cruzada"
* notAvailable.id ^definition = "Identificador único para referência cruzada"
* notAvailable.extension ^short = "Extensões adicionais que não fazem parte do modelo de dados básico"
* notAvailable.extension ^definition = "Extensões adicionais que não fazem parte do modelo de dados básico"
* notAvailable.modifierExtension ^short = "Extensões adicionais que não podem ser ignoradas, mesmo que não reconhecidas"
* notAvailable.modifierExtension ^definition = "Extensões adicionais que não podem ser ignoradas, mesmo que não reconhecidas"
* notAvailable.description ^short = "Motivo da indisponibilidade do serviço"
* notAvailable.description ^definition = "Motivo da indisponibilidade do serviço"
* notAvailable.during ^short = "Período da indisponibilidade"
* notAvailable.during ^definition = "Período da indisponibilidade"
* availabilityExceptions ^short = "Descrição das exceções de disponibilidade"
* availabilityExceptions ^definition = "Descrição das exceções de disponibilidade"
* endpoint ^short = "Endpoints técnicos que fornecem acesso a serviços eletrônicos operados para o serviço de saúde"
* endpoint ^definition = "Endpoints técnicos que fornecem acesso a serviços eletrônicos operados para o serviço de saúde"