Profile: BRCoreMedicationDispense
Parent: http://hl7.org/fhir/StructureDefinition/MedicationDispense
Id: br-core-medicationdispense
Title: "br-core-medicationdispense"
Description: "Este recurso Indica que um medicamento deve ser ou foi dispensado para uma pessoa/paciente. O recurso inclui a descrição do medicamento (suprimento) fornecido bem como as instruções para a sua administração. A dispensação do medicamento é o resultado de um  pedido de medicamentos feito por um sistema de informações"

* id ^short = "Identificador lógico deste artefato"
* id ^definition = "Identificador lógico deste artefato"
* meta ^short = "Metadados sobre o recurso"
* meta ^definition = "Metadados sobre o recurso" 
* implicitRules ^short = "Um conjunto de regras sob as quais este conteúdo foi criado"
* implicitRules ^definition = "Um conjunto de regras sob as quais este conteúdo foi criado"
* language ^short = "Idioma do recurso"
* language ^definition = "Idioma do recurso"
* text ^short = "Resumo do texto do recurso em linguagem natural"
* text ^definition = "Resumo do texto do recurso em linguagem natural"
* contained ^short = "Recursos contidos no recurso"
* contained ^definition = "Recursos contidos no recurso"
* extension ^short = "Extensões adicionais que não fazem parte do modelo base"
* extension ^definition = "Extensões adicionais que não fazem parte do modelo base"
* modifierExtension ^short = "Extensões adicionais que não podem ser ignoradas, mesmo que não reconhecidas"
* modifierExtension ^definition = "Extensões adicionais que não podem ser ignoradas, mesmo que não reconhecidas"
* identifier ^short = "Identificadores externos para este recurso"
* identifier ^definition = "Identificadores externos para este recurso"
* partOf ^short = "Referência ao procedimento que esta dispensação faz parte"
* partOf ^definition = "Referência ao procedimento que esta dispensação faz parte"
* status ^short = "Código de status da dispensação de medicamentos"
* status ^definition = "Código de status da dispensação de medicamentos"
* statusReason[x] ^short = "Porquê uma dispensação não foi realizada"
* statusReason[x] ^definition = "Porquê uma dispensação não foi realizada"
* category ^short = "Tipo de dispensação de medicamentos"
* category ^definition = "Tipo de dispensação de medicamentos"
* category 1..1
* medication[x] ^short = "Que medicamento foi fornecido"
* medication[x] ^definition = "Que medicamento foi fornecido"
* medicationReference ^short = "Referência ao medicamento dispensado"
* medicationReference ^definition = "Referência ao medicamento dispensado"
* medicationReference only Reference(br-core-medication)
* subject ^short = "Referência ao paciente para quem o medicamento foi dispensado"
* subject ^definition = "Referência ao paciente para quem o medicamento foi dispensado"
* subject 1..1
* subject only Reference(br-core-patient)
* context ^short = "Referência ao atendimento o qual o medicamento foi dispensado"
* context ^definition = "Referência ao atendimento o qual o medicamento foi dispensado"
* context only Reference(br-core-encounter)
* supportingInformation ^short = "Referência à outros recursos que subsidiam a dispensação do medicamento"
* supportingInformation ^definition = "Referência à outros recursos que subsidiam a dispensação do medicamento"
* performer ^short = "Quem realizou a dispensação do medicamento"
* performer ^definition = "Quem realizou a dispensação do medicamento"
* performer 1..*
* performer.id ^short = "Identificador exclusivo para referência entre elementos"
* performer.id ^definition = "Identificador exclusivo para referência entre elementos" 
* performer.extension ^short = "Conteúdo adicional definido pelas implementações"
* performer.extension ^definition = "Conteúdo adicional definido pelas implementações"
* performer.modifierExtension ^short = "Extensões que não podem ser ignoradas mesmo que não sejam reconhecidas"
* performer.modifierExtension ^definition = "Extensões que não podem ser ignoradas mesmo que não sejam reconhecidas" 
* performer.function ^short = "Função do profissional da dispensação do medicamento"
* performer.function ^definition = "Função do profissional da dispensação do medicamento"
* performer.actor ^short = "Referência ao profissional/organização/dispositivo/pessoa/paciente que realizou a dispensação do medicamento"
* performer.actor ^definition = "Referência ao profissional/organização/dispositivo/pessoa/paciente que realizou a dispensação do medicamento"
* performer.actor  only Reference(br-core-practitioner or br-core-practitionerrole or br-core-organization or br-core-patient or br-core-relatedperson or Device)
* location ^short = "Referência ao local de dispensação do medicamento"
* location ^definition = "Referência ao local de dispensação do medicamento"
* location only Reference(br-core-location)
* authorizingPrescription ^short = "Referência à solicitação da dispensação do medicamento"
* authorizingPrescription ^definition = "Referência à solicitação da dispensação do medicamento"
* authorizingPrescription only Reference(br-core-medicationrequest)
* type ^short = "Tipo de dispensação do medicamento"
* type ^definition = "Tipo de dispensação do medicamento"
* quantity ^short = "Quantidade de medicamento dispensada"
* quantity ^definition = "Quantidade de medicamento dispensada"
* quantity 1..1
* daysSupply ^short = "Número de dias de dispensação do medicamento"
* daysSupply ^definition = "Número de dias de dispensação do medicamento"
* whenPrepared ^short = "Quando o produto foi embalado e revisado"
* whenPrepared ^definition = "Quando o produto foi embalado e revisado"
* whenHandedOver ^short = "Quando o produto foi distribuído"
* whenHandedOver ^definition = "Quando o produto foi distribuído"
* whenHandedOver 1..1
* destination ^short = "Para onde o medicamento foi enviado"
* destination ^definition = "Para onde o medicamento foi enviado"
* destination only Reference(br-core-location)
* receiver ^short = "Referência ao profissional ou ao paciente que recebeu o medicamento"
* receiver ^definition = "Referência ao profissional ou ao paciente que recebeu o medicamento"
* receiver 1..1
* receiver only Reference(br-core-practitioner or br-core-patient)
* note ^short = "Informações sobre a dispensação do medicamento"
* note ^definition = "Informações sobre a dispensação do medicamento"
* dosageInstruction ^short = "Como o medicamento deve ser usado pelo paciente ou administrado pelo cuidador"
* dosageInstruction ^definition = "Como o medicamento deve ser usado pelo paciente ou administrado pelo cuidador"
* substitution ^short = "Se uma substituição foi realizada na dispensação"
* substitution ^definition = "Se uma substituição foi realizada na dispensação"
* substitution.id ^short = "Identificador exclusivo para referência entre elementos"
* substitution.id ^definition = "Identificador exclusivo para referência entre elementos" 
* substitution.extension ^short = "Conteúdo adicional definido pelas implementações"
* substitution.extension ^definition = "Conteúdo adicional definido pelas implementações"
* substitution.modifierExtension ^short = "Extensões que não podem ser ignoradas mesmo que não sejam reconhecidas"
* substitution.modifierExtension ^definition = "Extensões que não podem ser ignoradas mesmo que não sejam reconhecidas" 
* substitution.wasSubstituted ^short = "Se foi ou não realizada uma substituição na dispensação do medicamento"
* substitution.wasSubstituted ^definition = "Se foi ou não realizada uma substituição na dispensação do medicamento"
* substitution.type ^short = "Código que indica se um medicamento diferente do prescrito foi substituido"
* substitution.type ^definition = "Código que indica se um medicamento diferente do prescrito foi substituido"
* substitution.reason ^short = "Por que a substituição foi feita"
* substitution.reason ^definition = "Por que a substituição foi feita"
* substitution.responsibleParty ^short = "Referência ao profissional responsável pela substituição do medicamento"
* substitution.responsibleParty ^definition = "Referência ao profissional responsável pela substituição do medicamento"
* substitution.responsibleParty only Reference(br-core-practitioner or br-core-practitionerrole)
* detectedIssue ^short = "Referência à condição clínica"
* detectedIssue ^definition = "Referência à condição clínica"
* eventHistory ^short = "Referência à uma lista de eventos"
* eventHistory ^definition = "Referência à uma lista de eventos"