Profile: br-core-allergyintolerance
Parent: http://hl7.org/fhir/StructureDefinition/AllergyIntolerance
Id: br-core-allergyintolerance
Title: "br-core-allergyintolerance"
Description: "Alergia ou intolerância (geralmente: risco de reação adversa a uma substância)."

* id ^short = "Identificador lógico deste artefato."
* id ^definition = "Identificador lógico deste artefato."
* meta ^short = "Metadados sobre o recurso"
* meta ^definition = "Metadados sobre o recurso" 
* implicitRules ^short = "Conjunto de regras sob as quais este conteúdo foi criado"
* implicitRules ^definition = "Conjunto de regras sob as quais este conteúdo foi criado"
* language ^short = "Idioma do conteúdo do recurso"
* language ^definition = "Idioma do conteúdo do recurso"
* text ^short = "Resumo do texto do recurso em linguagem natural"
* text ^definition = "Resumo do texto do recurso em linguagem natural"
* contained ^short = "Recursos contidos em linha"
* contained ^definition = "Recursos contidos em linha"
//* extension[abatement-datetime] ^short = "URL de data e hora de redução da alergia."
//* extension[abatement-datetime] ^definition = "URL de data e hora de redução"
* modifierExtension ^short = "Extensão que não pode ser ignorada"
* modifierExtension ^definition = "Extensão que não pode ser ignorada"
* identifier ^short = "Identificadores externos para este item"
* identifier ^definition = "Identificadores externos para este item"
* clinicalStatus ^short = "O estado clínico da alergia ou intolerância."
* clinicalStatus ^definition = "O estado clínico da alergia ou intolerância."
* verificationStatus ^short = "Afirmação sobre a certeza associada a uma propensão, ou risco potencial, de uma reação à substância identificada."
* verificationStatus ^definition = "Afirmação sobre a certeza associada a uma propensão, ou risco potencial, de uma reação à substância identificada."
* type ^short = "Tipo da reação: Alergia | intolerância - Mecanismo subjacente (se conhecido)"
* type ^definition = "Identificação do mecanismo fisiológico subjacente a um Risco de Reação."
* category ^short = "Categoria de uma substância identificada associada a alergias ou intolerâncias: comida | medicamento | ambiente | biológico"
* category ^definition = "Categoria de uma substância identificada associada a alergias ou intolerâncias."
* criticality ^short = "Criticalidade da reação: baixo | alto | incapaz de avaliar"
* criticality ^definition  = "Estimativa do dano clínico potencial, ou gravidade, de uma reação a uma substância identificada."
* code ^short = "Código do conceito referenciando o IPS"
* code ^definition = "Tipo de substância/produto, condição de alergia ou intolerância ou ou código para alergia ausente/desconhecida."
* code from https://simplifier.net/redenacionaldedadosemsaude/valueset-bralergenos-1.0 (required)
* patient ^short = "Dados do paciente"
* patient ^definition = "Referência do paciente"
* patient only Reference(br-core-patient)
* patient.id ^short = "Identificador exclusivo para referência entre elementos"
* patient.id ^definition = "Identificador exclusivo para referência entre elementos"
* patient.extension ^short = "Conteúdo adicional definido por implementações."
* patient.extension ^definition = "Conteúdo adicional definido por implementações."
* patient.reference ^short = "Referência literal, URL relativa, interna ou absoluta"
* patient.reference ^definition = "Referência literal, URL relativa, interna ou absoluta"
* patient.type ^short = "Tipo ao qual a referência se refere (por exemplo: Paciente)."
* patient.type ^definition = "Tipo ao qual a referência se refere (por exemplo: Paciente)."
* patient.identifier ^short = "Referência lógica, quando a referência literal não é conhecida."
* patient.identifier ^definition = "Referência lógica, quando a referência literal não é conhecida."
* patient.display ^short = "Texto alternativo para o recurso."
* patient.display ^definition = "Texto alternativo para o recurso."
* encounter ^short = "Quando a alergia ou intolerância foi afirmada"
* encounter ^definition = "Quando a alergia ou intolerância foi afirmada"
* encounter only Reference(br-core-encounter)
* onset[x] ^short = "Quando a alergia ou a intolerância foi identificada"
* onset[x] ^definition = "Quando a alergia ou a intolerância foi identificada"
* recordedDate ^short = "Data em que a primeira versão da instância do recurso foi registrada."
* recordedDate ^definition = "Data em que a primeira versão da instância do recurso foi registrada."
* recorder ^short = "Quem registrou a sensibilidade."
* recorder ^definition = "Quem registrou a sensibilidade."
* recorder only Reference(br-core-patient or br-core-practitioner or br-core-practitionerrole or br-core-relatedperson)
* asserter ^short = "Fonte da informação sobre a alergia."
* asserter ^definition = "Fonte da informação sobre a alergia."
* asserter only Reference(br-core-patient or br-core-practitioner or br-core-practitionerrole or br-core-relatedperson)
* lastOccurrence ^short = "Data (/hora) da última ocorrência conhecida de uma reação."
* lastOccurrence ^definition = "Data (/hora) da última ocorrência conhecida de uma reação."
* note ^short = "Texto adicional não capturado em outros campos."
* note ^definition = "Texto adicional não capturado em outros campos.."
* reaction ^short = "Eventos de reação adversa relacionados à exposição da substância"
* reaction ^definition = "Eventos de reação adversa relacionados à exposição da substância"
* reaction.id ^short = "ID exclusivo para referência entre elementos."
* reaction.id ^definition = "ID exclusivo para referência entre elementos."
* reaction.modifierExtension ^short = "Conteúdo adicional definido por implementações."
* reaction.modifierExtension ^definition = "Conteúdo adicional definido por implementações."
* reaction.extension ^short = "Extensões que não podem ser ignoradas mesmo que não sejam reconhecidas."
* reaction.extension ^definition = "Extensões que não podem ser ignoradas mesmo que não sejam reconhecidas."
* reaction.substance ^short = "Substância específica ou produto farmacêutico considerado responsável pelo evento."
* reaction.substance ^definition = "Substância específica ou produto farmacêutico considerado responsável pelo evento."
* reaction.substance from https://terminologia.saude.gov.br/fhir/ValueSet/BRAlergenos
* reaction.manifestation ^short = "Código para a manifestação de reação de alergia ou intolerância do subconjunto SNOMED International Patient Set (IPS) do SNOMED CT (IPS Free Set)."
* reaction.manifestation ^definition = "Código para a manifestação de reação de alergia ou intolerância do subconjunto SNOMED IPS do SNOMED CT (IPS Free Set)."
* reaction.manifestation from https://terminologia.saude.gov.br/fhir/ValueSet/BRMedDRA (required)
* reaction.description ^short = "Descrição do evento como um todo."
* reaction.description ^definition = "Descrição do evento como um todo."
* reaction.onset ^short = "Data (/hora) em que as manifestações apareceram"
* reaction.onset ^definition = "Data (/hora) em que as manifestações apareceram."
* reaction.severity ^short = "Avaliação clínica da gravidade de um evento de reação: leve | moderado | grave (do evento como um todo)"
* reaction.severity ^definition = "mild | moderate | severe (of event as a whole)"
* reaction.exposureRoute ^short = "Como o sujeito foi exposto à substância."
* reaction.exposureRoute ^definition = "Como o sujeito foi exposto à substância."
* reaction.exposureRoute from https://terminologia.saude.gov.br/fhir/ValueSet/medicine-route-of-administration/
* reaction.note ^definition = "Texto sobre evento não capturado em outros campos."