Profile: BRCoreCapacidadeFuncional
Parent: br-core-condition
Id: br-core-capacidadefuncional
Title: "br-core-capacidadefuncional"
Description: "Capacidade funcional ou incapacidade do indivíduo (achado funcional), registrada como Condition. Herda do [br-core-condition](StructureDefinition-br-core-condition.html)."

* id ^short = "Identificador lógico deste artefato"
* id ^definition = "Identificador lógico deste artefato"
* meta ^short = "Metadados sobre o recurso"
* meta ^definition = "Metadados sobre o recurso" 
* implicitRules ^short = "Um conjunto de regras sob as quais este conteúdo foi criado"
* implicitRules ^definition = "Um conjunto de regras sob as quais este conteúdo foi criado"
* language ^short = "Idioma do recurso"
* language ^definition = "Idioma do recurso"
* text ^short = "Resumo do texto do recurso em linguagem natural"
* text ^definition = "Resumo do texto do recurso em linguagem natural"
* contained ^short = "Recursos contidos no recurso"
* contained ^definition = "Recursos contidos no recurso"
* extension ^short = "Extensões adicionais que não fazem parte do modelo base"
* extension ^definition = "Extensões adicionais que não fazem parte do modelo base"
* modifierExtension ^short = "Extensões adicionais que não podem ser ignoradas, mesmo que não reconhecidas"
* modifierExtension ^definition = "Extensões adicionais que não podem ser ignoradas, mesmo que não reconhecidas"
* identifier ^short = "Identificadores externos para este recurso"
* identifier ^definition = "Identificadores externos para este recurso"
* clinicalStatus ^short = "O status clínico da condição ou do diagnóstico"
* clinicalStatus ^definition = "O status clínico da condição ou do diagnóstico"
* clinicalStatus 1..1
* clinicalStatus.coding ^short = ""
* clinicalStatus.coding ^definition = ""
* clinicalStatus.coding.system 1..1
* clinicalStatus.coding.system ^short = "Identificador do sistema de terminologia"
* clinicalStatus.coding.system ^definition = "Identificador do sistema de terminologia"
* clinicalStatus.coding.code 1..1
* clinicalStatus.coding.code ^short = "Símbolo na sintaxe definida pelo sistema"
* clinicalStatus.coding.code ^definition = "Símbolo na sintaxe definida pelo sistema"
* clinicalStatus.coding.display 0..1
* clinicalStatus.coding.display ^short = "Representação definida pelo sistema"
* clinicalStatus.coding.display ^definition = "Representação definida pelo sistema"
* clinicalStatus.coding.userSelected ^short = "Se este código foi escolhido diretamente pelo usuário"
* clinicalStatus.coding.userSelected ^definition = "Se este código foi escolhido diretamente pelo usuário"
* clinicalStatus.coding.version ^short = "Versão do sistema de terminologia, se relevante"
* clinicalStatus.coding.version ^definition = "Versão do sistema de terminologia, se relevante"
* clinicalStatus.text ^short = "Representação em texto livre do conceito"
* clinicalStatus.text ^definition = "Representação em texto livre do conceito"
* verificationStatus ^short = "O status de verificação para apoiar ou recusar o status clínico da condição ou do diagnóstico"
* verificationStatus ^definition = "O status de verificação para apoiar ou recusar o status clínico da condição ou do diagnóstico"
* category ^short = "Categoria da condição" 
* category ^definition = "Categoria da condição"
* category 0..1
* severity ^short = "Severidade da condição" 
* severity ^definition = "Severidade da condição" 
* code ^definition = "Achado funcional (capacidade ou incapacidade). Preferencialmente SNOMED CT (Functional finding); CID-10 ou CIAP-2 da condição de base podem vir como codificação adicional"
* code ^short = "Achado funcional (capacidade ou incapacidade)"
* code 1..1
// Sem binding nacional: vale o example do R4. SNOMED CT (descendentes de 118228005 Functional finding)
// é o recomendado; o ValueSet BRCapacidadeFuncional depende de o OCL suportar ValueSet intensional.
* code.text
* bodySite ^short = "Local anatômico da condição, se relevante" 
* bodySite ^definition = "Local anatômico da condição, se relevante" 
* subject ^short = "Indivíduo com a Condição de Saúde avaliada"
* subject ^definition = "Indivíduo com a Condição de Saúde avaliada"
* subject only Reference(br-core-patient)
* subject.id ^short = "Identificador único para referência cruzada"
* subject.id ^definition = "Identificador único para referência cruzada"
* subject.extension ^short = "Extensões adicionais que não fazem parte do modelo de dados básico"
* subject.extension ^definition = "Extensões adicionais que não fazem parte do modelo de dados básico"
* subject.reference ^short = "Referência literal. URL relativa, interna ou externa"
* subject.reference ^definition = "Referência literal. URL relativa, interna ou externa"
* subject.type ^short = "Tipo de recurso ao qual a referência é feita"
* subject.type ^definition = "Tipo de recurso ao qual a referência é feita"
* subject.identifier ^short = "Referência lógica, quando a referência literal não é conhecida"
* subject.identifier ^definition = "Referência lógica, quando a referência literal não é conhecida"
* subject.identifier.id ^short = "Identificador único para referência cruzada"
* subject.identifier.id ^definition = "Identificador único para referência cruzada"
* subject.identifier.extension ^short = "Extensões adicionais definidas pela implementação"
* subject.identifier.extension ^definition = "Extensões adicionais definidas pela implementação"
* subject.identifier.type ^short = "Descrição do identificador"
* subject.identifier.type ^definition = "Descrição do identificador"
* subject.identifier.system ^short = "O namespace do valor do identificador"
* subject.identifier.system ^definition = "O namespace do valor do identificador"
* subject.identifier.value ^short = "Valor único do identificador"
* subject.identifier.value ^definition = "Valor único do identificador"
* subject.identifier.period ^short = "Período de tempo no qual este identicador é/ou foi válido para utilização"
* subject.identifier.period ^definition = "Período de tempo no qual este identicador é/ou foi válido para utilização"
* subject.identifier.assigner ^short = "Organização que emitiu o documento de identificação (pode ser apenas texto)"
* subject.identifier.assigner ^definition = "Organização que emitiu o documento de identificação (pode ser apenas texto)"
* subject.display ^short = "Texto alternativo para o recurso"
* subject.display ^definition = "Texto alternativo para o recurso"
* encounter ^short = "Referência ao atendimento no qual a condição foi diagnosticada"
* encounter ^definition = "Referência ao atendimento no qual a condição foi diagnosticada"
* encounter only Reference(br-core-encounter)
* onset[x] ^short = "Data ou idade estimada ou real do começo dos sintomas"
* onset[x] ^definition = "Data ou idade estimada ou real do começo dos sintomas"
* abatement[x] ^short = "Data ou idade estimada ou real em que o diagnóstico foi resolvido ou entrou em remissão"
* abatement[x] ^definition = "Data ou idade estimada ou real em que o diagnóstico foi resolvido ou entrou em remissão"
* recordedDate ^short = "Data na qual o registro foi registrado pela primeira vez"
* recordedDate ^definition = "Data na qual o registro foi registrado pela primeira vez"
* recorder ^short = "Quem registrou a condição"
* recorder ^definition = "Quem registrou a condição"
* recorder only Reference(br-core-patient or br-core-practitioner or br-core-practitionerrole or br-core-relatedperson)
* asserter ^short = "Pessoa que afirma a condição"
* asserter ^definition = "Pessoa que afirma a condição"
* asserter only Reference(br-core-patient or br-core-practitioner or br-core-practitionerrole or br-core-relatedperson)
* stage ^short = "Estágio/grau da condição, geralmente avaliado formalmente"
* stage ^definition = "Estágio/grau da condição, geralmente avaliado formalmente"
* stage.id ^short = "Identificador único para referência cruzada"
* stage.id ^definition = "Identificador único para referência cruzada"
* stage.extension ^short = "Extensões adicionais que não fazem parte do modelo de dados básico"
* stage.extension ^definition = "Extensões adicionais que não fazem parte do modelo de dados básico"
* stage.modifierExtension ^short = "Extensões adicionais que não podem ser ignoradas, mesmo que não reconhecidas"
* stage.modifierExtension ^definition = "Extensões adicionais que não podem ser ignoradas, mesmo que não reconhecidas"
* stage.summary ^short = "Códigos descrevendo estágios da condição (por exemplo, estágios de câncer)"
* stage.summary ^definition = "Códigos descrevendo estágios da condição (por exemplo, estágios de câncer)"
* stage.assessment ^short = "Avaliação que sustenta o grau (escala, observação, laudo)"
* stage.assessment ^definition = "Referência à avaliação que sustenta o grau de capacidade funcional: escala aplicada, observação ou laudo"
* stage.assessment only Reference(ClinicalImpression or br-core-diagnosticreport or br-core-observation)
* stage.type ^short = "Códigos que descrevem  o tipo do estadiamento (por exemplo, clínico ou patológico)"
* stage.type ^definition = "Códigos que descrevem  o tipo do estadiamento (por exemplo, clínico ou patológico)"
* evidence ^short = "Evidências de apoio ao diagnóstico"
* evidence ^definition = "Evidências de apoio ao diagnóstico"
* evidence.id ^short = "Identificador único para referência cruzada"
* evidence.id ^definition = "Identificador único para referência cruzada"
* evidence.extension ^short = "Extensões adicionais que não fazem parte do modelo de dados básico"
* evidence.extension ^definition = "Extensões adicionais que não fazem parte do modelo de dados básico"
* evidence.modifierExtension ^short = "Extensões adicionais que não podem ser ignoradas, mesmo que não reconhecidas"
* evidence.modifierExtension ^definition = "Extensões adicionais que não podem ser ignoradas, mesmo que não reconhecidas"
* evidence.code ^short =  "Manifestação/sintoma"
* evidence.code ^definition = "Códigos que descrevem a manifestação ou sintomas de uma condição"
* evidence.detail ^short = "Referência à informações de apoio"
* evidence.detail ^definition = "Referência à informações de apoio"
* evidence.detail only Reference(Resource)
* note ^short = "Informações adicionais sobre a condição"
* note ^definition = "Informações adicionais sobre a condição"