Profile: BRCoreCarePlan
Parent: http://hl7.org/fhir/StructureDefinition/CarePlan
Id: br-core-careplan
Description: "Este perfil restringe o recurso [CarePlan](https://hl7.org/fhir/R4/careplan.html) que descreve a intenção de como um ou mais profissionais pretendem prestar cuidados a um determinado paciente, grupo ou comunidade por um período de tempo, possivelmente limitado ao cuidado de uma condição específica ou conjunto de condições."

* id ^short = "Identificador lógico deste artefato."
* id ^definition = "Identificador lógico deste artefato."
* meta ^short = "Metadados sobre o recurso"
* meta ^definition = "Metadados sobre o recurso" 
* implicitRules ^short = "Um conjunto de regras sob as quais este conteúdo foi criado"
* implicitRules ^definition = "Um conjunto de regras sob as quais este conteúdo foi criado"
* language ^short = "Idioma do recurso"
* language ^definition = "Idioma do recurso"
* text ^short = "Resumo do texto do recurso em linguagem natural"
* text ^definition = "Resumo do texto do recurso em linguagem natural"
* contained ^short = "Recursos contidos"
* contained ^definition = "Recursos contidos no recurso"
* extension ^short = "Extensões adicionais"
* extension ^definition = "Extensões adicionais que não fazem parte do modelo base"
* modifierExtension ^short = "Extensões adicionais que não podem ser ignoradas, mesmo que não reconhecidas"
* modifierExtension ^definition = "Extensões adicionais que não podem ser ignoradas, mesmo que não reconhecidas"
* identifier ^short = "Identificadores externos para este recurso"
* identifier ^definition = "Identificadores externos para este recurso"
* instantiatesCanonical ^short = "Instância o protocolo ou definição FHIR"
* instantiatesCanonical ^definition = "Instância o protocolo ou definição FHIR"
* instantiatesUri ^short = "uri da instância do protocolo ou definição FHIR"
* instantiatesUri ^definition = "uri da instância do protocolo ou definição FHIR"
* basedOn ^short = "De acordo com o Plano de Cuidado"
* basedOn ^definition = "De acordo com o Plano de Cuidado"
* basedOn only Reference(br-core-careplan)
* replaces ^short = "Plano de Cuidado substituído por este Plano de Cuidado"
* replaces ^definition = "Plano de Cuidado substituído por este Plano de Cuidado"
* replaces only Reference(br-core-careplan)
* partOf ^short = "Parte do Plano de Cuidado referenciado"
* partOf ^definition = "Parte do Plano de Cuidado referenciado"
* partOf only Reference(br-core-careplan)
* status ^short = "O status desse Plano de Cuidado"
* status ^definition = "draft | active | on-hold | revoked | completed | entered-in-error | unknown"
* intent ^short = "Propósito do Plano de Cuidado definido"
* intent ^definition = "proposal | plan | order | option"
* category ^short = "Tipo de Plano de Cuidado"
* category ^definition = "Tipo de Plano de Cuidado"
* title ^short = "Nome do Plano de Cuidado"
* title ^definition = "Nome do Plano de Cuidado"
* description 1..1
* description ^short = "Descrição do Plano de Cuidado"
* description ^definition = "Descrição do Plano de Cuidado"
* subject ^short = "Paciente referenciado pelo Plano de Cuidado"
* subject ^definition = "Paciente referenciado pelo Plano de Cuidado"
* subject only Reference(br-core-patient)
* encounter ^short = "Atendimento referenciado pelo Plano de Cuidado"
* encounter ^definition = "Atendimento referenciado pelo Plano de Cuidado"
* encounter only Reference(br-core-encounter)
* period ^short = "O período de tempo que o Plano de Cuidado abrange"
* period ^definition = "O período de tempo que o Plano de Cuidado abrange"
* created ^short = "Data de criação do Plano de Cuidado"
* created ^definition = "Data de criação do Plano de Cuidado"
* author ^short = "Autoria do Plano de Cuidado"
* author ^definition = "Autoria do Plano de Cuidado"
* author only Reference(br-core-practitioner or br-core-practitionerrole or br-core-organization or br-core-patient or br-core-relatedperson or Device or CareTeam)
* contributor ^short = "Colaboradores na definição do Plano de Cuidado"
* contributor ^definition = "Colaboradores na definição do Plano de Cuidado"
* contributor only Reference(br-core-practitioner or br-core-practitionerrole or br-core-organization or br-core-patient or br-core-relatedperson or Device or CareTeam)
* careTeam ^short = "Equipe assistêncial envolvida no Plano de Cuidado"
* careTeam ^definition = "Equipe assistêncial envolvida no Plano de Cuidado"
* addresses 0..1
* addresses ^short = "Problemas de saúde referenciado neste Plano de Cuidado"
* addresses ^definition = "Problemas de saúde referenciado neste Plano de Cuidado"
* addresses only Reference(br-core-condition)
* supportingInfo ^short = "Informações adicionais do Plano de Cuidado"
* supportingInfo ^definition = "Informações adicionais do Plano de Cuidado"
* goal ^short = "Resultado esperado do Plano de Cuidado"
* goal ^definition = "Resultado esperado do Plano de Cuidado"
* activity ^short = "Atividade parte do Plano de Cuidado"
* activity ^definition = "Atividade parte do Plano de Cuidado"
* activity 1..1
* activity.id ^short = "Identificador único para referencia cruzada"
* activity.id ^definition = "Identificador único para referencia cruzada"
* activity.extension ^short = "Extensões adicionais que não fazem parte do modelo de dados básico"
* activity.extension ^definition = "Extensões adicionais que não fazem parte do modelo de dados básico"
* activity.modifierExtension ^short = "Extensões adicionais que não podem ser ignoradas, mesmo que não reconhecidas"
* activity.modifierExtension ^definition = "Extensões adicionais que não podem ser ignoradas, mesmo que não reconhecidas"
* activity.outcomeCodeableConcept ^short = "Resultados da atividade"
* activity.outcomeCodeableConcept ^definition = "Resultados da atividade"
* activity.outcomeReference ^short = "Referência a 'Appointment', 'Encounter', 'Procedure', etc."
* activity.outcomeReference ^definition = "Referência a 'Appointment', 'Encounter', 'Procedure', etc."
* activity.progress ^short = "Comentários sobre o status/progresso da atividade"
* activity.progress ^definition = "Comentários sobre o status/progresso da atividade"
* activity.reference ^short = "Detalhes da atividade definidos em recursos específicos"
* activity.reference ^definition = "Detalhes da atividade definidos em recursos específicos"
* activity.detail ^short = "Definição da atividade"
* activity.detail ^definition = "Definição da atividade"
* activity.detail 1..1
* activity.detail.id ^short = "Identificador único para referencia cruzada"
* activity.detail.id ^definition = "Identificador único para referencia cruzada"
* activity.detail.modifierExtension ^short = "Extensões que não podem ser ignoradas"
* activity.detail.modifierExtension ^definition = "Extensões que não podem ser ignoradas"
* activity.detail.kind ^short = "Tipos de recursos definidos como parte do FHIR que podem ser representados como definições em conformidade de uma atividade do Plano de Cuidados"
* activity.detail.kind ^definition = "Appointment | CommunicationRequest | DeviceRequest | MedicationRequest | NutritionOrder | Task | ServiceRequest | VisionPrescription"
* activity.detail.instantiatesCanonical ^short = "Instância o protocolo ou definição FHIR"
* activity.detail.instantiatesCanonical ^definition = "Instância o protocolo ou definição FHIR"
* activity.detail.instantiatesUri ^short = "Instância protocolo externo ou definição"
* activity.detail.instantiatesUri ^definition = "Instância protocolo externo ou definição"
* activity.detail.code ^short = "Código da atividade"
* activity.detail.code ^definition = "Código da atividade"
* activity.detail.code from https://terminologia.saude.gov.br/fhir/ValueSet/BRSubgrupoTabelaSUS
* activity.detail.reasonCode ^short = "Por quê a atividade deve ser feita ou Por quê a atividade foi proibida"
* activity.detail.reasonCode ^definition = "Por quê a atividade deve ser feita ou Por quê a atividade foi proibida"
* activity.detail.reasonReference ^short = "Por quê a atividade é necessária"
* activity.detail.reasonReference ^definition = "Por quê a atividade é necessária"
* activity.detail.goal ^short = "Objetivos da atividade"
* activity.detail.goal ^definition = "Objetivos da atividade"
* activity.detail.status ^short = "Código que reflete o estado atual de uma atividade do Planos de Cuidado"
* activity.detail.status ^definition = "Código que reflete o estado atual de uma atividade do Planos de Cuidado"
* activity.detail.statusReason ^short = "Motivo do status atual"
* activity.detail.statusReason ^definition = "Motivo do status atual"
* activity.detail.doNotPerform ^short = "Se for verdade, a atividade não deve ser realizada"
* activity.detail.doNotPerform ^definition = "Se for verdade, a atividade não deve ser realizada"
* activity.detail.scheduled[x] 1..1
* activity.detail.scheduled[x] ^short = "Quando a atividade deve ocorrer"
* activity.detail.scheduled[x] ^definition = "Quando a atividade deve ocorrer"
* activity.detail.location ^short = "Onde a atividade deve ocorrer"
* activity.detail.location ^definition = "Onde a atividade deve ocorrer"
* activity.detail.performer ^short = "Responsável pela atividade"
* activity.detail.performer ^definition = "Responsável pela atividade"
* activity.detail.product[x] ^short = "O que deve ser administrado/fornecido"
* activity.detail.product[x] ^definition = "O que deve ser administrado/fornecido"
* activity.detail.dailyAmount ^short = "Quantidade diária a ser consumida/fornecida/administrada"
* activity.detail.dailyAmount ^definition = "Quantidade diária a ser consumida/fornecida/administrada"
* activity.detail.quantity ^short = "Quantidade a ser consumida/fornecida/administrada"
* activity.detail.quantity ^definition = "Quantidade a ser consumida/fornecida/administrada"
* activity.detail.description 1..1
* activity.detail.description ^short = "Descrição da atividade a ser realizada"
* activity.detail.description ^definition = "Descrição da atividade a ser realizada"
* note ^short = "Comentários sobre o Planos de Cuidado"
* note ^definition = "Comentários sobre o Planos de Cuidado"