Profile: br-core-immunizationrecommendation
Parent: http://hl7.org/fhir/StructureDefinition/ImmunizationRecommendation
Id: br-core-immunizationrecommendation
Description: "Este perfil "

* identifier ^short = "Identificadores externos para este recurso"
* identifier ^definition = "Identificadores externos para este recurso"
* patient ^short = "Para quem é esse perfil"
* patient ^definition = "Para quem é esse perfil"
* date ^short = "Data em que a recomendação foi criada"
* date ^definition = "Data em que a recomendação foi criada"
* authority ^short = "Quem é responsável pelo protocolo"
* authority ^definition = "Quem é responsável pelo protocolo"
* recommendation ^short = "Recomendações para administração de vacinas"
* recommendation ^definition = "Recomendações para administração de vacinas"
* recommendation.vaccineCode ^short = "A recomendação da vacina ou do grupo de vacina se aplica a"
* recommendation.vaccineCode ^definition = "A recomendação da vacina ou do grupo de vacina se aplica a"
* recommendation.targetDisease ^short = "Doença contra a qual se deve imunizar"
* recommendation.targetDisease ^definition = "Doença contra a qual se deve imunizar"
* recommendation.contraindicatedVaccineCode ^short = "Vacina que é contraindicada para cumprir a recomendação"
* recommendation.contraindicatedVaccineCode ^definition = "Vacina que é contraindicada para cumprir a recomendação"
* recommendation.forecastStatus ^short = "Status de recomendação da vacina"
* recommendation.forecastStatus ^definition = "Status de recomendação da vacina"
* recommendation.forecastReason ^short = "Motivo do status de administração da vacina"
* recommendation.forecastReason ^definition = "Motivo do status de administração da vacina"
* recommendation.dateCriterion ^short = "Datas que regem a imunização proposta"
* recommendation.dateCriterion ^definition = "Datas que regem a imunização proposta"
* recommendation.dateCriterion.code ^short = "Tipo de data"
* recommendation.dateCriterion.code ^definition = "Tipo de data"
* recommendation.dateCriterion.value ^short = "Data recomendada"
* recommendation.dateCriterion.value ^definition = "Data recomendada"
* recommendation.description ^short = "Detalhes do protocolo"
* recommendation.description ^definition = "Detalhes do protocolo"
* recommendation.series ^short = "Nome da série de vacinação"
* recommendation.series ^definition = "Nome da série de vacinação"
* recommendation.doseNumber[x] ^short = "Número de dose recomendado dentro da série"
* recommendation.doseNumber[x] ^definition = "Número de dose recomendado dentro da série"
* recommendation.seriesDoses[x] ^short = "Número recomendado de doses para imunidade"
* recommendation.seriesDoses[x] ^definition = "Número recomendado de doses para imunidade"
* recommendation.supportingImmunization ^short = "Imunizações anteriores que apoiam a recomendação"
* recommendation.supportingImmunization ^definition = "Imunizações anteriores que apoiam a recomendação"
* recommendation.supportingPatientInformation ^short = "Observações do paciente que apoiam a recomendação"
* recommendation.supportingPatientInformation ^definition = "Observações do paciente que apoiam a recomendação"