Profile: BRCoreMedication
Parent: http://hl7.org/fhir/StructureDefinition/Medication
Id: br-core-medication
Title: "br-core-medication"
Description: "Este recurso é uma especialização do recurso FHIR R4 [Medication](https://hl7.org/fhir/R4/medication.html) usado principalmente para a identificação e definição de um medicamento para fins de prescrição, dispensação e administração de um medicamento, bem como para fazer declarações sobre medicamentos no Brasil."

* id ^short = "ID lógico deste artefato"
* id ^definition = "ID lógico deste artefato"
* meta ^short = "Metadados sobre o recurso"
* meta ^definition = "Metadados adicionais sobre o recurso"
* implicitRules ^short = "Um conjunto de regras sob as quais este conteúdo foi criado"
* implicitRules ^definition = "Um ou mais códigos que servem para identificar o tipo de recurso"
* language ^short = "Linguagem do recurso"
* language ^definition = "A linguagem humana natural do recurso"
* text ^short = "Resumo de texto para o recurso, para interpretação humana"
* text ^definition = "Um texto narrativo resumindo as informações do recurso"
* contained ^short = "Recursos contidos"
* contained ^definition = "Recursos contidos no recurso"
* extension ^short = "Extensões adicionais"
* extension ^definition = "Conteúdo adicional definido por implementações"
* extension 0..1
* modifierExtension ^short = "Extensões adicionais"
* modifierExtension ^definition = "Extensões que não podem ser ignoradas"
* identifier ^short = "Identificador de negócios para este medicamento"
* identifier ^definition = "Identificador de negócios para este medicamento"
* code ^short = "Nome do medicamento"
* code ^definition = "Nome e terminologia do medicamento fabricado."
* code from http://www.whocc.no/atc (preferred)
* status ^short = "ativo| inativo| entrado com erro"
* status ^definition = "ativo| inativo| entrado com erro"
* manufacturer ^short = "Organização Fabricante"
* manufacturer ^definition = "Fabricante do item"
* manufacturer only Reference(br-core-organization)
* form ^short = "Unidade de medida do medicamento"
* form ^definition = "Unidade de medida do medicamento prescrito (ex.: comprimido, cápsula, frasco, caixa etc.)."
* form from http://fhir.ch/ig/ch-emed/ValueSet/edqm-pharmaceuticaldoseform (preferred)
* amount ^short = "Quantidade de medicamento"
* amount ^definition = "Quantidade de medicamento na embalagem"
* ingredient ^short = "Ingrediente ativo ou inativo"
* ingredient ^definition = "Ingrediente ativo ou inativo"
* ingredient from http://www.whocc.no/atc (preferred)
* id ^short = "Referenciamento entre elemento"
* id ^definition = "ID exclusivo para referência entre elementos"
* extension ^short = "Extensões adicionais"
* extension ^definition = "Conteúdo adicional definido por implementações"
* modifierExtension ^short = "Extensões"
* modifierExtension ^definition = "Extensões que não podem ser ignoradas"
* ingredient.item[x] ^short = "Ingrediente"
* ingredient.item[x] ^definition = "O ingrediente ou conteúdo real Vinculante: Substâncias ativas de medicamentos - IPS (preferencial): Substâncias medicamentosas SNOMED CT"
* ingredient.itemReference only Reference(Substance or br-core-medication)
* ingredient.isActive ^short = "Ingrediente ativo"
* ingredient.isActive ^definition = "Indicador de ingrediente ativo"
* ingredient.strength ^short = "Uma proporção de dois valores de Quantidade - um numerador e um denominador"
* ingredient.strength ^definition = "Uma proporção de dois valores de Quantidade - um numerador e um denominador"
* batch ^short = "Detalhes sobre a medicação."
* batch ^definition = "Informação sobre lote e validade da medicação."
* batch.lotNumber ^short = "Lote de medicamento."
* batch.lotNumber ^definition = "RN14: Se medicamento serializado/Datamatrix - Elemento lot do XML para grupo IUM."
* batch.expirationDate ^short = "Data de validade do medicamento."
* batch.expirationDate ^definition = "Quando o lote vai expirar"