Profile: BRCoreObservation
Parent: http://hl7.org/fhir/StructureDefinition/Observation
Id: br-core-observation
Description: "O recurso [br-core-Observation](StructureDefinition-br-core-observation.html) herda do recurso FHIR R4 [observation](https://hl7.org/fhir/R4B/observation.html) e registra medidas e resumo simples feitas sobre um paciente, dispositivo ou outro assunto"

* id ^short = "Identificador lógico deste artefato"
* id ^definition = "Identificador lógico deste artefato"
* meta ^short = "Metadados sobre o recurso"
* meta ^definition = "Metadados sobre o recurso" 
* implicitRules ^short = "Um conjunto de regras sob as quais este conteúdo foi criado"
* implicitRules ^definition = "Um conjunto de regras sob as quais este conteúdo foi criado"
* language ^short = "Idioma do recurso"
* language ^definition = "Idioma do recurso"
* text ^short = "Resumo do texto do recurso em linguagem natural"
* text ^definition = "Resumo do texto do recurso em linguagem natural"
* contained ^definition = "Recursos contidos no recurso"
* contained ^definition = "Recursos contidos no recurso"
* extension ^definition = "Extensões adicionais que não fazem parte do modelo base"
* extension ^definition = "Extensões adicionais que não fazem parte do modelo base"
* modifierExtension ^short = "Extensões adicionais que não podem ser ignoradas, mesmo que não reconhecidas"
* modifierExtension ^definition = "Extensões adicionais que não podem ser ignoradas, mesmo que não reconhecidas"
* identifier ^short = "Identificadores externos para este recurso"
* identifier ^definition = "Identificadores externos para este recurso"
* basedOn ^short = "Referência ao pedido ou ao plano de tratamento que gerou este recurso"
* basedOn ^definition = "Referência ao pedido ou ao plano de tratamento que gerou este recurso"
* basedOn only Reference(br-core-careplan or DeviceRequest or ImmunizationRecommendation or br-core-medicationrequest or NutritionOrder or br-core-servicerequest)
* partOf ^short = "Referência ao evento do qual este recurso faz parte"
* partOf ^definition = "Referência ao evento do qual este recurso faz parte"
* partOf only Reference(br-core-medicationadministration or br-core-medicationdispense or br-core-medicationstatement or br-core-procedure or br-core-immunization or ImagingStudy)
* status ^short = "Status atual da observação"
* status ^definition = "active | completed | entered-in-error | intended | stopped | on-hold | unknown | not-taken"
* category ^short = "Categoria da observação"
* category ^definition = "Categoria da observação"
* code ^short = "Código da observação"
* code ^definition = "Código da observação"
* subject ^short = "Referência ao paciente ou local ou dispositivo ou grupo desta bservação"
* subject ^definition = "Referência ao paciente ou local ou dispositivo ou grupo desta bservação"
* subject only Reference(br-core-patient or br-core-location or Device or Group)
* subject.id ^short = "ID exclusivo para referência entre elementos"
* subject.id ^definition = "ID exclusivo para referência entre elementos"
* subject.extension ^short = "Conteúdo adicional definido por implementações"
* subject.extension ^definition = "Conteúdo adicional definido por implementações"
* subject.reference 0..1
* subject.reference ^short = "Referência literal, URL relativa, interna ou absoluta"
* subject.reference ^definition = "Referência literal, URL relativa, interna ou absoluta"
* subject.type ^short = "Tipo de referência (por exemplo, Paciente)"
* subject.type ^definition = "Tipo de referência (por exemplo, Paciente)"
* subject.identifier ^short = "Referência lógica, quando a referência literal não é conhecida"
* subject.identifier ^definition = "Referência lógica, quando a referência literal não é conhecida"
* subject.display ^short = "Texto alternativo para este rescurso"
* subject.display ^definition = "Texto alternativo para este recurso"
* focus ^short = "Referência à outro recurso desta observação"
* focus ^definition = "Referência à outro recurso desta observação"
* focus only Reference(Resource)
* encounter ^short = "Referência ao atendimento durante o qual esta observação foi registrada"
* encounter ^definition = "Referência ao atendimento durante o qual esta observação foi registrada"
* encounter only Reference(br-core-encounter)
* effective[x] ^short = "Tempo ou período de tempo clinicamente relevante para a observação"
* effective[x] ^definition = "Tempo ou período de tempo clinicamente relevante para a observação"
* issued ^short = "Data/hora em que esta versão foi disponibilizada"
* issued ^definition = "Data/hora em que esta versão foi disponibilizada"
* performer ^short = "Referência ao responsável pela observação"
* performer ^definition = "Quem é o responsável pela observação"
* performer only Reference(br-core-practitioner or br-core-practitionerrole or br-core-organization or CareTeam or br-core-patient or br-core-relatedperson)
* value[x] ^short = "Resultado da observação"
* value[x] ^definition = "Resultado da observação"
* dataAbsentReason ^short = "Por quê o resultado está faltando"
* dataAbsentReason ^definition = "Utilizado para especificar o porquê o valor esperado não está presente"
* interpretation ^short = "Interpretação do resultado"
* interpretation ^definition = "Interpretação da observação. Por exemplo: valor alto, baixo, normal"
* note ^short = "Comentários sobre a observação"
* note ^definition = "Comentários sobre a observação"
* bodySite ^short = "Parte anatômica alvo da observação"
* bodySite ^definition = "Parte anatômica alvo da observação"
* method ^short = "Método de medida da observação"
* method ^definition = "Método de medida da observação"
* specimen ^short = "Amostra utilizada para esta observação"
* specimen ^definition = "Amostra utilizada para esta observação"
* specimen only Reference(br-core-specimen)
* device ^short = "Dispositivo de medida da observação"
* device ^definition = "Dispositivo utilizado para registrar esta observação"
* device only Reference(Device or DeviceMetric)
* referenceRange ^short = "Fornece um guia para interpretação"
* referenceRange ^definition = "Fornece um guia para interpretação"
* referenceRange.id ^short = "Identificador único para referência cruzada"
* referenceRange.id ^definition = "Identificador único para referência cruzada"
* referenceRange.extension ^short = "Extensões adicionais que não fazem parte do modelo de dados básico"
* referenceRange.extension ^definition = "Extensões adicionais que não fazem parte do modelo de dados básico" 
* referenceRange.modifierExtension ^short = "Extensões adicionais que não podem ser ignoradas, mesmo que não reconhecidas"
* referenceRange.modifierExtension ^definition = "Extensões adicionais que não podem ser ignoradas, mesmo que não reconhecidas"
* referenceRange.modifierExtension 1..1
* referenceRange.low ^short = "Limite inferior do intervalo"
* referenceRange.low ^definition = "Limite inferior do intervalo de valores de referência"
* referenceRange.high ^short = "Limite superior do intervalo"
* referenceRange.high ^definition = "Limite superior do intervalo de valores de referência"
* referenceRange.type ^short = "Qualificador do valor de referência"
* referenceRange.type ^definition = "Qualificador do valor de referência"
* referenceRange.appliesTo ^short = "População do intervalo de referência"
* referenceRange.appliesTo ^definition = "População do intervalo de referência"
* referenceRange.age ^short = "Faixa etária aplicável"
* referenceRange.age ^definition = "Faixa etária aplicável, se relevante"
* referenceRange.text ^short = "Intervalo de referência em formato textual"
* referenceRange.text ^definition = "Intervalo de referência em formato textual"
* referenceRange.text 1..1
* hasMember ^short = "Referência à Observação/Resposta de questionário associada a esta observação"
* hasMember ^definition = "Referência à Observação/Resposta de questionário associada a esta observação"
* hasMember only Reference(br-core-observation or QuestionnaireResponse or MolecularSequence)
* derivedFrom ^short = "Referência à Documents, Imagens, Mídias associadas a esta observação"
* derivedFrom ^definition = "Referência à Documents, Imagens, Mídias associadas a esta observação"
* derivedFrom only Reference(DocumentReference or ImagingStudy or Media or QuestionnaireResponse or br-core-observation or MolecularSequence)
* component ^short = "Resultado dos componentes da observação" 
* component ^definition = "Resultado dos componentes da observação"
* component.id ^short = "ID exclusivo para referência entre elementos"
* component.id ^definition = "ID exclusivo para referência entre elementos"
* component.extension ^short = "Conteúdo adicional definido por implementações"
* component.extension ^definition = "Conteúdo adicional definido por implementações"
* component.modifierExtension ^short = "Extensões que não podem ser ignoradas mesmo que não sejam reconhecidas"
* component.modifierExtension ^definition = "Extensões que não podem ser ignoradas mesmo que não sejam reconhecidas"
* component.code ^short = "Tipo do componente da observação"
* component.code ^definition = "Tipo do componente da observação"
* component.value[x] ^short = "Resultado do componente"
* component.value[x] ^definition = "Resultado do componente"
* component.dataAbsentReason ^short = "Por que o resultado do componente está ausente"
* component.dataAbsentReason ^definition = "Por que o resultado do componente está ausente"
* component.interpretation ^short = "Interpretação do resultado do componente"
* component.interpretation ^definition = "Interpretação do resultado do componente"
* component.referenceRange ^short = "Valores de referência"
* component.referenceRange ^definition = "Valores de referência para auxiliar na interpretação do resultado"