Profile: BRCoreSumarioAlta
Parent: br-core-composition
Id: br-core-sumarioalta
Title: "br-core-sumarioalta"
Description: "Este perfil representa as informações da alta hospitalar, conforme a [PORTARIA Nº 701, DE 29 DE SETEMBRO DE 2022](https://bvsms.saude.gov.br/bvs/saudelegis/Saes/2022/prt0701_19_10_2022.html).
“O Sumário de Alta é um documento essencial para: 
-	Apoiar a comunicação das informações do sumário de alta entre os diversos níveis de atenção de modo eficiente, efetivo e a tempo, contribuindo para uma atenção coordenada entre os cuidadores do indivíduo e apoiando a continuidade dos seus cuidados;
-	Melhorar a qualidade da atenção em saúde e a segurança para o indivíduo com informações qualificadas, completas e oportunas que contribuam para uma conduta mais adequada às necessidades individuais de cada indivíduo e redução de efeitos adversos;
-	Contribuir para reduzir o número de reinternações evitáveis;
-	Garantir que um conjunto mínimo de informações clínicas padronizadas possa ser encaminhado e processado para múltiplos sistemas de informações em saúde, tais como prontuários eletrônicos dos indivíduos, registros eletrônicos em saúde e outros sistemas que utilizam as informações clínicas como insumos em seus processos de trabalho, facilitando a agregação e análise desses dados para tomada de decisão e produção de conhecimento;
-	Reduzir o custo com entradas manuais, integrações, mapeamento de sistemas independentes e manutenção dos sistemas de informação em saúde;
-	Prover aos desenvolvedores a especificação do conjunto de dados, mensagens de interface padronizada para a comunicação da alta, reduzindo o tempo entre o desenvolvimento e implantação da comunicação do sumário de alta;
-	Promover a simplificação e padronização das comunicações sobre os eventos de saúde entre os diversos envolvidos na atenção à saúde;
-	Alimentar o registro pessoal de saúde do indivíduo.”
"

* category 0..1

//Slicing
* section ^slicing.discriminator.type = #profile
* section ^slicing.discriminator.path = "code"
* section ^slicing.rules = #open
* section ^short = "Seções do sumário de alta"
* section ^definition = "Seções do sumário de alta"
* section 7..7
* section contains
    diagnosticosAdmissao 1..1 and
    alergiasIntolerancias 1..1 and
    diagnosticosAvaliados 1..1 and
    procedimentosRealizados 1..1 and
    prescricaoAlta 1..1 and
    planoCuidados 1..1 and
    capacidadeFuncional 1..1

//Section diagnosticosAdmissao
* section[diagnosticosAdmissao] ^short = "Seção de Resumo de Diagnósticos Admissão"
* section[diagnosticosAdmissao] ^definition = "Seção de Resumo de Diagnósticos Admissão"
* section[diagnosticosAdmissao].id ^short = "Identificador exclusivo para referência entre elementos"
* section[diagnosticosAdmissao].id ^definition = "Identificador exclusivo para referência entre elementos"
* section[diagnosticosAdmissao].extension ^short = "Conteúdo adicional definido por implementações"
* section[diagnosticosAdmissao].extension ^definition = "Conteúdo adicional definido por implementações" 
* section[diagnosticosAdmissao].modifierExtension ^short = "Extensões que não podem ser ignoradas mesmo que não sejam reconhecidas"
* section[diagnosticosAdmissao].modifierExtension ^definition = "Extensões que não podem ser ignoradas mesmo que não sejam reconhecidas"
* section[diagnosticosAdmissao].title ^short = "Título da seção - Fixo em 'Diagnósticos Admissão'"
* section[diagnosticosAdmissao].title ^definition = "Título da seção - Fixo em 'Diagnósticos Admissão'"
* section[diagnosticosAdmissao].code ^short = "Classificação da seção da Composition/Document"
* section[diagnosticosAdmissao].code ^definition = "Classificação da seção da Composition/Document"
* section[diagnosticosAdmissao].code.id ^short = "Identificador exclusivo para referência entre elementos"
* section[diagnosticosAdmissao].code.id ^definition = "Identificador exclusivo para referência entre elementos"
* section[diagnosticosAdmissao].code.extension ^short = "Conteúdo adicional definido por implementações"
* section[diagnosticosAdmissao].code.extension ^definition = "Conteúdo adicional definido por implementações"
* section[diagnosticosAdmissao].code.coding ^short = "Código definido por uma terminologia"
* section[diagnosticosAdmissao].code.coding ^definition = "Código definido por uma terminologia"
* section[diagnosticosAdmissao].code.coding.id ^short = "Identificador exclusivo para referência entre elementos"
* section[diagnosticosAdmissao].code.coding.id ^definition = "Identificador exclusivo para referência entre elementos"
* section[diagnosticosAdmissao].code.coding.extension ^short = "Conteúdo adicional definido por implementações"
* section[diagnosticosAdmissao].code.coding.extension ^definition = "Conteúdo adicional definido por implementações"
* section[diagnosticosAdmissao].code.coding.system ^short = "Identificador da terminologia"
* section[diagnosticosAdmissao].code.coding.system ^definition = "Identidade da terminologia"
* section[diagnosticosAdmissao].code.coding.system = $loinc
* section[diagnosticosAdmissao].code.coding.version ^short = "Versão da terminologia - se relevante"
* section[diagnosticosAdmissao].code.coding.version ^definition = "Versão da terminologia  - se relevante"
* section[diagnosticosAdmissao].code.coding.code ^short = "Código do conceito na sintaxe definida pela terminologia"
* section[diagnosticosAdmissao].code.coding.code ^definition = "Código do conceito na sintaxe definida pela terminologia - fixo em loinc#42347-5 'Admission Diagnosis'"
* section[diagnosticosAdmissao].code.coding.code = #42347-5
* section[diagnosticosAdmissao].code.coding.display ^short = "Descrição conforme definido pela terminologia"
* section[diagnosticosAdmissao].code.coding.display ^definition = "Representação definida pela terminologia"
* section[diagnosticosAdmissao].code.coding.display = "Admission Diagnosis"
* section[diagnosticosAdmissao].code.coding.userSelected ^short = "Se esta codificação foi escolhida diretamente pelo usuário"
* section[diagnosticosAdmissao].code.coding.userSelected ^definition = "Se esta codificação foi escolhida diretamente pelo usuário"
* section[diagnosticosAdmissao].code.text ^short = "Representação em texto do conceito"
* section[diagnosticosAdmissao].code.text ^definition = "Representação em texto do conceito"
* section[diagnosticosAdmissao].author ^short = "Quem/o quê foi o autor desta seção"
* section[diagnosticosAdmissao].author ^definition = "Quem/o quê foi o autor desta seção"
* section[diagnosticosAdmissao].focus ^short = "Sobre quem/o quê é a seção, quando não é sobre o assunto da Composition"
* section[diagnosticosAdmissao].focus ^definition = "Sobre quem/o quê é a seção, quando não é sobre o assunto da Composition"
* section[diagnosticosAdmissao].text ^short = "Resumo de texto da seção"
* section[diagnosticosAdmissao].text ^definition = "Resumo de texto da seção"
* section[diagnosticosAdmissao].mode ^short = "Método de processamento da seção"
* section[diagnosticosAdmissao].mode ^definition = "Método de processamento da seção"
* section[diagnosticosAdmissao].orderedBy ^short = "Ordem dos elementos na seção 'entry'"
* section[diagnosticosAdmissao].orderedBy ^definition = "Ordem dos elementos na seção 'entry'"
* section[diagnosticosAdmissao].entry ^short = "Medicamentos relevantes para o sumário internacional do paciente"
* section[diagnosticosAdmissao].entry ^definition = "Medicamentos relevantes para o sumário internacional do paciente"
* section[diagnosticosAdmissao].entry only Reference(br-core-condition)

//Section alergiasIntolerancias
* section[alergiasIntolerancias] ^short = "Seção de Resumo de Diagnósticos Admissão"
* section[alergiasIntolerancias] ^definition = "Seção de Resumo de Diagnósticos Admissão"
* section[alergiasIntolerancias].id ^short = "Identificador exclusivo para referência entre elementos"
* section[alergiasIntolerancias].id ^definition = "Identificador exclusivo para referência entre elementos"
* section[alergiasIntolerancias].extension ^short = "Conteúdo adicional definido por implementações"
* section[alergiasIntolerancias].extension ^definition = "Conteúdo adicional definido por implementações" 
* section[alergiasIntolerancias].modifierExtension ^short = "Extensões que não podem ser ignoradas mesmo que não sejam reconhecidas"
* section[alergiasIntolerancias].modifierExtension ^definition = "Extensões que não podem ser ignoradas mesmo que não sejam reconhecidas"
* section[alergiasIntolerancias].title ^short = "Título da seção - Fixo em 'Diagnósticos Admissão'"
* section[alergiasIntolerancias].title ^definition = "Título da seção - Fixo em 'Diagnósticos Admissão'"
* section[alergiasIntolerancias].code ^short = "Classificação da seção da Composition/Document"
* section[alergiasIntolerancias].code ^definition = "Classificação da seção da Composition/Document"
* section[alergiasIntolerancias].code.id ^short = "Identificador exclusivo para referência entre elementos"
* section[alergiasIntolerancias].code.id ^definition = "Identificador exclusivo para referência entre elementos"
* section[alergiasIntolerancias].code.extension ^short = "Conteúdo adicional definido por implementações"
* section[alergiasIntolerancias].code.extension ^definition = "Conteúdo adicional definido por implementações"
* section[alergiasIntolerancias].code.coding ^short = "Código definido por uma terminologia"
* section[alergiasIntolerancias].code.coding ^definition = "Código definido por uma terminologia"
* section[alergiasIntolerancias].code.coding.id ^short = "Identificador exclusivo para referência entre elementos"
* section[alergiasIntolerancias].code.coding.id ^definition = "Identificador exclusivo para referência entre elementos"
* section[alergiasIntolerancias].code.coding.extension ^short = "Conteúdo adicional definido por implementações"
* section[alergiasIntolerancias].code.coding.extension ^definition = "Conteúdo adicional definido por implementações"
* section[alergiasIntolerancias].code.coding.system ^short = "Identificador da terminologia"
* section[alergiasIntolerancias].code.coding.system ^definition = "Identidade da terminologia"
* section[alergiasIntolerancias].code.coding.system = $loinc
* section[alergiasIntolerancias].code.coding.version ^short = "Versão da terminologia - se relevante"
* section[alergiasIntolerancias].code.coding.version ^definition = "Versão da terminologia  - se relevante"
* section[alergiasIntolerancias].code.coding.code ^short = "Código do conceito na sintaxe definida pela terminologia"
* section[alergiasIntolerancias].code.coding.code ^definition = "Código do conceito na sintaxe definida pela terminologia - fixo em loinc#42347-5 'Admission Diagnosis'"
* section[alergiasIntolerancias].code.coding.code = #48765-2
* section[alergiasIntolerancias].code.coding.display ^short = "Descrição conforme definido pela terminologia"
* section[alergiasIntolerancias].code.coding.display ^definition = "Representação definida pela terminologia"
* section[alergiasIntolerancias].code.coding.display = "Allergies and adverse reactions Document"
* section[alergiasIntolerancias].code.coding.userSelected ^short = "Se esta codificação foi escolhida diretamente pelo usuário"
* section[alergiasIntolerancias].code.coding.userSelected ^definition = "Se esta codificação foi escolhida diretamente pelo usuário"
* section[alergiasIntolerancias].code.text ^short = "Representação em texto do conceito"
* section[alergiasIntolerancias].code.text ^definition = "Representação em texto do conceito"
* section[alergiasIntolerancias].author ^short = "Quem/o quê foi o autor desta seção"
* section[alergiasIntolerancias].author ^definition = "Quem/o quê foi o autor desta seção"
* section[alergiasIntolerancias].focus ^short = "Sobre quem/o quê é a seção, quando não é sobre o assunto da Composition"
* section[alergiasIntolerancias].focus ^definition = "Sobre quem/o quê é a seção, quando não é sobre o assunto da Composition"
* section[alergiasIntolerancias].text ^short = "Resumo de texto da seção"
* section[alergiasIntolerancias].text ^definition = "Resumo de texto da seção"
* section[alergiasIntolerancias].mode ^short = "Método de processamento da seção"
* section[alergiasIntolerancias].mode ^definition = "Método de processamento da seção"
* section[alergiasIntolerancias].orderedBy ^short = "Ordem dos elementos na seção 'entry'"
* section[alergiasIntolerancias].orderedBy ^definition = "Ordem dos elementos na seção 'entry'"
* section[alergiasIntolerancias].entry ^short = "Medicamentos relevantes para o sumário internacional do paciente"
* section[alergiasIntolerancias].entry ^definition = "Medicamentos relevantes para o sumário internacional do paciente"
* section[alergiasIntolerancias].entry only Reference(br-core-allergyintolerance)

//Section diagnosticosAvaliados
* section[diagnosticosAvaliados] ^short = "Seção de Resumo de Diagnósticos Admissão"
* section[diagnosticosAvaliados] ^definition = "Seção de Resumo de Diagnósticos Admissão"
* section[diagnosticosAvaliados].id ^short = "Identificador exclusivo para referência entre elementos"
* section[diagnosticosAvaliados].id ^definition = "Identificador exclusivo para referência entre elementos"
* section[diagnosticosAvaliados].extension ^short = "Conteúdo adicional definido por implementações"
* section[diagnosticosAvaliados].extension ^definition = "Conteúdo adicional definido por implementações" 
* section[diagnosticosAvaliados].modifierExtension ^short = "Extensões que não podem ser ignoradas mesmo que não sejam reconhecidas"
* section[diagnosticosAvaliados].modifierExtension ^definition = "Extensões que não podem ser ignoradas mesmo que não sejam reconhecidas"
* section[diagnosticosAvaliados].title ^short = "Título da seção - Fixo em 'Diagnósticos Admissão'"
* section[diagnosticosAvaliados].title ^definition = "Título da seção - Fixo em 'Diagnósticos Admissão'"
* section[diagnosticosAvaliados].code ^short = "Classificação da seção da Composition/Document"
* section[diagnosticosAvaliados].code ^definition = "Classificação da seção da Composition/Document"
* section[diagnosticosAvaliados].code.id ^short = "Identificador exclusivo para referência entre elementos"
* section[diagnosticosAvaliados].code.id ^definition = "Identificador exclusivo para referência entre elementos"
* section[diagnosticosAvaliados].code.extension ^short = "Conteúdo adicional definido por implementações"
* section[diagnosticosAvaliados].code.extension ^definition = "Conteúdo adicional definido por implementações"
* section[diagnosticosAvaliados].code.coding ^short = "Código definido por uma terminologia"
* section[diagnosticosAvaliados].code.coding ^definition = "Código definido por uma terminologia"
* section[diagnosticosAvaliados].code.coding.id ^short = "Identificador exclusivo para referência entre elementos"
* section[diagnosticosAvaliados].code.coding.id ^definition = "Identificador exclusivo para referência entre elementos"
* section[diagnosticosAvaliados].code.coding.extension ^short = "Conteúdo adicional definido por implementações"
* section[diagnosticosAvaliados].code.coding.extension ^definition = "Conteúdo adicional definido por implementações"
* section[diagnosticosAvaliados].code.coding.system ^short = "Identificador da terminologia"
* section[diagnosticosAvaliados].code.coding.system ^definition = "Identidade da terminologia"
* section[diagnosticosAvaliados].code.coding.system = $loinc
* section[diagnosticosAvaliados].code.coding.version ^short = "Versão da terminologia - se relevante"
* section[diagnosticosAvaliados].code.coding.version ^definition = "Versão da terminologia  - se relevante"
* section[diagnosticosAvaliados].code.coding.code ^short = "Código do conceito na sintaxe definida pela terminologia"
* section[diagnosticosAvaliados].code.coding.code ^definition = "Código do conceito na sintaxe definida pela terminologia - fixo em loinc#42347-5 'Admission Diagnosis'"
* section[diagnosticosAvaliados].code.coding.code = #48765-2 
* section[diagnosticosAvaliados].code.coding.display ^short = "Descrição conforme definido pela terminologia"
* section[diagnosticosAvaliados].code.coding.display ^definition = "Representação definida pela terminologia"
* section[diagnosticosAvaliados].code.coding.display = "Problem List"
* section[diagnosticosAvaliados].code.coding.userSelected ^short = "Se esta codificação foi escolhida diretamente pelo usuário"
* section[diagnosticosAvaliados].code.coding.userSelected ^definition = "Se esta codificação foi escolhida diretamente pelo usuário"
* section[diagnosticosAvaliados].code.text ^short = "Representação em texto do conceito"
* section[diagnosticosAvaliados].code.text ^definition = "Representação em texto do conceito"
* section[diagnosticosAvaliados].author ^short = "Quem/o quê foi o autor desta seção"
* section[diagnosticosAvaliados].author ^definition = "Quem/o quê foi o autor desta seção"
* section[diagnosticosAvaliados].focus ^short = "Sobre quem/o quê é a seção, quando não é sobre o assunto da Composition"
* section[diagnosticosAvaliados].focus ^definition = "Sobre quem/o quê é a seção, quando não é sobre o assunto da Composition"
* section[diagnosticosAvaliados].text ^short = "Resumo de texto da seção"
* section[diagnosticosAvaliados].text ^definition = "Resumo de texto da seção"
* section[diagnosticosAvaliados].mode ^short = "Método de processamento da seção"
* section[diagnosticosAvaliados].mode ^definition = "Método de processamento da seção"
* section[diagnosticosAvaliados].orderedBy ^short = "Ordem dos elementos na seção 'entry'"
* section[diagnosticosAvaliados].orderedBy ^definition = "Ordem dos elementos na seção 'entry'"
* section[diagnosticosAvaliados].entry ^short = "Medicamentos relevantes para o sumário internacional do paciente"
* section[diagnosticosAvaliados].entry ^definition = "Medicamentos relevantes para o sumário internacional do paciente"
* section[diagnosticosAvaliados].entry only Reference(br-core-condition)

//Section procedimentosRealizados
* section[procedimentosRealizados] ^short = "Seção de Resumo de Diagnósticos Admissão"
* section[procedimentosRealizados] ^definition = "Seção de Resumo de Diagnósticos Admissão"
* section[procedimentosRealizados].id ^short = "Identificador exclusivo para referência entre elementos"
* section[procedimentosRealizados].id ^definition = "Identificador exclusivo para referência entre elementos"
* section[procedimentosRealizados].extension ^short = "Conteúdo adicional definido por implementações"
* section[procedimentosRealizados].extension ^definition = "Conteúdo adicional definido por implementações" 
* section[procedimentosRealizados].modifierExtension ^short = "Extensões que não podem ser ignoradas mesmo que não sejam reconhecidas"
* section[procedimentosRealizados].modifierExtension ^definition = "Extensões que não podem ser ignoradas mesmo que não sejam reconhecidas"
* section[procedimentosRealizados].title ^short = "Título da seção - Fixo em 'Diagnósticos Admissão'"
* section[procedimentosRealizados].title ^definition = "Título da seção - Fixo em 'Diagnósticos Admissão'"
* section[procedimentosRealizados].code ^short = "Classificação da seção da Composition/Document"
* section[procedimentosRealizados].code ^definition = "Classificação da seção da Composition/Document"
* section[procedimentosRealizados].code.id ^short = "Identificador exclusivo para referência entre elementos"
* section[procedimentosRealizados].code.id ^definition = "Identificador exclusivo para referência entre elementos"
* section[procedimentosRealizados].code.extension ^short = "Conteúdo adicional definido por implementações"
* section[procedimentosRealizados].code.extension ^definition = "Conteúdo adicional definido por implementações"
* section[procedimentosRealizados].code.coding ^short = "Código definido por uma terminologia"
* section[procedimentosRealizados].code.coding ^definition = "Código definido por uma terminologia"
* section[procedimentosRealizados].code.coding.id ^short = "Identificador exclusivo para referência entre elementos"
* section[procedimentosRealizados].code.coding.id ^definition = "Identificador exclusivo para referência entre elementos"
* section[procedimentosRealizados].code.coding.extension ^short = "Conteúdo adicional definido por implementações"
* section[procedimentosRealizados].code.coding.extension ^definition = "Conteúdo adicional definido por implementações"
* section[procedimentosRealizados].code.coding.system ^short = "Identificador da terminologia"
* section[procedimentosRealizados].code.coding.system ^definition = "Identidade da terminologia"
* section[procedimentosRealizados].code.coding.system = $loinc
* section[procedimentosRealizados].code.coding.version ^short = "Versão da terminologia - se relevante"
* section[procedimentosRealizados].code.coding.version ^definition = "Versão da terminologia  - se relevante"
* section[procedimentosRealizados].code.coding.code ^short = "Código do conceito na sintaxe definida pela terminologia"
* section[procedimentosRealizados].code.coding.code ^definition = "Código do conceito na sintaxe definida pela terminologia - fixo em loinc#42347-5 'Admission Diagnosis'"
* section[procedimentosRealizados].code.coding.code = #47519-4
* section[procedimentosRealizados].code.coding.display ^short = "Descrição conforme definido pela terminologia"
* section[procedimentosRealizados].code.coding.display ^definition = "Representação definida pela terminologia"
* section[procedimentosRealizados].code.coding.display = "History of Procedures Document"
* section[procedimentosRealizados].code.coding.userSelected ^short = "Se esta codificação foi escolhida diretamente pelo usuário"
* section[procedimentosRealizados].code.coding.userSelected ^definition = "Se esta codificação foi escolhida diretamente pelo usuário"
* section[procedimentosRealizados].code.text ^short = "Representação em texto do conceito"
* section[procedimentosRealizados].code.text ^definition = "Representação em texto do conceito"
* section[procedimentosRealizados].author ^short = "Quem/o quê foi o autor desta seção"
* section[procedimentosRealizados].author ^definition = "Quem/o quê foi o autor desta seção"
* section[procedimentosRealizados].focus ^short = "Sobre quem/o quê é a seção, quando não é sobre o assunto da Composition"
* section[procedimentosRealizados].focus ^definition = "Sobre quem/o quê é a seção, quando não é sobre o assunto da Composition"
* section[procedimentosRealizados].text ^short = "Resumo de texto da seção"
* section[procedimentosRealizados].text ^definition = "Resumo de texto da seção"
* section[procedimentosRealizados].mode ^short = "Método de processamento da seção"
* section[procedimentosRealizados].mode ^definition = "Método de processamento da seção"
* section[procedimentosRealizados].orderedBy ^short = "Ordem dos elementos na seção 'entry'"
* section[procedimentosRealizados].orderedBy ^definition = "Ordem dos elementos na seção 'entry'"
* section[procedimentosRealizados].entry ^short = "Medicamentos relevantes para o sumário internacional do paciente"
* section[procedimentosRealizados].entry ^definition = "Medicamentos relevantes para o sumário internacional do paciente"
* section[procedimentosRealizados].entry only Reference(br-core-procedure)

//Section prescricaoAlta
* section[prescricaoAlta] ^short = "Seção de Resumo de Diagnósticos Admissão"
* section[prescricaoAlta] ^definition = "Seção de Resumo de Diagnósticos Admissão"
* section[prescricaoAlta].id ^short = "Identificador exclusivo para referência entre elementos"
* section[prescricaoAlta].id ^definition = "Identificador exclusivo para referência entre elementos"
* section[prescricaoAlta].extension ^short = "Conteúdo adicional definido por implementações"
* section[prescricaoAlta].extension ^definition = "Conteúdo adicional definido por implementações" 
* section[prescricaoAlta].modifierExtension ^short = "Extensões que não podem ser ignoradas mesmo que não sejam reconhecidas"
* section[prescricaoAlta].modifierExtension ^definition = "Extensões que não podem ser ignoradas mesmo que não sejam reconhecidas"
* section[prescricaoAlta].title ^short = "Título da seção - Fixo em 'Diagnósticos Admissão'"
* section[prescricaoAlta].title ^definition = "Título da seção - Fixo em 'Diagnósticos Admissão'"
* section[prescricaoAlta].code ^short = "Classificação da seção da Composition/Document"
* section[prescricaoAlta].code ^definition = "Classificação da seção da Composition/Document"
* section[prescricaoAlta].code.id ^short = "Identificador exclusivo para referência entre elementos"
* section[prescricaoAlta].code.id ^definition = "Identificador exclusivo para referência entre elementos"
* section[prescricaoAlta].code.extension ^short = "Conteúdo adicional definido por implementações"
* section[prescricaoAlta].code.extension ^definition = "Conteúdo adicional definido por implementações"
* section[prescricaoAlta].code.coding ^short = "Código definido por uma terminologia"
* section[prescricaoAlta].code.coding ^definition = "Código definido por uma terminologia"
* section[prescricaoAlta].code.coding.id ^short = "Identificador exclusivo para referência entre elementos"
* section[prescricaoAlta].code.coding.id ^definition = "Identificador exclusivo para referência entre elementos"
* section[prescricaoAlta].code.coding.extension ^short = "Conteúdo adicional definido por implementações"
* section[prescricaoAlta].code.coding.extension ^definition = "Conteúdo adicional definido por implementações"
* section[prescricaoAlta].code.coding.system ^short = "Identificador da terminologia"
* section[prescricaoAlta].code.coding.system ^definition = "Identidade da terminologia"
* section[prescricaoAlta].code.coding.system = $loinc
* section[prescricaoAlta].code.coding.version ^short = "Versão da terminologia - se relevante"
* section[prescricaoAlta].code.coding.version ^definition = "Versão da terminologia  - se relevante"
* section[prescricaoAlta].code.coding.code ^short = "Código do conceito na sintaxe definida pela terminologia"
* section[prescricaoAlta].code.coding.code ^definition = "Código do conceito na sintaxe definida pela terminologia - fixo em loinc#42347-5 'Admission Diagnosis'"
* section[prescricaoAlta].code.coding.code = #8654-6
* section[prescricaoAlta].code.coding.display ^short = "Descrição conforme definido pela terminologia"
* section[prescricaoAlta].code.coding.display ^definition = "Representação definida pela terminologia"
* section[prescricaoAlta].code.coding.display = "Hospital discharge medications"
* section[prescricaoAlta].code.coding.userSelected ^short = "Se esta codificação foi escolhida diretamente pelo usuário"
* section[prescricaoAlta].code.coding.userSelected ^definition = "Se esta codificação foi escolhida diretamente pelo usuário"
* section[prescricaoAlta].code.text ^short = "Representação em texto do conceito"
* section[prescricaoAlta].code.text ^definition = "Representação em texto do conceito"
* section[prescricaoAlta].author ^short = "Quem/o quê foi o autor desta seção"
* section[prescricaoAlta].author ^definition = "Quem/o quê foi o autor desta seção"
* section[prescricaoAlta].focus ^short = "Sobre quem/o quê é a seção, quando não é sobre o assunto da Composition"
* section[prescricaoAlta].focus ^definition = "Sobre quem/o quê é a seção, quando não é sobre o assunto da Composition"
* section[prescricaoAlta].text ^short = "Resumo de texto da seção"
* section[prescricaoAlta].text ^definition = "Resumo de texto da seção"
* section[prescricaoAlta].mode ^short = "Método de processamento da seção"
* section[prescricaoAlta].mode ^definition = "Método de processamento da seção"
* section[prescricaoAlta].orderedBy ^short = "Ordem dos elementos na seção 'entry'"
* section[prescricaoAlta].orderedBy ^definition = "Ordem dos elementos na seção 'entry'"
* section[prescricaoAlta].entry ^short = "Medicamentos relevantes para o sumário internacional do paciente"
* section[prescricaoAlta].entry ^definition = "Medicamentos relevantes para o sumário internacional do paciente"
* section[prescricaoAlta].entry only Reference(br-core-medicationrequest)

//Section planoCuidados
* section[planoCuidados] ^short = "Seção de Resumo de Diagnósticos Admissão"
* section[planoCuidados] ^definition = "Seção de Resumo de Diagnósticos Admissão"
* section[planoCuidados].id ^short = "Identificador exclusivo para referência entre elementos"
* section[planoCuidados].id ^definition = "Identificador exclusivo para referência entre elementos"
* section[planoCuidados].extension ^short = "Conteúdo adicional definido por implementações"
* section[planoCuidados].extension ^definition = "Conteúdo adicional definido por implementações" 
* section[planoCuidados].modifierExtension ^short = "Extensões que não podem ser ignoradas mesmo que não sejam reconhecidas"
* section[planoCuidados].modifierExtension ^definition = "Extensões que não podem ser ignoradas mesmo que não sejam reconhecidas"
* section[planoCuidados].title ^short = "Título da seção - Fixo em 'Diagnósticos Admissão'"
* section[planoCuidados].title ^definition = "Título da seção - Fixo em 'Diagnósticos Admissão'"
* section[planoCuidados].code ^short = "Classificação da seção da Composition/Document"
* section[planoCuidados].code ^definition = "Classificação da seção da Composition/Document"
* section[planoCuidados].code.id ^short = "Identificador exclusivo para referência entre elementos"
* section[planoCuidados].code.id ^definition = "Identificador exclusivo para referência entre elementos"
* section[planoCuidados].code.extension ^short = "Conteúdo adicional definido por implementações"
* section[planoCuidados].code.extension ^definition = "Conteúdo adicional definido por implementações"
* section[planoCuidados].code.coding ^short = "Código definido por uma terminologia"
* section[planoCuidados].code.coding ^definition = "Código definido por uma terminologia"
* section[planoCuidados].code.coding.id ^short = "Identificador exclusivo para referência entre elementos"
* section[planoCuidados].code.coding.id ^definition = "Identificador exclusivo para referência entre elementos"
* section[planoCuidados].code.coding.extension ^short = "Conteúdo adicional definido por implementações"
* section[planoCuidados].code.coding.extension ^definition = "Conteúdo adicional definido por implementações"
* section[planoCuidados].code.coding.system ^short = "Identificador da terminologia"
* section[planoCuidados].code.coding.system ^definition = "Identidade da terminologia"
* section[planoCuidados].code.coding.system = $loinc
* section[planoCuidados].code.coding.version ^short = "Versão da terminologia - se relevante"
* section[planoCuidados].code.coding.version ^definition = "Versão da terminologia  - se relevante"
* section[planoCuidados].code.coding.code ^short = "Código do conceito na sintaxe definida pela terminologia"
* section[planoCuidados].code.coding.code ^definition = "Código do conceito na sintaxe definida pela terminologia - fixo em loinc#42347-5 'Admission Diagnosis'"
* section[planoCuidados].code.coding.code = #18776-5
* section[planoCuidados].code.coding.display ^short = "Descrição conforme definido pela terminologia"
* section[planoCuidados].code.coding.display ^definition = "Representação definida pela terminologia"
* section[planoCuidados].code.coding.display = "Plan of care note"
* section[planoCuidados].code.coding.userSelected ^short = "Se esta codificação foi escolhida diretamente pelo usuário"
* section[planoCuidados].code.coding.userSelected ^definition = "Se esta codificação foi escolhida diretamente pelo usuário"
* section[planoCuidados].code.text ^short = "Representação em texto do conceito"
* section[planoCuidados].code.text ^definition = "Representação em texto do conceito"
* section[planoCuidados].author ^short = "Quem/o quê foi o autor desta seção"
* section[planoCuidados].author ^definition = "Quem/o quê foi o autor desta seção"
* section[planoCuidados].focus ^short = "Sobre quem/o quê é a seção, quando não é sobre o assunto da Composition"
* section[planoCuidados].focus ^definition = "Sobre quem/o quê é a seção, quando não é sobre o assunto da Composition"
* section[planoCuidados].text ^short = "Resumo de texto da seção"
* section[planoCuidados].text ^definition = "Resumo de texto da seção"
* section[planoCuidados].mode ^short = "Método de processamento da seção"
* section[planoCuidados].mode ^definition = "Método de processamento da seção"
* section[planoCuidados].orderedBy ^short = "Ordem dos elementos na seção 'entry'"
* section[planoCuidados].orderedBy ^definition = "Ordem dos elementos na seção 'entry'"
* section[planoCuidados].entry ^short = "Medicamentos relevantes para o sumário internacional do paciente"
* section[planoCuidados].entry ^definition = "Medicamentos relevantes para o sumário internacional do paciente"
* section[planoCuidados].entry only Reference(br-core-careplan)

//Section capacidadeFuncional
* section[capacidadeFuncional] ^short = "Seção de Resumo de Diagnósticos Admissão"
* section[capacidadeFuncional] ^definition = "Seção de Resumo de Diagnósticos Admissão"
* section[capacidadeFuncional].id ^short = "Identificador exclusivo para referência entre elementos"
* section[capacidadeFuncional].id ^definition = "Identificador exclusivo para referência entre elementos"
* section[capacidadeFuncional].extension ^short = "Conteúdo adicional definido por implementações"
* section[capacidadeFuncional].extension ^definition = "Conteúdo adicional definido por implementações" 
* section[capacidadeFuncional].modifierExtension ^short = "Extensões que não podem ser ignoradas mesmo que não sejam reconhecidas"
* section[capacidadeFuncional].modifierExtension ^definition = "Extensões que não podem ser ignoradas mesmo que não sejam reconhecidas"
* section[capacidadeFuncional].title ^short = "Título da seção - Fixo em 'Diagnósticos Admissão'"
* section[capacidadeFuncional].title ^definition = "Título da seção - Fixo em 'Diagnósticos Admissão'"
* section[capacidadeFuncional].code ^short = "Classificação da seção da Composition/Document"
* section[capacidadeFuncional].code ^definition = "Classificação da seção da Composition/Document"
* section[capacidadeFuncional].code.id ^short = "Identificador exclusivo para referência entre elementos"
* section[capacidadeFuncional].code.id ^definition = "Identificador exclusivo para referência entre elementos"
* section[capacidadeFuncional].code.extension ^short = "Conteúdo adicional definido por implementações"
* section[capacidadeFuncional].code.extension ^definition = "Conteúdo adicional definido por implementações"
* section[capacidadeFuncional].code.coding ^short = "Código definido por uma terminologia"
* section[capacidadeFuncional].code.coding ^definition = "Código definido por uma terminologia"
* section[capacidadeFuncional].code.coding.id ^short = "Identificador exclusivo para referência entre elementos"
* section[capacidadeFuncional].code.coding.id ^definition = "Identificador exclusivo para referência entre elementos"
* section[capacidadeFuncional].code.coding.extension ^short = "Conteúdo adicional definido por implementações"
* section[capacidadeFuncional].code.coding.extension ^definition = "Conteúdo adicional definido por implementações"
* section[capacidadeFuncional].code.coding.system ^short = "Identificador da terminologia"
* section[capacidadeFuncional].code.coding.system ^definition = "Identidade da terminologia"
* section[capacidadeFuncional].code.coding.system = $loinc
* section[capacidadeFuncional].code.coding.version ^short = "Versão da terminologia - se relevante"
* section[capacidadeFuncional].code.coding.version ^definition = "Versão da terminologia  - se relevante"
* section[capacidadeFuncional].code.coding.code ^short = "Código do conceito na sintaxe definida pela terminologia"
* section[capacidadeFuncional].code.coding.code ^definition = "Código do conceito na sintaxe definida pela terminologia - fixo em loinc#42347-5 'Admission Diagnosis'"
* section[capacidadeFuncional].code.coding.code = #54522-8
* section[capacidadeFuncional].code.coding.display ^short = "Descrição conforme definido pela terminologia"
* section[capacidadeFuncional].code.coding.display ^definition = "Representação definida pela terminologia"
* section[capacidadeFuncional].code.coding.display = "Functional status"
* section[capacidadeFuncional].code.coding.userSelected ^short = "Se esta codificação foi escolhida diretamente pelo usuário"
* section[capacidadeFuncional].code.coding.userSelected ^definition = "Se esta codificação foi escolhida diretamente pelo usuário"
* section[capacidadeFuncional].code.text ^short = "Representação em texto do conceito"
* section[capacidadeFuncional].code.text ^definition = "Representação em texto do conceito"
* section[capacidadeFuncional].author ^short = "Quem/o quê foi o autor desta seção"
* section[capacidadeFuncional].author ^definition = "Quem/o quê foi o autor desta seção"
* section[capacidadeFuncional].focus ^short = "Sobre quem/o quê é a seção, quando não é sobre o assunto da Composition"
* section[capacidadeFuncional].focus ^definition = "Sobre quem/o quê é a seção, quando não é sobre o assunto da Composition"
* section[capacidadeFuncional].text ^short = "Resumo de texto da seção"
* section[capacidadeFuncional].text ^definition = "Resumo de texto da seção"
* section[capacidadeFuncional].mode ^short = "Método de processamento da seção"
* section[capacidadeFuncional].mode ^definition = "Método de processamento da seção"
* section[capacidadeFuncional].orderedBy ^short = "Ordem dos elementos na seção 'entry'"
* section[capacidadeFuncional].orderedBy ^definition = "Ordem dos elementos na seção 'entry'"
* section[capacidadeFuncional].entry ^short = "Medicamentos relevantes para o sumário internacional do paciente"
* section[capacidadeFuncional].entry ^definition = "Medicamentos relevantes para o sumário internacional do paciente"
* section[capacidadeFuncional].entry only Reference(br-core-capacidadefuncional)