Profile: BRCoreMedicationAdministration
Parent: http://hl7.org/fhir/StructureDefinition/MedicationAdministration
Id: br-core-medicationadministration
Title: "br-core-medicationadministration"
Description: "Descreve o evento de um paciente consumindo ou de algum medicamento sendo administrado a um paciente. Isso pode ser tão simples quanto engolir um comprimido ou pode ser uma infusão de longa duração. Recursos relacionados vinculam esse evento à prescrição de autorização e ao atendimento specífco entre o paciente e o profissional de saúde"

* id ^short = "Identificador lógico deste artefato"
* id ^definition = "Identificador lógico deste artefato"
* meta ^short = "Metadados sobre o recurso"
* meta ^definition = "Metadados sobre o recurso" 
* implicitRules ^short = "Um conjunto de regras sob as quais este conteúdo foi criado"
* implicitRules ^definition = "Um conjunto de regras sob as quais este conteúdo foi criado"
* language ^short = "Idioma do recurso"
* language ^definition = "Idioma do recurso"
* text ^short = "Resumo do texto do recurso em linguagem natural"
* text ^definition = "Resumo do texto do recurso em linguagem natural"
* contained ^short = "Recursos contidos no recurso"
* contained ^definition = "Recursos contidos no recurso"
* extension ^short = "Extensões adicionais que não fazem parte do modelo base"
* extension ^definition = "Extensões adicionais que não fazem parte do modelo base"
* modifierExtension ^short = "Extensões adicionais que não podem ser ignoradas, mesmo que não reconhecidas"
* modifierExtension ^definition = "Extensões adicionais que não podem ser ignoradas, mesmo que não reconhecidas"
* identifier ^short = "Identificadores externos para este recurso"
* identifier ^definition = "Identificadores externos para este recurso"
* instantiates ^short = "Instancia protocolo ou definição"
* instantiates ^definition = "Instancia protocolo ou definição"
* partOf ^short = "Parte do evento referenciado"
* partOf ^definition = "Parte do evento referenciado"
* partOf only Reference(br-core-medicationadministration or br-core-procedure)
* status ^short = "Códigos de status de administração de medicamentos"
* status ^definition = "Códigos de status de administração de medicamentos"
* statusReason ^short = "Motivo da não realização da administração"
* statusReason ^definition = "Motivo da não realização da administração"
* statusReason from https://terminologia.saude.gov.br/fhir/ValueSet/reason-medication-not-given (example)
* category ^short = "Tipo de uso de medicamentos"
* category ^definition = "Tipo de uso de medicamentos"
* medication[x] ^short = "O que foi administrado"
* medication[x] ^definition = "O que foi administrado"
* subject ^short = "Referência ao paciente que recebeu o medicamento"
* subject ^definition = "Referência ao paciente que recebeu o medicamento"
* subject only Reference(br-core-patient)
* context ^short = "Referência ao atendimento que administrou o medicamento"
* context ^definition = "Referência ao atendimento que administrou o medicamento"
* context only Reference(br-core-encounter)
* supportingInformation ^short = "Informações adicionais para suporte à administração"
* supportingInformation ^definition = "Informações adicionais para suporte à administração"
* effective[x] ^short = "Hora de início e término da administração do medicamento"
* effective[x] ^definition = "Hora de início e término da administração do medicamento"
* performer ^short = "Quem realizou a administração da medicamento e o que eles fizeram"
* performer ^definition = "Quem realizou a administração da medicamento e o que eles fizeram"
* performer.id ^short = "Identificador exclusivo para referência entre elementos"
* performer.id ^definition = "Identificador exclusivo para referência entre elementos" 
* performer.extension ^short = "Conteúdo adicional definido pelas implementações"
* performer.extension ^definition = "Conteúdo adicional definido pelas implementações"
* performer.modifierExtension ^short = "Extensões que não podem ser ignoradas mesmo que não sejam reconhecidas"
* performer.modifierExtension ^definition = "Extensões que não podem ser ignoradas mesmo que não sejam reconhecidas" 
* performer.function ^short = "Função do profissional que administrou o medicamento"
* performer.function ^definition = "Função do profissional que administrou o medicamento"
* performer.function from http://hl7.org/fhir/ValueSet/med-admin-perform-function (example)
* performer.actor ^short = "Referência ao profissional que realizou a administraçãoexampleamento"
* performer.actor ^definition = "Referência ao profissional que realizou a administração do medicamento"
* performer.actor only Reference(br-core-practitioner or br-core-practitionerrole or br-core-patient or br-core-relatedperson or Device)
* reasonCode ^short = "Motivo da administração do medicamento"
* reasonCode ^definition = "Motivo da administração do medicamento"
* reasonReference ^short = "Referência à condição ou observação que é o motivo da administração do medicamento"
* reasonReference ^definition = "Referência à condição ou observação que é o motivo da administração do medicamento"
* reasonReference only Reference(br-core-condition or br-core-observation or br-core-diagnosticreport)
* request ^short = "Referência à solicitação do medicamento"
* request ^definition = "Referência à solicitação do medicamento"
* request only Reference(br-core-medicationrequest)
* device ^short = "Referência ao dispositivo utilizado para administrar o medicamento"
* device ^definition = "Referência ao dispositivo utilizado para administrar o medicamento"
* note ^short = "Informações sobre a administração do medicamento"
* note ^definition = "Informações sobre a administração do medicamento"
* dosage ^short = "Dose administrada do medicamento"
* dosage ^definition = "Dose administrada do medicamento"
* dosage.id ^short = "Identificador exclusivo para referência entre elementos"
* dosage.id ^definition = "Identificador exclusivo para referência entre elementos" 
* dosage.extension ^short = "Conteúdo adicional definido pelas implementações"
* dosage.extension ^definition = "Conteúdo adicional definido pelas implementações"
* dosage.modifierExtension ^short = "Extensões que não podem ser ignoradas mesmo que não sejam reconhecidas"
* dosage.modifierExtension ^definition = "Extensões que não podem ser ignoradas mesmo que não sejam reconhecidas" 
* dosage.text ^short = "Instruções de dosagem em texto livre, por exemplo, SIG"
* dosage.text ^definition = "Instruções de dosagem em texto livre, por exemplo, SIG"
* dosage.site ^short = "Local do corpo que o corpo foi administrado"
* dosage.site ^definition = "Local do corpo que o corpo foi administrado"
* dosage.site from http://hl7.org/fhir/ValueSet/body-site (example)
* dosage.route ^short = "Via de administração do medicamento"
* dosage.route ^definition = "Via de administração do medicamento"
* dosage.route from http://hl7.org/fhir/uv/ips/ValueSet/medicine-route-of-administration (example)
* dosage.method ^short = "Método de admnistração do medicamento"
* dosage.method ^definition = "Método de admnistração do medicamento"
* dosage.dose ^short = "Quantidade da dose do medicamento"
* dosage.dose ^definition = "Quantidade da dose do medicamento"
* dosage.rate[x] ^short = "Quantidade da dose por unidade de tempo"
* dosage.rate[x] ^definition = "Quantidade da dose por unidade de tempo"
* eventHistory ^short = "Referência à uma lista de eventos"
* eventHistory ^definition = "Referência à uma lista de eventos"
